use ods;
drop table if exists odstmp_bims_biz_customer_rel_common;
CREATE TABLE ods.odstmp_bims_biz_customer_rel_common (
  id STRING COMMENT 'ID',
  apply_no STRING COMMENT '申请编号',
  customer_no STRING COMMENT '客户编号',
  house_portion DOUBLE COMMENT '房产份额',
  relation STRING COMMENT '关系类型，这里匹配字典表里面的买卖双方关系人定义',
  `role` STRING COMMENT '客户角色买方BUY 卖方：SEL',
  is_proposer STRING COMMENT '是否申请人',
  create_user_id STRING COMMENT '创建人id',
  update_user_id STRING COMMENT '更新人id',
  create_time TIMESTAMP COMMENT '记录创建时间',
  update_time TIMESTAMP COMMENT '记录更新时间',
  rev bigint comment '版本号',
  delete_flag STRING COMMENT '记录删除标识(1：删除；0：有效记录)',
  is_actual_borrower_name STRING COMMENT '是否主借款人',
  has_common_borrower STRING COMMENT '是否有共同借款人',
  borrower_relation STRING COMMENT '与借款人关系',
  other_relation STRING COMMENT '其他关系（抵押贷存放配偶客户编号',
  relation_name STRING,
  role_name STRING,
   name STRING COMMENT '姓名',
   sex STRING COMMENT '性别',
   phone STRING COMMENT '客户联系方式',
   age bigint comment '年龄',
   id_card_type STRING COMMENT '证件类型',
   id_card_validity STRING COMMENT '证件有效期',
   id_card_no STRING COMMENT '证件号码',
   id_card_address STRING COMMENT '证件显示地址',
   marital_status STRING COMMENT '婚姻状态',
   education STRING COMMENT '教育程度',
   degree STRING COMMENT '学位',
   has_children STRING COMMENT '有无子女',
   address STRING COMMENT '家庭住址',
   income_type STRING COMMENT '收入类型',
   monthly_income DOUBLE COMMENT '月收入',
   employer STRING COMMENT '工作单位',
   former_name STRING COMMENT '曾用名',
   former_id_card STRING COMMENT '曾用身份证号',
   email STRING COMMENT '电子邮箱',
   house_create_user_id STRING COMMENT '创建人id',
   house_update_user_id STRING COMMENT '更新人id',
   house_create_time TIMESTAMP COMMENT '记录创建时间',
   house_update_time TIMESTAMP COMMENT '记录更新时间',
   house_rev bigint comment '版本号',
   house_delete_flag STRING COMMENT '记录删除标识(1：删除；0：有效记录)',
   family_year_income DOUBLE COMMENT '家庭年收入',
   contact_address STRING COMMENT '通讯地址',
   industry STRING COMMENT '所属行业',
   year_income DOUBLE COMMENT '个人年收入',
   birthday STRING COMMENT '出生日期',
   idcard_organ STRING COMMENT '身份证发证机关所在地',
   origin_province STRING COMMENT '户籍所在地省份',
   origin_city STRING COMMENT '户籍所在地市',
   origin_district STRING COMMENT '户籍所在地区',
   origin_type STRING COMMENT '户籍类型，本地，非本地',
   origin_detailaddr STRING COMMENT '户籍详细地址',
   origin_belong STRING COMMENT '户籍所属地，城市户口，农村户口',
   house_province STRING COMMENT '房产地址省',
   house_city STRING COMMENT '房产地址市',
   house_district STRING COMMENT '房产地址区',
   house_detailaddr STRING COMMENT '房产详细地址',
   live_province STRING COMMENT '居住地区省',
   live_city STRING COMMENT '居住地区市',
   live_district STRING COMMENT '居住地区区',
   live_zipcode STRING COMMENT '住宅邮编',
   live_detailaddr STRING COMMENT '详细住宅详细地址',
   default_mail_address STRING COMMENT '首选邮寄地址',
   has_house STRING COMMENT '有无房产',
   has_localhouse STRING COMMENT '有无本地房产',
   qq_number STRING COMMENT 'QQ',
   wechat_number STRING COMMENT '微信',
   default_contact_type STRING COMMENT '首选联系方式',
   company_name STRING COMMENT '工作单位',
   income_company_type STRING COMMENT '单位性质 国有，私营，个体，股份',
   company_department STRING COMMENT '所属部门',
   company_workyear STRING COMMENT '现单位工作年限',
   establishment_year STRING COMMENT '企业成立年限',
   has_register STRING COMMENT '是否注册',
   occupancy STRING COMMENT '占股情况',
   individual_type STRING COMMENT '个人类型，公务员，受薪，个体',
   job_type STRING COMMENT '职务类型，科负责人，处负责人，普通员工',
   company_telareacode STRING COMMENT '单位固话区号',
   company_tel STRING COMMENT '单位固话',
   company_zipcode STRING COMMENT '单位邮编',
   company_hr STRING COMMENT '人事部联系人',
   company_hrphone STRING COMMENT '人事部联系电话',
   company_hrtelareacode STRING COMMENT '人事部固话区号',
   company_hrtel STRING COMMENT '人事部固话',
   company_province STRING COMMENT '单位地址，省',
   company_city STRING COMMENT '单位地址，市',
   company_district STRING COMMENT '单位地址，区',
   month_income STRING,
   has_car STRING COMMENT '有无汽车',
   customer_type STRING COMMENT '客户类型 标准受薪，优良职业，自雇人士',
   residence_settle STRING COMMENT '户口所在地(对应字典项hkszd)',
   home_telareacode STRING COMMENT '家庭电话区号',
   home_telephone STRING COMMENT '家庭电话',
   employer_address STRING COMMENT '单位地址',
   employer_phone STRING COMMENT '单位电话',
   work_nature STRING COMMENT '工作性质',
   occupation STRING COMMENT '职业名称',
   headship STRING COMMENT '职务类型',
   techpost STRING COMMENT '职称',
   family_status STRING COMMENT '居住状况',
   industry_type STRING COMMENT '所属行业（待会删除掉）',
   special_area_code STRING COMMENT '联系人座机区号',
   special_state_area_code STRING COMMENT '联系人座机国家区号',
   explaintext STRING COMMENT '联系人其他说明',
   graduation_school STRING COMMENT '毕业学校',
   graduation_date STRING COMMENT '毕业时间',
   house_house_portion DOUBLE COMMENT '房产份额',
   credit_channel STRING COMMENT '征信获取方式',
   credit_souruce STRING COMMENT '征信查询供应商',
   and_guarantee_relation STRING COMMENT '与抵押人关系；字典：AndGuaranteeRelationType',
   provide_other_personal_local_residences STRING COMMENT '是否提供本人当地其他住宅',
   borrower_profession_name STRING COMMENT '借款人职业名称',
   borrower_industry_name STRING COMMENT '借款人行业名称',
   marital_status_name STRING COMMENT '婚姻状态名',
   marital_status_tag STRING COMMENT '婚姻状态标识',
   income_type_name STRING COMMENT '收入类型名',
   customer_type_name STRING COMMENT '客户类型名 标准受薪，优良职业，自雇人士',
   individual_type_name STRING COMMENT '个人类型名，公务员，受薪，个体'
) STORED AS parquet;

insert overwrite table odstmp_bims_biz_customer_rel_common
select * from (select a.*,
d.`NAME_` relation_name,
a.`role`role_name,
b.`name`,
b.`sex`,
b.`phone`,
b.`age`,
b.`id_card_type`,
b.`id_card_validity`,
b.`id_card_no`,
b.`id_card_address`,
b.`marital_status`,
b.`education`,
b.`degree`,
b.`has_children`,
b.`address`,
b.`income_type`,
b.`monthly_income`,
b.`employer`,
b.`former_name`,
b.`former_id_card`,
b.`email`,
b.`create_user_id` house_create_user_id,
b.`update_user_id` house_update_user_id,
b.`create_time` house_create_time,
b.`update_time` house_update_time,
b.`rev` house_rev,
b.`delete_flag` house_delete_flag,
b.`family_year_income`,
b.`contact_address`,
b.`industry`,
b.`year_income`,
b.`birthday`,
b.`idcard_organ`,
b.`origin_province`,
b.`origin_city`,
b.`origin_district`,
b.`origin_type`,
b.`origin_detailaddr`,
b.`origin_belong`,
b.`house_province`,
b.`house_city`,
b.`house_district`,
b.`house_detailaddr`,
b.`live_province`,
b.`live_city`,
b.`live_district`,
b.`live_zipcode`,
b.`live_detailaddr`,
b.`default_mail_address`,
b.`has_house`,
b.`has_localhouse`,
b.`qq_number`,
b.`wechat_number`,
b.`default_contact_type`,
b.`company_name`,
b.`income_company_type`,
b.`company_department`,
b.`company_workyear`,
b.`establishment_year`,
b.`has_register`,
b.`occupancy`,
b.`individual_type`,
b.`job_type`,
b.`company_telareacode`,
b.`company_tel`,
b.`company_zipcode`,
b.`company_hr`,
b.`company_hrphone`,
b.`company_hrtelareacode`,
b.`company_hrtel`,
b.`company_province`,
b.`company_city`,
b.`company_district`,
b.`month_income`,
b.`has_car`,
b.`customer_type`,
b.`residence_settle`,
b.`home_telareacode`,
b.`home_telephone`,
b.`employer_address`,
b.`employer_phone`,
b.`work_nature`,
b.`occupation`,
b.`headship`,
b.`techpost`,
b.`family_status`,
b.`industry_type`,
b.`special_area_code`,
b.`special_state_area_code`,
b.`explaintext`,
b.`graduation_school`,
b.`graduation_date`,
b.`house_portion` house_house_portion,
b.`credit_channel`,
b.`credit_souruce`,
b.`and_guarantee_relation`,
b.`provide_other_personal_local_residences`,
b.`borrower_profession_name`,
b.`borrower_industry_name`,
regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(lower(marital_status),'30','丧偶'),'div','离异'),'mri','已婚'),'^umr','未婚'),'^ly$','离异'),'^so$','丧偶'),'^wh$','未婚'),'^yh$','已婚') marital_status_name,
regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(lower(marital_status),'30','否'),'div','否'),'mri','是'),'^umr','否'),'^ly$','否'),'^so$','否'),'^wh$','否'),'^yh$','是') marital_status_tag,
regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(lower(income_type),'com','标准受薪'),'god','优良职业'),'slf','自雇人士'),'^自雇人士$','自雇人士'),'^受薪$','标准受薪'),'^oth$','其他') income_type_name,
regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(lower(customer_type),'com','标准受薪'),'god','优良职业'),'slf','自雇人士'),'^自雇人士$','自雇人士'),'^受薪$','标准受薪'),'^oth$','其他') customer_type_name,
f.NAME_ 'individual_type_name'
from ods_bims_biz_customer_rel a
left join ods_bims_biz_customer b on a.customer_no=b.cust_no
left join (select DISTINCT KEY_,NAME_new_ NAME_ from ods_bims_sys_dic_common where TYPE_ID_='10000039280202' or TYPE_ID_='10000042605398' or TYPE_ID_='10000057640173' or TYPE_ID_='10000060310225' )d on d.KEY_=lower(a.`relation`)
left join (select DISTINCT KEY_,NAME_new_ NAME_ from ods_bims_sys_dic_common where TYPE_ID_='10000010830911' or TYPE_ID_='10000057530172' or TYPE_ID_='10000034210010' or TYPE_ID_='10000025010002' or  TYPE_ID_='10000001220223' or TYPE_ID_='10000034210010' or TYPE_ID_='1000000122021' or TYPE_ID_='10000033770002' )e on e.KEY_=lower(a.`role`)
left join (select DISTINCT KEY_,NAME_new_ NAME_ from ods_bims_sys_dic_common where TYPE_ID_='10000038180237' )f on f.KEY_=lower(b.`individual_type`)
)T order by is_actual_borrower_name desc;

drop table if exists ods_bims_biz_customer_rel_common;
ALTER TABLE odstmp_bims_biz_customer_rel_common RENAME TO ods_bims_biz_customer_rel_common;