use ods;
insert overwrite table ods.ods_rcs_icrCreditInfo
select
reportBaseInfo.reportNo `reportNo`,
reportBaseInfo.queryTime `queryTime`,
reportBaseInfo.reportCreateTime `reportCreateTime`,
reportBaseInfo.name `queryname`,
reportBaseInfo.certType `querycertType`,
reportBaseInfo.certNo `querycertNo`,
reportBaseInfo.operateUser `operateUser`,
reportBaseInfo.queryReason `queryReason`,
icrIdentity.gender `icrIdentity`,
icrIdentity.birthday `birthday`,
icrIdentity.maritalState `maritalState`,
icrIdentity.mobile `mobile`,
icrIdentity.officetelePhoneno `officetelePhoneno`,
icrIdentity.hometelePhoneno `hometelePhoneno`,
icrIdentity.edulevel `edulevel`,
icrIdentity.edudegree `edudegree`,
icrIdentity.postAddress `postAddress`,
icrIdentity.registeredAddress `registeredAddress`,
icrSpouse.name `spouse_name`,
icrSpouse.certType `spouse_certType`,
icrSpouse.certNo `spouse_certNo`,
icrSpouse.employer `spouse_mployer`,
icrSpouse.telephoneNo `spouse_telephoneNo`,
icrResidence.serialNo `serialNo`,
icrResidence.address `address`,
icrResidence.residenceType `residenceType`,
icrResidence.getTime `residencegetTime`,
icrProfessional.employer `employer`,
icrProfessional.employerAddress `employerAddress`,
icrProfessional.occupation `occupation`,
icrProfessional.industry `industry`,
icrProfessional.duty `duty`,
icrProfessional.title `title`,
icrProfessional.startYear `startYear`,
icrProfessional.getTime `professionalgetTime`,
icrCreditCue.houseLoanCount `houseLoanCount`,
icrCreditCue.houseLoan2Count `houseLoan2Count`,
icrCreditCue.otherLoanCount `otherLoanCount`,
icrCreditCue.firstLoanOpenMonth `firstLoanOpenMonth`,
icrCreditCue.loanCardCount `loanCardCount`,
icrCreditCue.firstLoanCardOpenMonth `firstLoanCardOpenMonth`,
icrCreditCue.standardLoanCardCount `standardLoanCardCount`,
icrCreditCue.firstStandardLoanCardOpenMonth `firstStandardLoanCardOpenMonth`,
icrCreditCue.announceCount `announceCount`,
icrCreditCue.dissentCount `dissentCount`,
icrOverdueSummary.count `count`,
icrOverdueSummary.months `months`,
icrOverdueSummary.highestOverdueAmountPermon `highestOverdueAmountPermon`,
icrOverdueSummary.maxDuration `maxDuration`,
icrOverdueSummary.count2 `count2`,
icrOverdueSummary.months2 `months2`,
icrOverdueSummary.highestOverdueAmountPermon2 `highestOverdueAmountPermon2`,
icrOverdueSummary.maxDuration2 `maxDuration2`,
icrOverdueSummary.count3 `count3`,
icrOverdueSummary.months3 `months3`,
icrOverdueSummary.highestOverdueAmountPermon3 `highestOverdueAmountPermon3`,
icrOverdueSummary.maxDuration3 `maxDuration3`,
icrUnpaidLoan.financeCorpCount `unpaidLoan_financeCorpCount`,
icrUnpaidLoan.financeOrgCount `unpaidLoan_financeOrgCount`,
icrUnpaidLoan.accountCount `unpaidLoan_accountCount`,
icrUnpaidLoan.creditLimit `unpaidLoan_creditLimit`,
icrUnpaidLoan.balance `unpaidLoan_balance`,
icrUnpaidLoan.latest6MonthUseDavgAmount `unpaidLoan_latest6MonthUseDavgAmount`,
cast (icrUndestoryLoanCard.financeCorpCount  as double ) `undestoryLoanCard_financeCorpCount`,
icrUndestoryLoanCard.financeOrgCount `undestoryLoanCard_financeOrgCount`,
icrUndestoryLoanCard.accountCount `undestoryLoanCard_accountCount`,
icrUndestoryLoanCard.creditLimit `undestoryLoanCard_creditLimit`,
icrUndestoryLoanCard.maxCreditLimitPerOrg `undestoryLoanCard_maxCreditLimitPerOrg`,
icrUndestoryLoanCard.minCreditLimitPerOrg `undestoryLoanCard_minCreditLimitPerOrg`,
icrUndestoryLoanCard.usedCreditLimit `undestoryLoanCard_usedCreditLimit`,
icrUndestoryLoanCard.latest6MonthUseDavgAmount `undestoryLoanCard_latest6MonthUseDavgAmount`
from ods_rcs_reportBaseInfo reportBaseInfo left join
ods_rcs_icrIdentity icrIdentity on icrIdentity.reportno=reportBaseInfo.reportno left join
(select reportno,
group_concat(name) 'name',
group_concat(certType) 'certType',
group_concat(certNo) 'certNo',
group_concat(employer) 'employer',
group_concat(telephoneNo) 'telephoneNo'
from ods_rcs_icrSpouse group by reportno) icrSpouse on icrSpouse.reportno=reportBaseInfo.reportno
left join (
select reportno,
group_concat(serialNo) 'serialNo',
group_concat(address) 'address',
group_concat(residenceType) 'residenceType',
group_concat(getTime) 'getTime'
from ods_rcs_icrResidence  group by reportno) icrResidence on icrResidence.reportno=reportBaseInfo.reportno
left join
(select reportno,
group_concat(employer) 'employer',
group_concat(employerAddress) 'employerAddress',
group_concat(occupation) 'occupation',
group_concat(industry) 'industry',
group_concat(duty) 'duty',
group_concat(title) 'title',
group_concat(startYear) 'startYear',
group_concat(getTime) 'getTime'
from ods_rcs_icrProfessional group by reportno
)icrProfessional on icrProfessional.reportno=reportBaseInfo.reportno
left join ods_rcs_icrCreditCue icrCreditCue on icrCreditCue.reportno=reportBaseInfo.reportno
left join ods_rcs_icrOverdueSummary icrOverdueSummary on icrOverdueSummary.reportno=reportBaseInfo.reportno
left join ods_rcs_icrUnpaidLoan icrUnpaidLoan on icrUnpaidLoan.reportno=reportBaseInfo.reportno
left join ods_rcs_icrUndestoryLoanCard icrUndestoryLoanCard on icrUndestoryLoanCard.reportno=reportBaseInfo.reportno;