use ods;
drop table if exists odstmp_bpms_biz_ransom_floor_common;
CREATE TABLE if not exists ods.odstmp_bpms_biz_ransom_floor_common (
  id STRING,
  apply_no STRING COMMENT '订单编号',
  house_no STRING COMMENT '房产信息编号,关联房产信息',
  is_hold_cert STRING COMMENT '业主是否持证',
  is_already_ransom STRING COMMENT '是否已预约赎楼',
  ransom_borrow_amount DOUBLE COMMENT '赎楼借款金额',
  own_fund_amount DOUBLE COMMENT '卖方自有资金',
  ransom_cut_amount DOUBLE COMMENT '赎楼扣款金额',
  ransom_cut_time timestamp COMMENT '赎楼扣款时间',
  loan_rate STRING COMMENT '赎楼贷款利率',
  loan_terms STRING COMMENT '赎楼贷款期限(月)',
  repay_method STRING COMMENT '赎楼贷款还款方式',
  borrow_cont_no STRING COMMENT '赎楼贷款借款合同编号',
  bank_user STRING COMMENT '赎楼贷款银行联系人',
  bank_phone STRING COMMENT '赎楼贷款联系方式',
  seller_name STRING COMMENT '赎楼贷款借款人姓名',
  seller_card_no STRING COMMENT '赎楼贷款身份证号码',
  remark STRING COMMENT '备注',
  create_user_id STRING COMMENT '创建人id',
  update_user_id STRING COMMENT '更新人id',
  create_time timestamp COMMENT '记录创建时间',
  update_time timestamp COMMENT '记录更新时间',
  rev bigint comment '版本号',
  delete_flag STRING COMMENT '记录删除标识(1:删除；0:有效记录)',
  has_ransom_floor STRING COMMENT '是否有赎楼(Y/N)',
  has_qzjzxcl STRING COMMENT '是否需要取证及注销材料(Y/N)',
  qzjzxcl_phone STRING COMMENT '取注销资料电话',
  qzjzxcl_bank STRING COMMENT '取注销资料银行总行',
  qzjzxcl_bank_code STRING COMMENT '取注销资料银行总行编码',
  qzjzxcl_branch_bank STRING COMMENT '取注销资料银行分行',
  qzjzxcl_branch_bank_code STRING COMMENT '取注销资料银行分行编码',
  predict_qzjzxcl_time timestamp COMMENT '预计取注销资料时间',
  qzjzxcl_time timestamp COMMENT '取注销资料时间',
  qzjzxcl_linkman STRING COMMENT '取注销资料联系人',
  ransom_flag STRING COMMENT '赎楼状态',
  ransom_fail_reason STRING COMMENT '赎楼失败原因',
  pre_ransom_next_time timestamp COMMENT '预计下次赎楼时间',
  ransom_amount_back_flag STRING COMMENT '赎楼资金是否划回',
  ransom_amout_back DOUBLE COMMENT '赎楼划回金额',
  get_cancel_material_address STRING COMMENT '取注销（后）资料地点',
  is_company_cancel STRING COMMENT '是否由我司办理注销抵押(Y:是，N:否)',
  is_company_get_material STRING COMMENT '是否由我司领取注销抵押（后）资料',
  actual_repay_method STRING COMMENT '实际赎楼方式式',
  actual_repay_method_name STRING COMMENT '实际赎楼方式名',
  rn bigint
) STORED AS parquet;
insert overwrite table odstmp_bpms_biz_ransom_floor_common
select T.*,sys.name_ actual_repay_method_name,
ROW_NUMBER() OVER(PARTITION BY apply_no ORDER BY create_time desc) rn
from
( SELECT
a.id,
a.apply_no,
a.house_no,
a.is_hold_cert,
a.is_already_ransom,
a.ransom_borrow_amount,
a.own_fund_amount,
a.ransom_cut_amount,
a.ransom_cut_time,
a.loan_rate,
a.loan_terms,
a.repay_method,
a.borrow_cont_no,
a.bank_user,
a.bank_phone,
a.seller_name,
a.seller_card_no,
a.remark,
a.create_user_id,
a.update_user_id,
a.create_time,
a.update_time,
a.rev,
a.delete_flag,
a.has_ransom_floor,
a.has_qzjzxcl,
a.qzjzxcl_phone,
a.qzjzxcl_bank,
a.qzjzxcl_bank_code,
a.qzjzxcl_branch_bank,
a.qzjzxcl_branch_bank_code,
a.predict_qzjzxcl_time,
a.qzjzxcl_time,
a.qzjzxcl_linkman,
a.ransom_flag,
a.ransom_fail_reason,
a.pre_ransom_next_time,
a.ransom_amount_back_flag,
a.ransom_amout_back,
a.get_cancel_material_address,
a.is_company_cancel,
a.is_company_get_material,
a.actual_repay_method
  FROM
( select * from ods_bpms_biz_ransom_floor where (apply_no<>'' and apply_no is not null) and(house_no='' or house_no is null ) ) a
union all
SELECT
a1.id,
c1.apply_no,
a1.house_no,
a1.is_hold_cert,
a1.is_already_ransom,
a1.ransom_borrow_amount,
a1.own_fund_amount,
a1.ransom_cut_amount,
a1.ransom_cut_time,
a1.loan_rate,
a1.loan_terms,
a1.repay_method,
a1.borrow_cont_no,
a1.bank_user,
a1.bank_phone,
a1.seller_name,
a1.seller_card_no,
a1.remark,
a1.create_user_id,
a1.update_user_id,
a1.create_time,
a1.update_time,
a1.rev,
a1.delete_flag,
a1.has_ransom_floor,
a1.has_qzjzxcl,
a1.qzjzxcl_phone,
a1.qzjzxcl_bank,
a1.qzjzxcl_bank_code,
a1.qzjzxcl_branch_bank,
a1.qzjzxcl_branch_bank_code,
a1.predict_qzjzxcl_time,
a1.qzjzxcl_time,
a1.qzjzxcl_linkman,
a1.ransom_flag,
a1.ransom_fail_reason,
a1.pre_ransom_next_time,
a1.ransom_amount_back_flag,
a1.ransom_amout_back,
a1.get_cancel_material_address,
a1.is_company_cancel,
a1.is_company_get_material,
a1.actual_repay_method
FROM
( select * from ods_bpms_biz_ransom_floor where (apply_no<>'' and apply_no is not null) and(house_no<>'' and house_no is not null ) ) a1
LEFT JOIN ( select apply_no, house_no from ods_bpms_biz_apply_order where house_no <> '' AND house_no IS NOT NULL ) c1 ON c1.house_no = a1.house_no
union all
select
b.id,
c.apply_no apply_no,
b.house_no,
b.is_hold_cert,
b.is_already_ransom,
b.ransom_borrow_amount,
b.own_fund_amount,
b.ransom_cut_amount,
b.ransom_cut_time,
b.loan_rate,
b.loan_terms,
b.repay_method,
b.borrow_cont_no,
b.bank_user,
b.bank_phone,
b.seller_name,
b.seller_card_no,
b.remark,
b.create_user_id,
b.update_user_id,
b.create_time,
b.update_time,
b.rev,
b.delete_flag,
b.has_ransom_floor,
b.has_qzjzxcl,
b.qzjzxcl_phone,
b.qzjzxcl_bank,
b.qzjzxcl_bank_code,
b.qzjzxcl_branch_bank,
b.qzjzxcl_branch_bank_code,
b.predict_qzjzxcl_time,
b.qzjzxcl_time,
b.qzjzxcl_linkman,
b.ransom_flag,
b.ransom_fail_reason,
b.pre_ransom_next_time,
b.ransom_amount_back_flag,
b.ransom_amout_back,
b.get_cancel_material_address,
b.is_company_cancel,
b.is_company_get_material,b.actual_repay_method from ( SELECT
*
FROM
ods_bpms_biz_ransom_floor
WHERE
(house_no <> '' AND house_no IS NOT NULL ) and (apply_no ='' or apply_no is null )
) b
LEFT JOIN ( select apply_no, house_no from ods_bpms_biz_apply_order where house_no <> '' AND house_no IS NOT NULL ) c ON c.house_no = b.house_no
)T
left join (select * from ods_bpms_sys_dic_common where rn=1) sys on sys.key_=lower(actual_repay_method);
drop table if exists ods_bpms_biz_ransom_floor_common;
ALTER TABLE odstmp_bpms_biz_ransom_floor_common RENAME TO ods_bpms_biz_ransom_floor_common;