use ods;
drop table if exists  odstmp_bims_bpm_check_opinion_common_ex_wx;
CREATE TABLE if not exists odstmp_bims_bpm_check_opinion_common_ex_wx (
apply_no STRING,
approvalimage_time timestamp comment '人工初审申请时间',
approvalimage_user_id STRING comment '人工初审申请用户id',
approvalimage_user_name STRING comment '人工初审申请用户名',
approvalimage_option STRING comment '人工初审申请审批意见',
approvalimage_status_name STRING comment '人工初审申请审批状态',
quota_time timestamp comment '出额申请时间',
quota_user_id STRING comment '出额申请用户id',
quota_user_name STRING comment '出额申请用户名',
quota_option STRING comment '出额申请审批意见',
quota_status_name STRING comment '出额申请审批状态',
inputapproveinfo_time timestamp comment '初审信息录入申请时间',
inputapproveinfo_user_id STRING comment '初审信息录入申请用户id',
inputapproveinfo_user_name STRING comment '初审信息录入申请用户名',
inputapproveinfo_option STRING comment '初审信息录入申请审批意见',
inputapproveinfo_status_name STRING comment '初审信息录入申请审批状态',
queryarchive_time timestamp comment '查档申请时间',
queryarchive_user_id STRING comment '查档申请用户id',
queryarchive_user_name STRING comment '查档申请用户名',
queryarchive_option STRING comment '查档申请审批意见',
queryarchive_status_name STRING comment '查档申请审批状态',
transfermark_time timestamp comment '放款登记申请时间',
transfermark_user_id STRING comment '放款登记申请用户id',
transfermark_user_name STRING comment '放款登记申请用户名',
transfermark_option STRING comment '放款登记申请审批意见',
transfermark_status_name STRING comment '放款登记申请审批状态',
mortgageout_time timestamp comment '抵押出件申请时间',
mortgageout_user_id STRING comment '抵押出件申请用户id',
mortgageout_user_name STRING comment '抵押出件申请用户名',
mortgageout_option STRING comment '抵押出件申请审批意见',
mortgageout_status_name STRING comment '抵押出件申请审批状态',
costmark_time timestamp comment '费率登记申请时间',
costmark_user_id STRING comment '费率登记申请用户id',
costmark_user_name STRING comment '费率登记申请用户名',
costmark_option STRING comment '费率登记申请审批意见',
costmark_status_name STRING comment '费率登记申请审批状态',
householdapprove_time timestamp comment '下户审批申请时间',
householdapprove_user_id STRING comment '下户审批申请用户id',
householdapprove_user_name STRING comment '下户审批申请用户名',
householdapprove_option STRING comment '下户审批申请审批意见',
householdapprove_status_name STRING comment '下户审批申请审批状态',
confirmationloan_time timestamp comment '确认贷款意向申请时间',
confirmationloan_user_id STRING comment '确认贷款意向申请用户id',
confirmationloan_user_name STRING comment '确认贷款意向申请用户名',
confirmationloan_option STRING comment '确认贷款意向申请审批意见',
confirmationloan_status_name STRING comment '确认贷款意向申请审批状态',
insuranceinfoconfirm_time timestamp comment '保单信息确认申请时间',
insuranceinfoconfirm_user_id STRING comment '保单信息确认申请用户id',
insuranceinfoconfirm_user_name STRING comment '保单信息确认申请用户名',
insuranceinfoconfirm_option STRING comment '保单信息确认申请审批意见',
insuranceinfoconfirm_status_name STRING comment '保单信息确认申请审批状态',
householdsurvey_time timestamp comment '下户调查申请时间',
householdsurvey_user_id STRING comment '下户调查申请用户id',
householdsurvey_user_name STRING comment '下户调查申请用户名',
householdsurvey_option STRING comment '下户调查申请审批意见',
householdsurvey_status_name STRING comment '下户调查申请审批状态',
mortgagepass_time timestamp comment '抵押递件申请时间',
mortgagepass_user_id STRING comment '抵押递件申请用户id',
mortgagepass_user_name STRING comment '抵押递件申请用户名',
mortgagepass_option STRING comment '抵押递件申请审批意见',
mortgagepass_status_name STRING comment '抵押递件申请审批状态',
creditconfirm_time timestamp comment '征信确认申请时间',
creditconfirm_user_id STRING comment '征信确认申请用户id',
creditconfirm_user_name STRING comment '征信确认申请用户名',
creditconfirm_option STRING comment '征信确认申请审批意见',
creditconfirm_status_name STRING comment '征信确认申请审批状态',
costitemmark_time timestamp comment '费项登记申请时间',
costitemmark_user_id STRING comment '费项登记申请用户id',
costitemmark_user_name STRING comment '费项登记申请用户名',
costitemmark_option STRING comment '费项登记申请审批意见',
costitemmark_status_name STRING comment '费项登记申请审批状态',
patch_ds_time timestamp comment '大数补件申请时间',
patch_ds_user_id STRING comment '大数补件申请用户id',
patch_ds_user_name STRING comment '大数补件申请用户名',
patch_ds_option STRING comment '大数补件申请审批意见',
patch_ds_status_name STRING comment '大数补件申请审批状态',
sendloancommand_time timestamp comment '出账审核申请时间',
sendloancommand_user_id STRING comment '出账审核申请用户id',
sendloancommand_user_name STRING comment '出账审核申请用户名',
sendloancommand_option STRING comment '出账审核申请审批意见',
sendloancommand_status_name STRING comment '出账审核申请审批状态',
uploadimg_time timestamp comment '资料反馈申请时间',
uploadimg_user_id STRING comment '资料反馈申请用户id',
uploadimg_user_name STRING comment '资料反馈申请用户名',
uploadimg_option STRING comment '资料反馈申请审批意见',
uploadimg_status_name STRING comment '资料反馈申请审批状态',
pushoutcommand_time timestamp comment '外传指令推送申请时间',
pushoutcommand_user_id STRING comment '外传指令推送申请用户id',
pushoutcommand_user_name STRING comment '外传指令推送申请用户名',
pushoutcommand_option STRING comment '外传指令推送申请审批意见',
pushoutcommand_status_name STRING comment '外传指令推送申请审批状态',
applyorder_time timestamp comment '业务申请申请时间',
applyorder_user_id STRING comment '业务申请申请用户id',
applyorder_user_name STRING comment '业务申请申请用户名',
applyorder_option STRING comment '业务申请申请审批意见',
applyorder_status_name STRING comment '业务申请申请审批状态',
prefile_time timestamp comment '归档申请时间',
prefile_user_id STRING comment '归档申请用户id',
prefile_user_name STRING comment '归档申请用户名',
prefile_option STRING comment '归档申请审批意见',
prefile_status_name STRING comment '归档申请审批状态',
sendverifymaterial_time timestamp comment '核保资料外传申请时间',
sendverifymaterial_user_id STRING comment '核保资料外传申请用户id',
sendverifymaterial_user_name STRING comment '核保资料外传申请用户名',
sendverifymaterial_option STRING comment '核保资料外传申请审批意见',
sendverifymaterial_status_name STRING comment '核保资料外传申请审批状态',
pushloancommand_time timestamp comment '出账指令推送申请时间',
pushloancommand_user_id STRING comment '出账指令推送申请用户id',
pushloancommand_user_name STRING comment '出账指令推送申请用户名',
pushloancommand_option STRING comment '出账指令推送申请审批意见',
pushloancommand_status_name STRING comment '出账指令推送申请审批状态',
submitverifyapply_time timestamp comment '提交核保申请申请时间',
submitverifyapply_user_id STRING comment '提交核保申请申请用户id',
submitverifyapply_user_name STRING comment '提交核保申请申请用户名',
submitverifyapply_option STRING comment '提交核保申请申请审批意见',
submitverifyapply_status_name STRING comment '提交核保申请申请审批状态',
submitapproval_time timestamp comment '影像资料确认申请时间',
submitapproval_user_id STRING comment '影像资料确认申请用户id',
submitapproval_user_name STRING comment '影像资料确认申请用户名',
submitapproval_option STRING comment '影像资料确认申请审批意见',
submitapproval_status_name STRING comment '影像资料确认申请审批状态',
notarization_time timestamp comment '办理公证申请时间',
notarization_user_id STRING comment '办理公证申请用户id',
notarization_user_name STRING comment '办理公证申请用户名',
notarization_option STRING comment '办理公证申请审批意见',
notarization_status_name STRING comment '办理公证申请审批状态',
trustaccount_time timestamp comment '要件托管申请时间',
trustaccount_user_id STRING comment '要件托管申请用户id',
trustaccount_user_name STRING comment '要件托管申请用户名',
trustaccount_option STRING comment '要件托管申请审批意见',
trustaccount_status_name STRING comment '要件托管申请审批状态',
approvalresult_time timestamp comment '终审补件申请时间',
approvalresult_user_id STRING comment '终审补件申请用户id',
approvalresult_user_name STRING comment '终审补件申请用户名',
approvalresult_option STRING comment '终审补件申请审批意见',
approvalresult_status_name STRING comment '终审补件申请审批状态',
inputinfo_time timestamp comment '录入申请时间',
inputinfo_user_id STRING comment '录入申请用户id',
inputinfo_user_name STRING comment '录入申请用户名',
inputinfo_option STRING comment '录入申请审批意见',
inputinfo_status_name STRING comment '录入申请审批状态',
interview_time timestamp comment '面签申请时间',
interview_user_id STRING comment '面签申请用户id',
interview_user_name STRING comment '面签申请用户名',
interview_option STRING comment '面签申请审批意见',
interview_status_name STRING comment '面签申请审批状态',
checkmarsend_time timestamp comment '审批资料外传申请时间',
checkmarsend_user_id STRING comment '审批资料外传申请用户id',
checkmarsend_user_name STRING comment '审批资料外传申请用户名',
checkmarsend_option STRING comment '审批资料外传申请审批意见',
checkmarsend_status_name STRING comment '审批资料外传申请审批状态',
approvalimage_min timestamp comment '首次人工初审时间',
approvalimage_user_id_min STRING comment '首次人工初审用户id',
approvalimage_user_name_min STRING comment '首次人工初审用户名',
approvalimage_option_min STRING comment '首次人工初审审批意见',
approvalimage_status_name_min STRING comment '首次人工初审审批状态',
quota_min timestamp comment '首次出额时间',
quota_user_id_min STRING comment '首次出额用户id',
quota_user_name_min STRING comment '首次出额用户名',
quota_option_min STRING comment '首次出额审批意见',
quota_status_name_min STRING comment '首次出额审批状态',
inputapproveinfo_min timestamp comment '首次初审信息录入时间',
inputapproveinfo_user_id_min STRING comment '首次初审信息录入用户id',
inputapproveinfo_user_name_min STRING comment '首次初审信息录入用户名',
inputapproveinfo_option_min STRING comment '首次初审信息录入审批意见',
inputapproveinfo_status_name_min STRING comment '首次初审信息录入审批状态',
queryarchive_min timestamp comment '首次查档时间',
queryarchive_user_id_min STRING comment '首次查档用户id',
queryarchive_user_name_min STRING comment '首次查档用户名',
queryarchive_option_min STRING comment '首次查档审批意见',
queryarchive_status_name_min STRING comment '首次查档审批状态',
transfermark_min timestamp comment '首次放款登记时间',
transfermark_user_id_min STRING comment '首次放款登记用户id',
transfermark_user_name_min STRING comment '首次放款登记用户名',
transfermark_option_min STRING comment '首次放款登记审批意见',
transfermark_status_name_min STRING comment '首次放款登记审批状态',
mortgageout_min timestamp comment '首次抵押出件时间',
mortgageout_user_id_min STRING comment '首次抵押出件用户id',
mortgageout_user_name_min STRING comment '首次抵押出件用户名',
mortgageout_option_min STRING comment '首次抵押出件审批意见',
mortgageout_status_name_min STRING comment '首次抵押出件审批状态',
costmark_min timestamp comment '首次费率登记时间',
costmark_user_id_min STRING comment '首次费率登记用户id',
costmark_user_name_min STRING comment '首次费率登记用户名',
costmark_option_min STRING comment '首次费率登记审批意见',
costmark_status_name_min STRING comment '首次费率登记审批状态',
householdapprove_min timestamp comment '首次下户审批时间',
householdapprove_user_id_min STRING comment '首次下户审批用户id',
householdapprove_user_name_min STRING comment '首次下户审批用户名',
householdapprove_option_min STRING comment '首次下户审批审批意见',
householdapprove_status_name_min STRING comment '首次下户审批审批状态',
confirmationloan_min timestamp comment '首次确认贷款意向时间',
confirmationloan_user_id_min STRING comment '首次确认贷款意向用户id',
confirmationloan_user_name_min STRING comment '首次确认贷款意向用户名',
confirmationloan_option_min STRING comment '首次确认贷款意向审批意见',
confirmationloan_status_name_min STRING comment '首次确认贷款意向审批状态',
insuranceinfoconfirm_min timestamp comment '首次保单信息确认时间',
insuranceinfoconfirm_user_id_min STRING comment '首次保单信息确认用户id',
insuranceinfoconfirm_user_name_min STRING comment '首次保单信息确认用户名',
insuranceinfoconfirm_option_min STRING comment '首次保单信息确认审批意见',
insuranceinfoconfirm_status_name_min STRING comment '首次保单信息确认审批状态',
householdsurvey_min timestamp comment '首次下户调查时间',
householdsurvey_user_id_min STRING comment '首次下户调查用户id',
householdsurvey_user_name_min STRING comment '首次下户调查用户名',
householdsurvey_option_min STRING comment '首次下户调查审批意见',
householdsurvey_status_name_min STRING comment '首次下户调查审批状态',
mortgagepass_min timestamp comment '首次抵押递件时间',
mortgagepass_user_id_min STRING comment '首次抵押递件用户id',
mortgagepass_user_name_min STRING comment '首次抵押递件用户名',
mortgagepass_option_min STRING comment '首次抵押递件审批意见',
mortgagepass_status_name_min STRING comment '首次抵押递件审批状态',
creditconfirm_min timestamp comment '首次征信确认时间',
creditconfirm_user_id_min STRING comment '首次征信确认用户id',
creditconfirm_user_name_min STRING comment '首次征信确认用户名',
creditconfirm_option_min STRING comment '首次征信确认审批意见',
creditconfirm_status_name_min STRING comment '首次征信确认审批状态',
costitemmark_min timestamp comment '首次费项登记时间',
costitemmark_user_id_min STRING comment '首次费项登记用户id',
costitemmark_user_name_min STRING comment '首次费项登记用户名',
costitemmark_option_min STRING comment '首次费项登记审批意见',
costitemmark_status_name_min STRING comment '首次费项登记审批状态',
patch_ds_min timestamp comment '首次大数补件时间',
patch_ds_user_id_min STRING comment '首次大数补件用户id',
patch_ds_user_name_min STRING comment '首次大数补件用户名',
patch_ds_option_min STRING comment '首次大数补件审批意见',
patch_ds_status_name_min STRING comment '首次大数补件审批状态',
sendloancommand_min timestamp comment '首次出账审核时间',
sendloancommand_user_id_min STRING comment '首次出账审核用户id',
sendloancommand_user_name_min STRING comment '首次出账审核用户名',
sendloancommand_option_min STRING comment '首次出账审核审批意见',
sendloancommand_status_name_min STRING comment '首次出账审核审批状态',
uploadimg_min timestamp comment '首次资料反馈时间',
uploadimg_user_id_min STRING comment '首次资料反馈用户id',
uploadimg_user_name_min STRING comment '首次资料反馈用户名',
uploadimg_option_min STRING comment '首次资料反馈审批意见',
uploadimg_status_name_min STRING comment '首次资料反馈审批状态',
pushoutcommand_min timestamp comment '首次外传指令推送时间',
pushoutcommand_user_id_min STRING comment '首次外传指令推送用户id',
pushoutcommand_user_name_min STRING comment '首次外传指令推送用户名',
pushoutcommand_option_min STRING comment '首次外传指令推送审批意见',
pushoutcommand_status_name_min STRING comment '首次外传指令推送审批状态',
applyorder_min timestamp comment '首次业务申请时间',
applyorder_user_id_min STRING comment '首次业务申请用户id',
applyorder_user_name_min STRING comment '首次业务申请用户名',
applyorder_option_min STRING comment '首次业务申请审批意见',
applyorder_status_name_min STRING comment '首次业务申请审批状态',
prefile_min timestamp comment '首次归档时间',
prefile_user_id_min STRING comment '首次归档用户id',
prefile_user_name_min STRING comment '首次归档用户名',
prefile_option_min STRING comment '首次归档审批意见',
prefile_status_name_min STRING comment '首次归档审批状态',
sendverifymaterial_min timestamp comment '首次核保资料外传时间',
sendverifymaterial_user_id_min STRING comment '首次核保资料外传用户id',
sendverifymaterial_user_name_min STRING comment '首次核保资料外传用户名',
sendverifymaterial_option_min STRING comment '首次核保资料外传审批意见',
sendverifymaterial_status_name_min STRING comment '首次核保资料外传审批状态',
pushloancommand_min timestamp comment '首次出账指令推送时间',
pushloancommand_user_id_min STRING comment '首次出账指令推送用户id',
pushloancommand_user_name_min STRING comment '首次出账指令推送用户名',
pushloancommand_option_min STRING comment '首次出账指令推送审批意见',
pushloancommand_status_name_min STRING comment '首次出账指令推送审批状态',
submitverifyapply_min timestamp comment '首次提交核保申请时间',
submitverifyapply_user_id_min STRING comment '首次提交核保申请用户id',
submitverifyapply_user_name_min STRING comment '首次提交核保申请用户名',
submitverifyapply_option_min STRING comment '首次提交核保申请审批意见',
submitverifyapply_status_name_min STRING comment '首次提交核保申请审批状态',
submitapproval_min timestamp comment '首次影像资料确认时间',
submitapproval_user_id_min STRING comment '首次影像资料确认用户id',
submitapproval_user_name_min STRING comment '首次影像资料确认用户名',
submitapproval_option_min STRING comment '首次影像资料确认审批意见',
submitapproval_status_name_min STRING comment '首次影像资料确认审批状态',
notarization_min timestamp comment '首次办理公证时间',
notarization_user_id_min STRING comment '首次办理公证用户id',
notarization_user_name_min STRING comment '首次办理公证用户名',
notarization_option_min STRING comment '首次办理公证审批意见',
notarization_status_name_min STRING comment '首次办理公证审批状态',
trustaccount_min timestamp comment '首次要件托管时间',
trustaccount_user_id_min STRING comment '首次要件托管用户id',
trustaccount_user_name_min STRING comment '首次要件托管用户名',
trustaccount_option_min STRING comment '首次要件托管审批意见',
trustaccount_status_name_min STRING comment '首次要件托管审批状态',
approvalresult_min timestamp comment '首次终审补件时间',
approvalresult_user_id_min STRING comment '首次终审补件用户id',
approvalresult_user_name_min STRING comment '首次终审补件用户名',
approvalresult_option_min STRING comment '首次终审补件审批意见',
approvalresult_status_name_min STRING comment '首次终审补件审批状态',
inputinfo_min timestamp comment '首次录入时间',
inputinfo_user_id_min STRING comment '首次录入用户id',
inputinfo_user_name_min STRING comment '首次录入用户名',
inputinfo_option_min STRING comment '首次录入审批意见',
inputinfo_status_name_min STRING comment '首次录入审批状态',
interview_min timestamp comment '首次面签时间',
interview_user_id_min STRING comment '首次面签用户id',
interview_user_name_min STRING comment '首次面签用户名',
interview_option_min STRING comment '首次面签审批意见',
interview_status_name_min STRING comment '首次面签审批状态',
checkmarsend_min timestamp comment '首次审批资料外传时间',
checkmarsend_user_id_min STRING comment '首次审批资料外传用户id',
checkmarsend_user_name_min STRING comment '首次审批资料外传用户名',
checkmarsend_option_min STRING comment '首次审批资料外传审批意见',
checkmarsend_status_name_min STRING comment '首次审批资料外传审批状态'
) STORED AS parquet;
with tmp_check_opinion_common_ex as (
  select *, ROW_NUMBER() OVER(PARTITION BY apply_no,task_key_new_ ORDER BY complete_time_ desc) rn1
 from (select * from ods.ods_bims_bpm_check_opinion_common_ex where apply_no is not null
 and (`status_` is NULL or `status_`<>'manual_end') and complete_time_ is not null )t
),
tmp_check_option_common_min as (
select a.* from tmp_check_opinion_common_ex a join
(select apply_no,task_key_new_,max(rn1) max_rn from tmp_check_opinion_common_ex group by apply_no,task_key_new_) b
on b.apply_no=a.apply_no and b.max_rn=a.rn1 and b.task_key_new_=a.task_key_new_
)
insert overwrite table odstmp_bims_bpm_check_opinion_common_ex_wx
select t666.*,
t777.approvalimage_time_min,
t777.approvalimage_user_id_min,
t777.approvalimage_user_name_min,
t777.approvalimage_option_min,
t777.approvalimage_status_name_min,
t777.quota_time_min,
t777.quota_user_id_min,
t777.quota_user_name_min,
t777.quota_option_min,
t777.quota_status_name_min,
t777.inputapproveinfo_time_min,
t777.inputapproveinfo_user_id_min,
t777.inputapproveinfo_user_name_min,
t777.inputapproveinfo_option_min,
t777.inputapproveinfo_status_name_min,
t777.queryarchive_time_min,
t777.queryarchive_user_id_min,
t777.queryarchive_user_name_min,
t777.queryarchive_option_min,
t777.queryarchive_status_name_min,
t777.transfermark_time_min,
t777.transfermark_user_id_min,
t777.transfermark_user_name_min,
t777.transfermark_option_min,
t777.transfermark_status_name_min,
t777.mortgageout_time_min,
t777.mortgageout_user_id_min,
t777.mortgageout_user_name_min,
t777.mortgageout_option_min,
t777.mortgageout_status_name_min,
t777.costmark_time_min,
t777.costmark_user_id_min,
t777.costmark_user_name_min,
t777.costmark_option_min,
t777.costmark_status_name_min,
t777.householdapprove_time_min,
t777.householdapprove_user_id_min,
t777.householdapprove_user_name_min,
t777.householdapprove_option_min,
t777.householdapprove_status_name_min,
t777.confirmationloan_time_min,
t777.confirmationloan_user_id_min,
t777.confirmationloan_user_name_min,
t777.confirmationloan_option_min,
t777.confirmationloan_status_name_min,
t777.insuranceinfoconfirm_time_min,
t777.insuranceinfoconfirm_user_id_min,
t777.insuranceinfoconfirm_user_name_min,
t777.insuranceinfoconfirm_option_min,
t777.insuranceinfoconfirm_status_name_min,
t777.householdsurvey_time_min,
t777.householdsurvey_user_id_min,
t777.householdsurvey_user_name_min,
t777.householdsurvey_option_min,
t777.householdsurvey_status_name_min,
t777.mortgagepass_time_min,
t777.mortgagepass_user_id_min,
t777.mortgagepass_user_name_min,
t777.mortgagepass_option_min,
t777.mortgagepass_status_name_min,
t777.creditconfirm_time_min,
t777.creditconfirm_user_id_min,
t777.creditconfirm_user_name_min,
t777.creditconfirm_option_min,
t777.creditconfirm_status_name_min,
t777.costitemmark_time_min,
t777.costitemmark_user_id_min,
t777.costitemmark_user_name_min,
t777.costitemmark_option_min,
t777.costitemmark_status_name_min,
t777.patch_ds_time_min,
t777.patch_ds_user_id_min,
t777.patch_ds_user_name_min,
t777.patch_ds_option_min,
t777.patch_ds_status_name_min,
t777.sendloancommand_time_min,
t777.sendloancommand_user_id_min,
t777.sendloancommand_user_name_min,
t777.sendloancommand_option_min,
t777.sendloancommand_status_name_min,
t777.uploadimg_time_min,
t777.uploadimg_user_id_min,
t777.uploadimg_user_name_min,
t777.uploadimg_option_min,
t777.uploadimg_status_name_min,
t777.pushoutcommand_time_min,
t777.pushoutcommand_user_id_min,
t777.pushoutcommand_user_name_min,
t777.pushoutcommand_option_min,
t777.pushoutcommand_status_name_min,
t777.applyorder_time_min,
t777.applyorder_user_id_min,
t777.applyorder_user_name_min,
t777.applyorder_option_min,
t777.applyorder_status_name_min,
t777.prefile_time_min,
t777.prefile_user_id_min,
t777.prefile_user_name_min,
t777.prefile_option_min,
t777.prefile_status_name_min,
t777.sendverifymaterial_time_min,
t777.sendverifymaterial_user_id_min,
t777.sendverifymaterial_user_name_min,
t777.sendverifymaterial_option_min,
t777.sendverifymaterial_status_name_min,
t777.pushloancommand_time_min,
t777.pushloancommand_user_id_min,
t777.pushloancommand_user_name_min,
t777.pushloancommand_option_min,
t777.pushloancommand_status_name_min,
t777.submitverifyapply_time_min,
t777.submitverifyapply_user_id_min,
t777.submitverifyapply_user_name_min,
t777.submitverifyapply_option_min,
t777.submitverifyapply_status_name_min,
t777.submitapproval_time_min,
t777.submitapproval_user_id_min,
t777.submitapproval_user_name_min,
t777.submitapproval_option_min,
t777.submitapproval_status_name_min,
t777.notarization_time_min,
t777.notarization_user_id_min,
t777.notarization_user_name_min,
t777.notarization_option_min,
t777.notarization_status_name_min,
t777.trustaccount_time_min,
t777.trustaccount_user_id_min,
t777.trustaccount_user_name_min,
t777.trustaccount_option_min,
t777.trustaccount_status_name_min,
t777.approvalresult_time_min,
t777.approvalresult_user_id_min,
t777.approvalresult_user_name_min,
t777.approvalresult_option_min,
t777.approvalresult_status_name_min,
t777.inputinfo_time_min,
t777.inputinfo_user_id_min,
t777.inputinfo_user_name_min,
t777.inputinfo_option_min,
t777.inputinfo_status_name_min,
t777.interview_time_min,
t777.interview_user_id_min,
t777.interview_user_name_min,
t777.interview_option_min,
t777.interview_status_name_min,
t777.checkmarsend_time_min,
t777.checkmarsend_user_id_min,
t777.checkmarsend_user_name_min,
t777.checkmarsend_option_min,
t777.checkmarsend_status_name_min
from (
select apply_no,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalimage' THEN t666.complete_time_ ELSE NULL END)) approvalimage_time,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalimage' THEN t666.auditor_ ELSE NULL END)) approvalimage_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalimage' THEN t666.auditor_name_ ELSE NULL END)) approvalimage_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalimage' THEN t666.opinion_ ELSE NULL END))  approvalimage_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalimage' THEN t666.status_name_ ELSE NULL END))   approvalimage_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='quota' THEN t666.complete_time_ ELSE NULL END)) quota_time,
MAX((CASE WHEN lower(t666.task_key_new_)='quota' THEN t666.auditor_ ELSE NULL END)) quota_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='quota' THEN t666.auditor_name_ ELSE NULL END)) quota_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='quota' THEN t666.opinion_ ELSE NULL END))  quota_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='quota' THEN t666.status_name_ ELSE NULL END))   quota_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='inputapproveinfo' THEN t666.complete_time_ ELSE NULL END)) inputapproveinfo_time,
MAX((CASE WHEN lower(t666.task_key_new_)='inputapproveinfo' THEN t666.auditor_ ELSE NULL END)) inputapproveinfo_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='inputapproveinfo' THEN t666.auditor_name_ ELSE NULL END)) inputapproveinfo_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='inputapproveinfo' THEN t666.opinion_ ELSE NULL END))  inputapproveinfo_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='inputapproveinfo' THEN t666.status_name_ ELSE NULL END))   inputapproveinfo_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.complete_time_ ELSE NULL END)) queryarchive_time,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.auditor_ ELSE NULL END)) queryarchive_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.auditor_name_ ELSE NULL END)) queryarchive_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.opinion_ ELSE NULL END))  queryarchive_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.status_name_ ELSE NULL END))   queryarchive_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.complete_time_ ELSE NULL END)) transfermark_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.auditor_ ELSE NULL END)) transfermark_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.auditor_name_ ELSE NULL END)) transfermark_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.opinion_ ELSE NULL END))  transfermark_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.status_name_ ELSE NULL END))   transfermark_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.complete_time_ ELSE NULL END)) mortgageout_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.auditor_ ELSE NULL END)) mortgageout_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.auditor_name_ ELSE NULL END)) mortgageout_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.opinion_ ELSE NULL END))  mortgageout_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.status_name_ ELSE NULL END))   mortgageout_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.complete_time_ ELSE NULL END)) costmark_time,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.auditor_ ELSE NULL END)) costmark_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.auditor_name_ ELSE NULL END)) costmark_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.opinion_ ELSE NULL END))  costmark_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.status_name_ ELSE NULL END))   costmark_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.complete_time_ ELSE NULL END)) householdapprove_time,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.auditor_ ELSE NULL END)) householdapprove_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.auditor_name_ ELSE NULL END)) householdapprove_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.opinion_ ELSE NULL END))  householdapprove_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.status_name_ ELSE NULL END))   householdapprove_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmationloan' THEN t666.complete_time_ ELSE NULL END)) confirmationloan_time,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmationloan' THEN t666.auditor_ ELSE NULL END)) confirmationloan_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmationloan' THEN t666.auditor_name_ ELSE NULL END)) confirmationloan_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmationloan' THEN t666.opinion_ ELSE NULL END))  confirmationloan_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmationloan' THEN t666.status_name_ ELSE NULL END))   confirmationloan_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.complete_time_ ELSE NULL END)) insuranceinfoconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.auditor_ ELSE NULL END)) insuranceinfoconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.auditor_name_ ELSE NULL END)) insuranceinfoconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.opinion_ ELSE NULL END))  insuranceinfoconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.status_name_ ELSE NULL END))   insuranceinfoconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.complete_time_ ELSE NULL END)) householdsurvey_time,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.auditor_ ELSE NULL END)) householdsurvey_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.auditor_name_ ELSE NULL END)) householdsurvey_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.opinion_ ELSE NULL END))  householdsurvey_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.status_name_ ELSE NULL END))   householdsurvey_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.complete_time_ ELSE NULL END)) mortgagepass_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.auditor_ ELSE NULL END)) mortgagepass_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.auditor_name_ ELSE NULL END)) mortgagepass_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.opinion_ ELSE NULL END))  mortgagepass_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.status_name_ ELSE NULL END))   mortgagepass_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.complete_time_ ELSE NULL END)) creditconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.auditor_ ELSE NULL END)) creditconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.auditor_name_ ELSE NULL END)) creditconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.opinion_ ELSE NULL END))  creditconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.status_name_ ELSE NULL END))   creditconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.complete_time_ ELSE NULL END)) costitemmark_time,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.auditor_ ELSE NULL END)) costitemmark_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.auditor_name_ ELSE NULL END)) costitemmark_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.opinion_ ELSE NULL END))  costitemmark_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.status_name_ ELSE NULL END))   costitemmark_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.complete_time_ ELSE NULL END)) patch_ds_time,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.auditor_ ELSE NULL END)) patch_ds_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.auditor_name_ ELSE NULL END)) patch_ds_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.opinion_ ELSE NULL END))  patch_ds_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.status_name_ ELSE NULL END))   patch_ds_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.complete_time_ ELSE NULL END)) sendloancommand_time,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.auditor_ ELSE NULL END)) sendloancommand_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.auditor_name_ ELSE NULL END)) sendloancommand_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.opinion_ ELSE NULL END))  sendloancommand_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.status_name_ ELSE NULL END))   sendloancommand_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.complete_time_ ELSE NULL END)) uploadimg_time,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.auditor_ ELSE NULL END)) uploadimg_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.auditor_name_ ELSE NULL END)) uploadimg_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.opinion_ ELSE NULL END))  uploadimg_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.status_name_ ELSE NULL END))   uploadimg_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.complete_time_ ELSE NULL END)) pushoutcommand_time,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.auditor_ ELSE NULL END)) pushoutcommand_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.auditor_name_ ELSE NULL END)) pushoutcommand_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.opinion_ ELSE NULL END))  pushoutcommand_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.status_name_ ELSE NULL END))   pushoutcommand_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.complete_time_ ELSE NULL END)) applyorder_time,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.auditor_ ELSE NULL END)) applyorder_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.auditor_name_ ELSE NULL END)) applyorder_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.opinion_ ELSE NULL END))  applyorder_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.status_name_ ELSE NULL END))   applyorder_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.complete_time_ ELSE NULL END)) prefile_time,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.auditor_ ELSE NULL END)) prefile_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.auditor_name_ ELSE NULL END)) prefile_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.opinion_ ELSE NULL END))  prefile_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.status_name_ ELSE NULL END))   prefile_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.complete_time_ ELSE NULL END)) sendverifymaterial_time,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.auditor_ ELSE NULL END)) sendverifymaterial_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.auditor_name_ ELSE NULL END)) sendverifymaterial_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.opinion_ ELSE NULL END))  sendverifymaterial_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.status_name_ ELSE NULL END))   sendverifymaterial_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.complete_time_ ELSE NULL END)) pushloancommand_time,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.auditor_ ELSE NULL END)) pushloancommand_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.auditor_name_ ELSE NULL END)) pushloancommand_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.opinion_ ELSE NULL END))  pushloancommand_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.status_name_ ELSE NULL END))   pushloancommand_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.complete_time_ ELSE NULL END)) submitverifyapply_time,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.auditor_ ELSE NULL END)) submitverifyapply_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.auditor_name_ ELSE NULL END)) submitverifyapply_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.opinion_ ELSE NULL END))  submitverifyapply_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.status_name_ ELSE NULL END))   submitverifyapply_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='submitapproval' THEN t666.complete_time_ ELSE NULL END)) submitapproval_time,
MAX((CASE WHEN lower(t666.task_key_new_)='submitapproval' THEN t666.auditor_ ELSE NULL END)) submitapproval_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='submitapproval' THEN t666.auditor_name_ ELSE NULL END)) submitapproval_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='submitapproval' THEN t666.opinion_ ELSE NULL END))  submitapproval_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='submitapproval' THEN t666.status_name_ ELSE NULL END))   submitapproval_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.complete_time_ ELSE NULL END)) notarization_time,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.auditor_ ELSE NULL END)) notarization_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.auditor_name_ ELSE NULL END)) notarization_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.opinion_ ELSE NULL END))  notarization_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.status_name_ ELSE NULL END))   notarization_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.complete_time_ ELSE NULL END)) trustaccount_time,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.auditor_ ELSE NULL END)) trustaccount_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.auditor_name_ ELSE NULL END)) trustaccount_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.opinion_ ELSE NULL END))  trustaccount_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.status_name_ ELSE NULL END))   trustaccount_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.complete_time_ ELSE NULL END)) approvalresult_time,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.auditor_ ELSE NULL END)) approvalresult_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.auditor_name_ ELSE NULL END)) approvalresult_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.opinion_ ELSE NULL END))  approvalresult_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.status_name_ ELSE NULL END))   approvalresult_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.complete_time_ ELSE NULL END)) inputinfo_time,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.auditor_ ELSE NULL END)) inputinfo_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.auditor_name_ ELSE NULL END)) inputinfo_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.opinion_ ELSE NULL END))  inputinfo_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.status_name_ ELSE NULL END))   inputinfo_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.complete_time_ ELSE NULL END)) interview_time,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.auditor_ ELSE NULL END)) interview_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.auditor_name_ ELSE NULL END)) interview_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.opinion_ ELSE NULL END))  interview_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.status_name_ ELSE NULL END))   interview_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.complete_time_ ELSE NULL END)) checkmarsend_time,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.auditor_ ELSE NULL END)) checkmarsend_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.auditor_name_ ELSE NULL END)) checkmarsend_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.opinion_ ELSE NULL END))  checkmarsend_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.status_name_ ELSE NULL END))   checkmarsend_status_name_
from (select * from tmp_check_opinion_common_ex where rn1=1) t666 group by t666.apply_no) t666
join (select apply_no,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalimage' THEN t777.complete_time_ ELSE NULL END)) approvalimage_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalimage' THEN t777.auditor_ ELSE NULL END)) approvalimage_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalimage' THEN t777.auditor_name_ ELSE NULL END)) approvalimage_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalimage' THEN t777.opinion_ ELSE NULL END))  approvalimage_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalimage' THEN t777.status_name_ ELSE NULL END))   approvalimage_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='quota' THEN t777.complete_time_ ELSE NULL END)) quota_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='quota' THEN t777.auditor_ ELSE NULL END)) quota_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='quota' THEN t777.auditor_name_ ELSE NULL END)) quota_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='quota' THEN t777.opinion_ ELSE NULL END))  quota_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='quota' THEN t777.status_name_ ELSE NULL END))   quota_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputapproveinfo' THEN t777.complete_time_ ELSE NULL END)) inputapproveinfo_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputapproveinfo' THEN t777.auditor_ ELSE NULL END)) inputapproveinfo_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputapproveinfo' THEN t777.auditor_name_ ELSE NULL END)) inputapproveinfo_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputapproveinfo' THEN t777.opinion_ ELSE NULL END))  inputapproveinfo_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputapproveinfo' THEN t777.status_name_ ELSE NULL END))   inputapproveinfo_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='queryarchive' THEN t777.complete_time_ ELSE NULL END)) queryarchive_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='queryarchive' THEN t777.auditor_ ELSE NULL END)) queryarchive_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='queryarchive' THEN t777.auditor_name_ ELSE NULL END)) queryarchive_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='queryarchive' THEN t777.opinion_ ELSE NULL END))  queryarchive_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='queryarchive' THEN t777.status_name_ ELSE NULL END))   queryarchive_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='transfermark' THEN t777.complete_time_ ELSE NULL END)) transfermark_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='transfermark' THEN t777.auditor_ ELSE NULL END)) transfermark_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='transfermark' THEN t777.auditor_name_ ELSE NULL END)) transfermark_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='transfermark' THEN t777.opinion_ ELSE NULL END))  transfermark_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='transfermark' THEN t777.status_name_ ELSE NULL END))   transfermark_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgageout' THEN t777.complete_time_ ELSE NULL END)) mortgageout_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgageout' THEN t777.auditor_ ELSE NULL END)) mortgageout_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgageout' THEN t777.auditor_name_ ELSE NULL END)) mortgageout_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgageout' THEN t777.opinion_ ELSE NULL END))  mortgageout_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgageout' THEN t777.status_name_ ELSE NULL END))   mortgageout_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costmark' THEN t777.complete_time_ ELSE NULL END)) costmark_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costmark' THEN t777.auditor_ ELSE NULL END)) costmark_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costmark' THEN t777.auditor_name_ ELSE NULL END)) costmark_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costmark' THEN t777.opinion_ ELSE NULL END))  costmark_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costmark' THEN t777.status_name_ ELSE NULL END))   costmark_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdapprove' THEN t777.complete_time_ ELSE NULL END)) householdapprove_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdapprove' THEN t777.auditor_ ELSE NULL END)) householdapprove_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdapprove' THEN t777.auditor_name_ ELSE NULL END)) householdapprove_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdapprove' THEN t777.opinion_ ELSE NULL END))  householdapprove_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdapprove' THEN t777.status_name_ ELSE NULL END))   householdapprove_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='confirmationloan' THEN t777.complete_time_ ELSE NULL END)) confirmationloan_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='confirmationloan' THEN t777.auditor_ ELSE NULL END)) confirmationloan_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='confirmationloan' THEN t777.auditor_name_ ELSE NULL END)) confirmationloan_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='confirmationloan' THEN t777.opinion_ ELSE NULL END))  confirmationloan_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='confirmationloan' THEN t777.status_name_ ELSE NULL END))   confirmationloan_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='insuranceinfoconfirm' THEN t777.complete_time_ ELSE NULL END)) insuranceinfoconfirm_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='insuranceinfoconfirm' THEN t777.auditor_ ELSE NULL END)) insuranceinfoconfirm_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='insuranceinfoconfirm' THEN t777.auditor_name_ ELSE NULL END)) insuranceinfoconfirm_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='insuranceinfoconfirm' THEN t777.opinion_ ELSE NULL END))  insuranceinfoconfirm_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='insuranceinfoconfirm' THEN t777.status_name_ ELSE NULL END))   insuranceinfoconfirm_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdsurvey' THEN t777.complete_time_ ELSE NULL END)) householdsurvey_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdsurvey' THEN t777.auditor_ ELSE NULL END)) householdsurvey_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdsurvey' THEN t777.auditor_name_ ELSE NULL END)) householdsurvey_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdsurvey' THEN t777.opinion_ ELSE NULL END))  householdsurvey_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='householdsurvey' THEN t777.status_name_ ELSE NULL END))   householdsurvey_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgagepass' THEN t777.complete_time_ ELSE NULL END)) mortgagepass_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgagepass' THEN t777.auditor_ ELSE NULL END)) mortgagepass_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgagepass' THEN t777.auditor_name_ ELSE NULL END)) mortgagepass_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgagepass' THEN t777.opinion_ ELSE NULL END))  mortgagepass_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='mortgagepass' THEN t777.status_name_ ELSE NULL END))   mortgagepass_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='creditconfirm' THEN t777.complete_time_ ELSE NULL END)) creditconfirm_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='creditconfirm' THEN t777.auditor_ ELSE NULL END)) creditconfirm_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='creditconfirm' THEN t777.auditor_name_ ELSE NULL END)) creditconfirm_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='creditconfirm' THEN t777.opinion_ ELSE NULL END))  creditconfirm_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='creditconfirm' THEN t777.status_name_ ELSE NULL END))   creditconfirm_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costitemmark' THEN t777.complete_time_ ELSE NULL END)) costitemmark_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costitemmark' THEN t777.auditor_ ELSE NULL END)) costitemmark_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costitemmark' THEN t777.auditor_name_ ELSE NULL END)) costitemmark_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costitemmark' THEN t777.opinion_ ELSE NULL END))  costitemmark_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='costitemmark' THEN t777.status_name_ ELSE NULL END))   costitemmark_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='patch_ds' THEN t777.complete_time_ ELSE NULL END)) patch_ds_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='patch_ds' THEN t777.auditor_ ELSE NULL END)) patch_ds_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='patch_ds' THEN t777.auditor_name_ ELSE NULL END)) patch_ds_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='patch_ds' THEN t777.opinion_ ELSE NULL END))  patch_ds_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='patch_ds' THEN t777.status_name_ ELSE NULL END))   patch_ds_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendloancommand' THEN t777.complete_time_ ELSE NULL END)) sendloancommand_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendloancommand' THEN t777.auditor_ ELSE NULL END)) sendloancommand_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendloancommand' THEN t777.auditor_name_ ELSE NULL END)) sendloancommand_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendloancommand' THEN t777.opinion_ ELSE NULL END))  sendloancommand_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendloancommand' THEN t777.status_name_ ELSE NULL END))   sendloancommand_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='uploadimg' THEN t777.complete_time_ ELSE NULL END)) uploadimg_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='uploadimg' THEN t777.auditor_ ELSE NULL END)) uploadimg_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='uploadimg' THEN t777.auditor_name_ ELSE NULL END)) uploadimg_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='uploadimg' THEN t777.opinion_ ELSE NULL END))  uploadimg_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='uploadimg' THEN t777.status_name_ ELSE NULL END))   uploadimg_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushoutcommand' THEN t777.complete_time_ ELSE NULL END)) pushoutcommand_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushoutcommand' THEN t777.auditor_ ELSE NULL END)) pushoutcommand_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushoutcommand' THEN t777.auditor_name_ ELSE NULL END)) pushoutcommand_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushoutcommand' THEN t777.opinion_ ELSE NULL END))  pushoutcommand_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushoutcommand' THEN t777.status_name_ ELSE NULL END))   pushoutcommand_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='applyorder' THEN t777.complete_time_ ELSE NULL END)) applyorder_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='applyorder' THEN t777.auditor_ ELSE NULL END)) applyorder_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='applyorder' THEN t777.auditor_name_ ELSE NULL END)) applyorder_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='applyorder' THEN t777.opinion_ ELSE NULL END))  applyorder_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='applyorder' THEN t777.status_name_ ELSE NULL END))   applyorder_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='prefile' THEN t777.complete_time_ ELSE NULL END)) prefile_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='prefile' THEN t777.auditor_ ELSE NULL END)) prefile_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='prefile' THEN t777.auditor_name_ ELSE NULL END)) prefile_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='prefile' THEN t777.opinion_ ELSE NULL END))  prefile_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='prefile' THEN t777.status_name_ ELSE NULL END))   prefile_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendverifymaterial' THEN t777.complete_time_ ELSE NULL END)) sendverifymaterial_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendverifymaterial' THEN t777.auditor_ ELSE NULL END)) sendverifymaterial_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendverifymaterial' THEN t777.auditor_name_ ELSE NULL END)) sendverifymaterial_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendverifymaterial' THEN t777.opinion_ ELSE NULL END))  sendverifymaterial_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='sendverifymaterial' THEN t777.status_name_ ELSE NULL END))   sendverifymaterial_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushloancommand' THEN t777.complete_time_ ELSE NULL END)) pushloancommand_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushloancommand' THEN t777.auditor_ ELSE NULL END)) pushloancommand_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushloancommand' THEN t777.auditor_name_ ELSE NULL END)) pushloancommand_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushloancommand' THEN t777.opinion_ ELSE NULL END))  pushloancommand_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='pushloancommand' THEN t777.status_name_ ELSE NULL END))   pushloancommand_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitverifyapply' THEN t777.complete_time_ ELSE NULL END)) submitverifyapply_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitverifyapply' THEN t777.auditor_ ELSE NULL END)) submitverifyapply_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitverifyapply' THEN t777.auditor_name_ ELSE NULL END)) submitverifyapply_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitverifyapply' THEN t777.opinion_ ELSE NULL END))  submitverifyapply_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitverifyapply' THEN t777.status_name_ ELSE NULL END))   submitverifyapply_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitapproval' THEN t777.complete_time_ ELSE NULL END)) submitapproval_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitapproval' THEN t777.auditor_ ELSE NULL END)) submitapproval_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitapproval' THEN t777.auditor_name_ ELSE NULL END)) submitapproval_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitapproval' THEN t777.opinion_ ELSE NULL END))  submitapproval_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='submitapproval' THEN t777.status_name_ ELSE NULL END))   submitapproval_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='notarization' THEN t777.complete_time_ ELSE NULL END)) notarization_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='notarization' THEN t777.auditor_ ELSE NULL END)) notarization_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='notarization' THEN t777.auditor_name_ ELSE NULL END)) notarization_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='notarization' THEN t777.opinion_ ELSE NULL END))  notarization_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='notarization' THEN t777.status_name_ ELSE NULL END))   notarization_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='trustaccount' THEN t777.complete_time_ ELSE NULL END)) trustaccount_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='trustaccount' THEN t777.auditor_ ELSE NULL END)) trustaccount_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='trustaccount' THEN t777.auditor_name_ ELSE NULL END)) trustaccount_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='trustaccount' THEN t777.opinion_ ELSE NULL END))  trustaccount_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='trustaccount' THEN t777.status_name_ ELSE NULL END))   trustaccount_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalresult' THEN t777.complete_time_ ELSE NULL END)) approvalresult_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalresult' THEN t777.auditor_ ELSE NULL END)) approvalresult_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalresult' THEN t777.auditor_name_ ELSE NULL END)) approvalresult_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalresult' THEN t777.opinion_ ELSE NULL END))  approvalresult_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='approvalresult' THEN t777.status_name_ ELSE NULL END))   approvalresult_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputinfo' THEN t777.complete_time_ ELSE NULL END)) inputinfo_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputinfo' THEN t777.auditor_ ELSE NULL END)) inputinfo_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputinfo' THEN t777.auditor_name_ ELSE NULL END)) inputinfo_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputinfo' THEN t777.opinion_ ELSE NULL END))  inputinfo_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='inputinfo' THEN t777.status_name_ ELSE NULL END))   inputinfo_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='interview' THEN t777.complete_time_ ELSE NULL END)) interview_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='interview' THEN t777.auditor_ ELSE NULL END)) interview_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='interview' THEN t777.auditor_name_ ELSE NULL END)) interview_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='interview' THEN t777.opinion_ ELSE NULL END))  interview_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='interview' THEN t777.status_name_ ELSE NULL END))   interview_status_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='checkmarsend' THEN t777.complete_time_ ELSE NULL END)) checkmarsend_time_min,
MIN((CASE WHEN lower(t777.task_key_new_)='checkmarsend' THEN t777.auditor_ ELSE NULL END)) checkmarsend_user_id_min,
MIN((CASE WHEN lower(t777.task_key_new_)='checkmarsend' THEN t777.auditor_name_ ELSE NULL END)) checkmarsend_user_name_min,
MIN((CASE WHEN lower(t777.task_key_new_)='checkmarsend' THEN t777.opinion_ ELSE NULL END))  checkmarsend_option_min,
MIN((CASE WHEN lower(t777.task_key_new_)='checkmarsend' THEN t777.status_name_ ELSE NULL END))   checkmarsend_status_name_min
from tmp_check_option_common_min t777 group by t777.apply_no )t777 on t777.apply_no=t666.apply_no;
drop table if exists ods_bims_bpm_check_opinion_common_ex_wx;
ALTER TABLE odstmp_bims_bpm_check_opinion_common_ex_wx RENAME TO ods_bims_bpm_check_opinion_common_ex_wx;