use ods;
drop table if  exists ods.odstmp_bpms_biz_ori_loan_common;
CREATE TABLE if not exists ods.odstmp_bpms_biz_ori_loan_common (
  id STRING COMMENT '主键id',
  apply_no STRING COMMENT '订单编号',
  house_no STRING COMMENT '房产信息编号,关联房产信息',
  is_loan_flag STRING COMMENT '有无原贷款信息标识  有：Y  没：N ',
  ori_loan_bank_name STRING COMMENT '原贷款银行名称',
  ori_loan_bank_code STRING COMMENT '原贷款银行编号',
  repay_method STRING COMMENT '还款扣款方式 预存自动扣款：AUT  柜台办理即时扣款：DSK ，柜台办理系统批量扣款：BAT',
  busi_deduct_principal_balance DOUBLE COMMENT '商贷本金余额（元）',
  pre_fine_amount DOUBLE COMMENT '预计罚息（元）',
  deduct_date_interval STRING COMMENT '扣款时间段',
  ori_bank_user STRING COMMENT '银行联系人',
  ori_bank_phone STRING COMMENT '联系方式',
  glk_bank_name STRING COMMENT '供楼卡开户行名称',
  glk_bank_code STRING COMMENT '供楼卡开户行编号',
  glk_account_user_name STRING COMMENT '供楼卡户名',
  glk_account_user_no STRING COMMENT '供楼卡户主编号',
  glk_account_no STRING COMMENT '供楼卡卡号',
  fund_loan_flag STRING COMMENT '是否有公积金贷款标识  有：Y  没：N ',
  fund_deduct_balance DOUBLE COMMENT '公积金贷款本金余额（元）',
  fund_repay_user STRING COMMENT '公积金还款联系人',
  fund_repay_user_phone STRING COMMENT '公积金还款联系人联系电话',
  pre_ransom_date timestamp COMMENT '预计赎楼时间',
  remark STRING COMMENT '备注',
  first_mortgage_amount DOUBLE COMMENT '一押本金余额（元）',
  has_second_mortgage STRING COMMENT '是否为二押（Y:是,N:否）',
  create_user_id STRING COMMENT '创建人id',
  update_user_id STRING COMMENT '更新人id',
  create_time timestamp COMMENT '记录创建时间',
  update_time timestamp COMMENT '记录更新时间',
  rev bigint comment '版本号',
  delete_flag STRING COMMENT '记录删除标识(1：删除；0：有效记录)',
  is_prestore STRING COMMENT '是否预存',
  prestore_day STRING COMMENT '预存天数',
  ransom_repayment_start_date TIMESTAMP COMMENT '赎楼还款开始日期',
  ransom_repayment_end_date TIMESTAMP COMMENT '赎楼还款结束日期',
  is_relation_loan STRING COMMENT '是否有关联贷款  Y是，N否',
  loan_balance_total DOUBLE COMMENT '贷款余额合计（元）   商贷余额+公积金贷款余额+关联贷款余额  ',
  relation_loan_balance DOUBLE COMMENT '关联贷款余额（元）',
  pre_provident_fund_loan_amount DOUBLE COMMENT '预计公积金贷款金额',
  amount_regulation_code STRING COMMENT '资金监管协议编号',
  borrower_type STRING COMMENT '原贷款借款人类型(个人 公司)',
  ori_loan_payee STRING COMMENT '原贷款借款人',
  other_non_bank STRING COMMENT '其他非银机构',
  repay_method_name STRING,
  rn bigint
) STORED AS parquet;
insert overwrite table odstmp_bpms_biz_ori_loan_common
select T.*,
ROW_NUMBER() OVER(PARTITION BY apply_no ORDER BY create_time asc) rn
from
( SELECT
a.id,
a.apply_no,
a.house_no,
a.is_loan_flag,
a.ori_loan_bank_name,
a.ori_loan_bank_code,
a.repay_method,
a.busi_deduct_principal_balance,
a.pre_fine_amount,
a.deduct_date_interval,
a.ori_bank_user,
a.ori_bank_phone,
a.glk_bank_name,
a.glk_bank_code,
a.glk_account_user_name,
a.glk_account_user_no,
a.glk_account_no,
a.fund_loan_flag,
a.fund_deduct_balance,
a.fund_repay_user,
a.fund_repay_user_phone,
a.pre_ransom_date,
a.remark,
a.first_mortgage_amount,
a.has_second_mortgage,
a.create_user_id,
a.update_user_id,
a.create_time,
a.update_time,
a.rev,
a.delete_flag,
a.is_prestore,
a.prestore_day,
a.ransom_repayment_start_date,
a.ransom_repayment_end_date,
a.is_relation_loan,
a.loan_balance_total,
a.relation_loan_balance,
a.pre_provident_fund_loan_amount,
a.amount_regulation_code,
a.borrower_type,
a.ori_loan_payee,
a.other_non_bank,
regexp_replace(regexp_replace(regexp_replace(lower(a.repay_method),'^aut$','预存自动扣款'),'^bat$','柜台办理系统批量扣款'),'^dsk$','柜台办理即时扣款')
FROM
( select * from ods_bpms_biz_ori_loan where apply_no<>'' and apply_no is not null ) a
union all
SELECT
a1.id,
c1.apply_no,
a1.house_no,
a1.is_loan_flag,
a1.ori_loan_bank_name,
a1.ori_loan_bank_code,
a1.repay_method,
a1.busi_deduct_principal_balance,
a1.pre_fine_amount,
a1.deduct_date_interval,
a1.ori_bank_user,
a1.ori_bank_phone,
a1.glk_bank_name,
a1.glk_bank_code,
a1.glk_account_user_name,
a1.glk_account_user_no,
a1.glk_account_no,
a1.fund_loan_flag,
a1.fund_deduct_balance,
a1.fund_repay_user,
a1.fund_repay_user_phone,
a1.pre_ransom_date,
a1.remark,
a1.first_mortgage_amount,
a1.has_second_mortgage,
a1.create_user_id,
a1.update_user_id,
a1.create_time,
a1.update_time,
a1.rev,
a1.delete_flag,
a1.is_prestore,
a1.prestore_day,
a1.ransom_repayment_start_date,
a1.ransom_repayment_end_date,
a1.is_relation_loan,
a1.loan_balance_total,
a1.relation_loan_balance,
a1.pre_provident_fund_loan_amount,
a1.amount_regulation_code,
a1.borrower_type,
a1.ori_loan_payee,
a1.other_non_bank,
regexp_replace(regexp_replace(regexp_replace(lower(a1.repay_method),'^aut$','预存自动扣款'),'^bat$','柜台办理系统批量扣款'),'^dsk$','柜台办理即时扣款')
FROM
( select * from ods_bpms_biz_ori_loan where (apply_no<>'' and apply_no is not null) and(house_no<>'' and house_no is not null ) ) a1
LEFT JOIN ( select apply_no, house_no from ods_bpms_biz_apply_order where house_no <> '' AND house_no IS NOT NULL ) c1 ON c1.house_no = a1.house_no
union all
select
b.id,
c.apply_no apply_no,
b.house_no,
b.is_loan_flag,
b.ori_loan_bank_name,
b.ori_loan_bank_code,
b.repay_method,
b.busi_deduct_principal_balance,
b.pre_fine_amount,
b.deduct_date_interval,
b.ori_bank_user,
b.ori_bank_phone,
b.glk_bank_name,
b.glk_bank_code,
b.glk_account_user_name,
b.glk_account_user_no,
b.glk_account_no,
b.fund_loan_flag,
b.fund_deduct_balance,
b.fund_repay_user,
b.fund_repay_user_phone,
b.pre_ransom_date,
b.remark,
b.first_mortgage_amount,
b.has_second_mortgage,
b.create_user_id,
b.update_user_id,
b.create_time,
b.update_time,
b.rev,
b.delete_flag,
b.is_prestore,
b.prestore_day,
b.ransom_repayment_start_date,
b.ransom_repayment_end_date,
b.is_relation_loan,
b.loan_balance_total,
b.relation_loan_balance,
b.pre_provident_fund_loan_amount,
b.amount_regulation_code,
b.borrower_type,
b.ori_loan_payee,
b.other_non_bank,
regexp_replace(regexp_replace(regexp_replace(lower(b.repay_method),'^aut$','预存自动扣款'),'^bat$','柜台办理系统批量扣款'),'^dsk$','柜台办理即时扣款')
from ( SELECT
*
FROM
ods_bpms_biz_ori_loan
WHERE
(house_no <> '' AND house_no IS NOT NULL ) and (apply_no ='' or apply_no is null )
) b
LEFT JOIN ( select apply_no, house_no from ods_bpms_biz_apply_order where house_no <> '' AND house_no IS NOT NULL ) c ON c.house_no = b.house_no
)T;
drop table if exists ods_bpms_biz_ori_loan_common;
ALTER TABLE odstmp_bpms_biz_ori_loan_common RENAME TO ods_bpms_biz_ori_loan_common;