use ods;
drop table if exists  odstmp_bpms_bpms_bpm_check_opinion_flow_wx;
CREATE TABLE if not exists odstmp_bpms_bpms_bpm_check_opinion_flow_wx (
proc_inst_id_ STRING,
transferapply_time timestamp comment '资金划拨申请时间',
transferapply_user_id STRING comment '资金划拨申请用户id',
transferapply_user_name STRING comment '资金划拨申请用户名',
transferapply_option STRING comment '资金划拨申请审批意见',
transferapply_status_name STRING comment '资金划拨申请审批状态',
transferconfirm_time timestamp comment '资金划拨确认时间',
transferconfirm_user_id STRING comment '资金划拨确认用户id',
transferconfirm_user_name STRING comment '资金划拨确认用户名',
transferconfirm_option STRING comment '资金划拨确认审批意见',
transferconfirm_status_name STRING comment '资金划拨确认审批状态',
returnapply_time timestamp comment '资金归还申请时间',
returnapply_user_id STRING comment '资金归还申请用户id',
returnapply_user_name STRING comment '资金归还申请用户名',
returnapply_option STRING comment '资金归还申请审批意见',
returnapply_status_name STRING comment '资金归还申请审批状态',
accounttest_time timestamp comment '账户测试时间',
accounttest_user_id STRING comment '账户测试用户id',
accounttest_user_name STRING comment '账户测试用户名',
accounttest_option STRING comment '账户测试审批意见',
accounttest_status_name STRING comment '账户测试审批状态',
agreeloanmark_time timestamp comment '同贷信息登记/同贷登记时间',
agreeloanmark_user_id STRING comment '同贷信息登记/同贷登记用户id',
agreeloanmark_user_name STRING comment '同贷信息登记/同贷登记用户名',
agreeloanmark_option STRING comment '同贷信息登记/同贷登记审批意见',
agreeloanmark_status_name STRING comment '同贷信息登记/同贷登记审批状态',
agreeloanmark_atone_time timestamp comment '同贷信息登记(赎楼贷款)时间',
agreeloanmark_atone_user_id STRING comment '同贷信息登记(赎楼贷款)用户id',
agreeloanmark_atone_user_name STRING comment '同贷信息登记(赎楼贷款)用户名',
agreeloanmark_atone_option STRING comment '同贷信息登记(赎楼贷款)审批意见',
agreeloanmark_atone_status_name STRING comment '同贷信息登记(赎楼贷款)审批状态',
applycheck_time timestamp comment '报审/报单时间',
applycheck_user_id STRING comment '报审/报单用户id',
applycheck_user_name STRING comment '报审/报单用户名',
applycheck_option STRING comment '报审/报单审批意见',
applycheck_status_name STRING comment '报审/报单审批状态',
applyloan_time timestamp comment '申请贷款时间',
applyloan_user_id STRING comment '申请贷款用户id',
applyloan_user_name STRING comment '申请贷款用户名',
applyloan_option STRING comment '申请贷款审批意见',
applyloan_status_name STRING comment '申请贷款审批状态',
applyloan_atone_time timestamp comment '申请贷款(赎楼贷款)时间',
applyloan_atone_user_id STRING comment '申请贷款(赎楼贷款)用户id',
applyloan_atone_user_name STRING comment '申请贷款(赎楼贷款)用户名',
applyloan_atone_option STRING comment '申请贷款(赎楼贷款)审批意见',
applyloan_atone_status_name STRING comment '申请贷款(赎楼贷款)审批状态',
applyorder_time timestamp comment '业务申请时间',
applyorder_user_id STRING comment '业务申请用户id',
applyorder_user_name STRING comment '业务申请用户名',
applyorder_option STRING comment '业务申请审批意见',
applyorder_status_name STRING comment '业务申请审批状态',
appointinterview_time timestamp comment '预约面签时间',
appointinterview_user_id STRING comment '预约面签用户id',
appointinterview_user_name STRING comment '预约面签用户名',
appointinterview_option STRING comment '预约面签审批意见',
appointinterview_status_name STRING comment '预约面签审批状态',
approvalresult_time timestamp comment '审批结果确定/审批结果确认时间',
approvalresult_user_id STRING comment '审批结果确定/审批结果确认用户id',
approvalresult_user_name STRING comment '审批结果确定/审批结果确认用户名',
approvalresult_option STRING comment '审批结果确定/审批结果确认审批意见',
approvalresult_status_name STRING comment '审批结果确定/审批结果确认审批状态',
billcheck_time timestamp comment '出账前审查时间',
billcheck_user_id STRING comment '出账前审查用户id',
billcheck_user_name STRING comment '出账前审查用户名',
billcheck_option STRING comment '出账前审查审批意见',
billcheck_status_name STRING comment '出账前审查审批状态',
canclemortgage_time timestamp comment '注销抵押时间',
canclemortgage_user_id STRING comment '注销抵押用户id',
canclemortgage_user_name STRING comment '注销抵押用户名',
canclemortgage_option STRING comment '注销抵押审批意见',
canclemortgage_status_name STRING comment '注销抵押审批状态',
canclemortgage_zz_time timestamp comment '注销抵押_郑州时间',
canclemortgage_zz_user_id STRING comment '注销抵押_郑州用户id',
canclemortgage_zz_user_name STRING comment '注销抵押_郑州用户名',
canclemortgage_zz_option STRING comment '注销抵押_郑州审批意见',
canclemortgage_zz_status_name STRING comment '注销抵押_郑州审批状态',
checkmarpush_time timestamp comment '外传指令推送/审批资料推送时间',
checkmarpush_user_id STRING comment '外传指令推送/审批资料推送用户id',
checkmarpush_user_name STRING comment '外传指令推送/审批资料推送用户名',
checkmarpush_option STRING comment '外传指令推送/审批资料推送审批意见',
checkmarpush_status_name STRING comment '外传指令推送/审批资料推送审批状态',
checkmarsend_time timestamp comment '审批资料外传时间',
checkmarsend_user_id STRING comment '审批资料外传用户id',
checkmarsend_user_name STRING comment '审批资料外传用户名',
checkmarsend_option STRING comment '审批资料外传审批意见',
checkmarsend_status_name STRING comment '审批资料外传审批状态',
checkresensure_time timestamp comment '审批结果确定/审批结果确认时间',
checkresensure_user_id STRING comment '审批结果确定/审批结果确认用户id',
checkresensure_user_name STRING comment '审批结果确定/审批结果确认用户名',
checkresensure_option STRING comment '审批结果确定/审批结果确认审批意见',
checkresensure_status_name STRING comment '审批结果确定/审批结果确认审批状态',
confirmarrival_time timestamp comment '确认资金到账时间',
confirmarrival_user_id STRING comment '确认资金到账用户id',
confirmarrival_user_name STRING comment '确认资金到账用户名',
confirmarrival_option STRING comment '确认资金到账审批意见',
confirmarrival_status_name STRING comment '确认资金到账审批状态',
confirmtailarrial_time timestamp comment '确认资金到账（尾款）时间',
confirmtailarrial_user_id STRING comment '确认资金到账（尾款）用户id',
confirmtailarrial_user_name STRING comment '确认资金到账（尾款）用户名',
confirmtailarrial_option STRING comment '确认资金到账（尾款）审批意见',
confirmtailarrial_status_name STRING comment '确认资金到账（尾款）审批状态',
confirmtransfertail_time timestamp comment '尾款划拨确认时间',
confirmtransfertail_user_id STRING comment '尾款划拨确认用户id',
confirmtransfertail_user_name STRING comment '尾款划拨确认用户名',
confirmtransfertail_option STRING comment '尾款划拨确认审批意见',
confirmtransfertail_status_name STRING comment '尾款划拨确认审批状态',
costconfirm_time timestamp comment '缴费确认时间',
costconfirm_user_id STRING comment '缴费确认用户id',
costconfirm_user_name STRING comment '缴费确认用户名',
costconfirm_option STRING comment '缴费确认审批意见',
costconfirm_status_name STRING comment '缴费确认审批状态',
costitemmark_time timestamp comment '费项登记时间',
costitemmark_user_id STRING comment '费项登记用户id',
costitemmark_user_name STRING comment '费项登记用户名',
costitemmark_option STRING comment '费项登记审批意见',
costitemmark_status_name STRING comment '费项登记审批状态',
costmark_time timestamp comment '费率登记/费用登记时间',
costmark_user_id STRING comment '费率登记/费用登记用户id',
costmark_user_name STRING comment '费率登记/费用登记用户名',
costmark_option STRING comment '费率登记/费用登记审批意见',
costmark_status_name STRING comment '费率登记/费用登记审批状态',
creditconfirm_time timestamp comment '征信确认时间',
creditconfirm_user_id STRING comment '征信确认用户id',
creditconfirm_user_name STRING comment '征信确认用户名',
creditconfirm_option STRING comment '征信确认审批意见',
creditconfirm_status_name STRING comment '征信确认审批状态',
datainspection_time timestamp comment '资料齐全时间',
datainspection_user_id STRING comment '资料齐全用户id',
datainspection_user_name STRING comment '资料齐全用户名',
datainspection_option STRING comment '资料齐全审批意见',
datainspection_status_name STRING comment '资料齐全审批状态',
endnode_time timestamp comment '结束节点时间',
endnode_user_id STRING comment '结束节点用户id',
endnode_user_name STRING comment '结束节点用户名',
endnode_option STRING comment '结束节点审批意见',
endnode_status_name STRING comment '结束节点审批状态',
finalloan_time timestamp comment '贷款上报终审时间',
finalloan_user_id STRING comment '贷款上报终审用户id',
finalloan_user_name STRING comment '贷款上报终审用户名',
finalloan_option STRING comment '贷款上报终审审批意见',
finalloan_status_name STRING comment '贷款上报终审审批状态',
financialarchiveevent_time timestamp comment '财务归档时间',
financialarchiveevent_user_id STRING comment '财务归档用户id',
financialarchiveevent_user_name STRING comment '财务归档用户名',
financialarchiveevent_option STRING comment '财务归档审批意见',
financialarchiveevent_status_name STRING comment '财务归档审批状态',
flooradvance_time timestamp comment '赎楼前垫资回款时间',
flooradvance_user_id STRING comment '赎楼前垫资回款用户id',
flooradvance_user_name STRING comment '赎楼前垫资回款用户名',
flooradvance_option STRING comment '赎楼前垫资回款审批意见',
flooradvance_status_name STRING comment '赎楼前垫资回款审批状态',
getcancelmaterial_time timestamp comment '领取注销资料时间',
getcancelmaterial_user_id STRING comment '领取注销资料用户id',
getcancelmaterial_user_name STRING comment '领取注销资料用户名',
getcancelmaterial_option STRING comment '领取注销资料审批意见',
getcancelmaterial_status_name STRING comment '领取注销资料审批状态',
houseappraisal_time timestamp comment '房产评估时间',
houseappraisal_user_id STRING comment '房产评估用户id',
houseappraisal_user_name STRING comment '房产评估用户名',
houseappraisal_option STRING comment '房产评估审批意见',
houseappraisal_status_name STRING comment '房产评估审批状态',
householdapprove_time timestamp comment '下户审批时间',
householdapprove_user_id STRING comment '下户审批用户id',
householdapprove_user_name STRING comment '下户审批用户名',
householdapprove_option STRING comment '下户审批审批意见',
householdapprove_status_name STRING comment '下户审批审批状态',
householdsurvey_time timestamp comment '下户调查/下户时间',
householdsurvey_user_id STRING comment '下户调查/下户用户id',
householdsurvey_user_name STRING comment '下户调查/下户用户名',
householdsurvey_option STRING comment '下户调查/下户审批意见',
householdsurvey_status_name STRING comment '下户调查/下户审批状态',
houseinspection_time timestamp comment '查房时间',
houseinspection_user_id STRING comment '查房用户id',
houseinspection_user_name STRING comment '查房用户名',
houseinspection_option STRING comment '查房审批意见',
houseinspection_status_name STRING comment '查房审批状态',
inputinfo_time timestamp comment '录入时间',
inputinfo_user_id STRING comment '录入用户id',
inputinfo_user_name STRING comment '录入用户名',
inputinfo_option STRING comment '录入审批意见',
inputinfo_status_name STRING comment '录入审批状态',
inputinfocomplete_time timestamp comment '录入完成时间',
inputinfocomplete_user_id STRING comment '录入完成用户id',
inputinfocomplete_user_name STRING comment '录入完成用户名',
inputinfocomplete_option STRING comment '录入完成审批意见',
inputinfocomplete_status_name STRING comment '录入完成审批状态',
insuranceinfoconfirm_time timestamp comment '保单信息确认时间',
insuranceinfoconfirm_user_id STRING comment '保单信息确认用户id',
insuranceinfoconfirm_user_name STRING comment '保单信息确认用户名',
insuranceinfoconfirm_option STRING comment '保单信息确认审批意见',
insuranceinfoconfirm_status_name STRING comment '保单信息确认审批状态',
interview_time timestamp comment '面签时间',
interview_user_id STRING comment '面签用户id',
interview_user_name STRING comment '面签用户名',
interview_option STRING comment '面签审批意见',
interview_status_name STRING comment '面签审批状态',
investigate_time timestamp comment '审查时间',
investigate_user_id STRING comment '审查用户id',
investigate_user_name STRING comment '审查用户名',
investigate_option STRING comment '审查审批意见',
investigate_status_name STRING comment '审查审批状态',
mancheck_time timestamp comment '审批时间',
mancheck_user_id STRING comment '审批用户id',
mancheck_user_name STRING comment '审批用户名',
mancheck_option STRING comment '审批审批意见',
mancheck_status_name STRING comment '审批审批状态',
mortgageout_time timestamp comment '抵押出件时间',
mortgageout_user_id STRING comment '抵押出件用户id',
mortgageout_user_name STRING comment '抵押出件用户名',
mortgageout_option STRING comment '抵押出件审批意见',
mortgageout_status_name STRING comment '抵押出件审批状态',
mortgageout_zz_time timestamp comment '抵押出件_郑州时间',
mortgageout_zz_user_id STRING comment '抵押出件_郑州用户id',
mortgageout_zz_user_name STRING comment '抵押出件_郑州用户名',
mortgageout_zz_option STRING comment '抵押出件_郑州审批意见',
mortgageout_zz_status_name STRING comment '抵押出件_郑州审批状态',
mortgagepass_time timestamp comment '抵押递件时间',
mortgagepass_user_id STRING comment '抵押递件用户id',
mortgagepass_user_name STRING comment '抵押递件用户名',
mortgagepass_option STRING comment '抵押递件审批意见',
mortgagepass_status_name STRING comment '抵押递件审批状态',
mortgagepass_zz_time timestamp comment '抵押递件_郑州时间',
mortgagepass_zz_user_id STRING comment '抵押递件_郑州用户id',
mortgagepass_zz_user_name STRING comment '抵押递件_郑州用户名',
mortgagepass_zz_option STRING comment '抵押递件_郑州审批意见',
mortgagepass_zz_status_name STRING comment '抵押递件_郑州审批状态',
notarization_time timestamp comment '办理公证时间',
notarization_user_id STRING comment '办理公证用户id',
notarization_user_name STRING comment '办理公证用户名',
notarization_option STRING comment '办理公证审批意见',
notarization_status_name STRING comment '办理公证审批状态',
overinsurance_time timestamp comment '解保时间',
overinsurance_user_id STRING comment '解保用户id',
overinsurance_user_name STRING comment '解保用户名',
overinsurance_option STRING comment '解保审批意见',
overinsurance_status_name STRING comment '解保审批状态',
patch_ds_time timestamp comment '大数补件时间',
patch_ds_user_id STRING comment '大数补件用户id',
patch_ds_user_name STRING comment '大数补件用户名',
patch_ds_option STRING comment '大数补件审批意见',
patch_ds_status_name STRING comment '大数补件审批状态',
paymentarrival_time timestamp comment '确认回款资金到账时间',
paymentarrival_user_id STRING comment '确认回款资金到账用户id',
paymentarrival_user_name STRING comment '确认回款资金到账用户名',
paymentarrival_option STRING comment '确认回款资金到账审批意见',
paymentarrival_status_name STRING comment '确认回款资金到账审批状态',
platformarrival_time timestamp comment '确认平台款到账时间',
platformarrival_user_id STRING comment '确认平台款到账用户id',
platformarrival_user_name STRING comment '确认平台款到账用户名',
platformarrival_option STRING comment '确认平台款到账审批意见',
platformarrival_status_name STRING comment '确认平台款到账审批状态',
policyapply_time timestamp comment '出保单申请时间',
policyapply_user_id STRING comment '出保单申请用户id',
policyapply_user_name STRING comment '出保单申请用户名',
policyapply_option STRING comment '出保单申请审批意见',
policyapply_status_name STRING comment '出保单申请审批状态',
prefile_time timestamp comment '归档时间',
prefile_user_id STRING comment '归档用户id',
prefile_user_name STRING comment '归档用户名',
prefile_option STRING comment '归档审批意见',
prefile_status_name STRING comment '归档审批状态',
prerandom_time timestamp comment '预约赎楼时间',
prerandom_user_id STRING comment '预约赎楼用户id',
prerandom_user_name STRING comment '预约赎楼用户名',
prerandom_option STRING comment '预约赎楼审批意见',
prerandom_status_name STRING comment '预约赎楼审批状态',
pushloancommand_time timestamp comment '放款指令推送时间',
pushloancommand_user_id STRING comment '放款指令推送用户id',
pushloancommand_user_name STRING comment '放款指令推送用户名',
pushloancommand_option STRING comment '放款指令推送审批意见',
pushloancommand_status_name STRING comment '放款指令推送审批状态',
pushoutcommand_time timestamp comment '外传指令推送/审批资料推送时间',
pushoutcommand_user_id STRING comment '外传指令推送/审批资料推送用户id',
pushoutcommand_user_name STRING comment '外传指令推送/审批资料推送用户名',
pushoutcommand_option STRING comment '外传指令推送/审批资料推送审批意见',
pushoutcommand_status_name STRING comment '外传指令推送/审批资料推送审批状态',
queryarchive_time timestamp comment '查档时间',
queryarchive_user_id STRING comment '查档用户id',
queryarchive_user_name STRING comment '查档用户名',
queryarchive_option STRING comment '查档审批意见',
queryarchive_status_name STRING comment '查档审批状态',
randomcashback_time timestamp comment '赎楼资金划回时间',
randomcashback_user_id STRING comment '赎楼资金划回用户id',
randomcashback_user_name STRING comment '赎楼资金划回用户名',
randomcashback_option STRING comment '赎楼资金划回审批意见',
randomcashback_status_name STRING comment '赎楼资金划回审批状态',
randommark_time timestamp comment '赎楼登记时间',
randommark_user_id STRING comment '赎楼登记用户id',
randommark_user_name STRING comment '赎楼登记用户名',
randommark_option STRING comment '赎楼登记审批意见',
randommark_status_name STRING comment '赎楼登记审批状态',
repaymentconfirm_time timestamp comment '还款确认时间',
repaymentconfirm_user_id STRING comment '还款确认用户id',
repaymentconfirm_user_name STRING comment '还款确认用户名',
repaymentconfirm_option STRING comment '还款确认审批意见',
repaymentconfirm_status_name STRING comment '还款确认审批状态',
sendloancommand_time timestamp comment '发送放款指令时间',
sendloancommand_user_id STRING comment '发送放款指令用户id',
sendloancommand_user_name STRING comment '发送放款指令用户名',
sendloancommand_option STRING comment '发送放款指令审批意见',
sendloancommand_status_name STRING comment '发送放款指令审批状态',
sendloanrelesecommand_time timestamp comment '发送款项释放指令时间',
sendloanrelesecommand_user_id STRING comment '发送款项释放指令用户id',
sendloanrelesecommand_user_name STRING comment '发送款项释放指令用户名',
sendloanrelesecommand_option STRING comment '发送款项释放指令审批意见',
sendloanrelesecommand_status_name STRING comment '发送款项释放指令审批状态',
sendverifymaterial_time timestamp comment '核保资料外传时间',
sendverifymaterial_user_id STRING comment '核保资料外传用户id',
sendverifymaterial_user_name STRING comment '核保资料外传用户名',
sendverifymaterial_option STRING comment '核保资料外传审批意见',
sendverifymaterial_status_name STRING comment '核保资料外传审批状态',
startnode_time timestamp comment '发起节点时间',
startnode_user_id STRING comment '发起节点用户id',
startnode_user_name STRING comment '发起节点用户名',
startnode_option STRING comment '发起节点审批意见',
startnode_status_name STRING comment '发起节点审批状态',
submitverifyapply_time timestamp comment '提交核保申请时间',
submitverifyapply_user_id STRING comment '提交核保申请用户id',
submitverifyapply_user_name STRING comment '提交核保申请用户名',
submitverifyapply_option STRING comment '提交核保申请审批意见',
submitverifyapply_status_name STRING comment '提交核保申请审批状态',
transferin_time timestamp comment '过户递件时间',
transferin_user_id STRING comment '过户递件用户id',
transferin_user_name STRING comment '过户递件用户名',
transferin_option STRING comment '过户递件审批意见',
transferin_status_name STRING comment '过户递件审批状态',
transferin_zz_time timestamp comment '过户递件_郑州时间',
transferin_zz_user_id STRING comment '过户递件_郑州用户id',
transferin_zz_user_name STRING comment '过户递件_郑州用户名',
transferin_zz_option STRING comment '过户递件_郑州审批意见',
transferin_zz_status_name STRING comment '过户递件_郑州审批状态',
transfermark_time timestamp comment '放款登记时间',
transfermark_user_id STRING comment '放款登记用户id',
transfermark_user_name STRING comment '放款登记用户名',
transfermark_option STRING comment '放款登记审批意见',
transfermark_status_name STRING comment '放款登记审批状态',
transferout_time timestamp comment '过户出件时间',
transferout_user_id STRING comment '过户出件用户id',
transferout_user_name STRING comment '过户出件用户名',
transferout_option STRING comment '过户出件审批意见',
transferout_status_name STRING comment '过户出件审批状态',
transferout_zz_time timestamp comment '过户出件_郑州时间',
transferout_zz_user_id STRING comment '过户出件_郑州用户id',
transferout_zz_user_name STRING comment '过户出件_郑州用户名',
transferout_zz_option STRING comment '过户出件_郑州审批意见',
transferout_zz_status_name STRING comment '过户出件_郑州审批状态',
transfertail_time timestamp comment '尾款划拨申请时间',
transfertail_user_id STRING comment '尾款划拨申请用户id',
transfertail_user_name STRING comment '尾款划拨申请用户名',
transfertail_option STRING comment '尾款划拨申请审批意见',
transfertail_status_name STRING comment '尾款划拨申请审批状态',
trustaccount_time timestamp comment '要件托管时间',
trustaccount_user_id STRING comment '要件托管用户id',
trustaccount_user_name STRING comment '要件托管用户名',
trustaccount_option STRING comment '要件托管审批意见',
trustaccount_status_name STRING comment '要件托管审批状态',
uploadimg_time timestamp comment '资料反馈时间',
uploadimg_user_id STRING comment '资料反馈用户id',
uploadimg_user_name STRING comment '资料反馈用户名',
uploadimg_option STRING comment '资料反馈审批意见',
uploadimg_status_name STRING comment '资料反馈审批状态',
transfertailrelese_time timestamp comment '尾款释放时间',
transfertailrelese_user_id STRING comment '尾款释放用户id',
transfertailrelese_user_name STRING comment '尾款释放用户名',
transfertailrelese_option STRING comment '尾款释放审批意见',
transfertailrelese_status_name STRING comment '尾款释放审批状态',
precheck_time timestamp comment '预审批时间',
precheck_user_id STRING comment '预审批用户id',
precheck_user_name STRING comment '预审批用户名',
precheck_option STRING comment '预审批审批意见',
precheck_status_name STRING comment '预审批审批状态',
returnconfirm_time timestamp comment '资金归还确认时间',
returnconfirm_user_id STRING comment '资金归还确认用户id',
returnconfirm_user_name STRING comment '资金归还确认用户名',
returnconfirm_option STRING comment '资金归还确认审批意见',
returnconfirm_status_name STRING comment '资金归还确认审批状态',
mancheck2_time timestamp comment '人工审核时间',
mancheck2_user_id STRING comment '人工审核用户id',
mancheck2_user_name STRING comment '人工审核用户名',
mancheck2_option STRING comment '人工审核审批意见',
mancheck2_status_name STRING comment '人工审核审批状态',
lureturnapply_time timestamp comment '陆金所资金归还时间',
lureturnapply_user_id STRING comment '陆金所资金归还用户id',
lureturnapply_user_name STRING comment '陆金所资金归还用户名',
lureturnapply_option STRING comment '陆金所资金归还审批意见',
lureturnapply_status_name STRING comment '陆金所资金归还审批状态',
internalturnFunds_time timestamp comment '内部转款-归还时间',
internalturnFunds_user_id STRING comment '内部转款-归还用户id',
internalturnFunds_user_name STRING comment '内部转款-归还用户名',
internalturnFunds_option STRING comment '内部转款-归还审批意见',
internalturnFunds_status_name STRING comment '内部转款-归还审批状态',
mortgageprint_time timestamp comment '打印抵押材料时间',
mortgageprint_user_id STRING comment '打印抵押材料用户id',
mortgageprint_user_name STRING comment '打印抵押材料用户名',
mortgageprint_option STRING comment '打印抵押材料审批意见',
mortgageprint_status_name STRING comment '打印抵押材料审批状态',
bank_1_time timestamp comment '银行上会时间',
bank_1_user_id STRING comment '银行上会用户id',
bank_1_user_name STRING comment '银行上会用户名',
bank_1_option STRING comment '银行上会审批意见',
bank_1_status_name STRING comment '银行上会审批状态',
bank_2_time timestamp comment '银行输机时间',
bank_2_user_id STRING comment '银行输机用户id',
bank_2_user_name STRING comment '银行输机用户名',
bank_2_option STRING comment '银行输机审批意见',
bank_2_status_name STRING comment '银行输机审批状态',
custreceivableconfirm_time timestamp comment '客户回款确认时间',
custreceivableconfirm_user_id STRING comment '客户回款确认用户id',
custreceivableconfirm_user_name STRING comment '客户回款确认用户名',
custreceivableconfirm_option STRING comment '客户回款确认审批意见',
custreceivableconfirm_status_name STRING comment '客户回款确认审批状态',
principaltransfer_time timestamp comment '本息划拨申请时间',
principaltransfer_user_id STRING comment '本息划拨申请用户id',
principaltransfer_user_name STRING comment '本息划拨申请用户名',
principaltransfer_option STRING comment '本息划拨申请审批意见',
principaltransfer_status_name STRING comment '本息划拨申请审批状态',
principaltransferconfirm_time timestamp comment '本息划拨确认时间',
principaltransferconfirm_user_id STRING comment '本息划拨确认用户id',
principaltransferconfirm_user_name STRING comment '本息划拨确认用户名',
principaltransferconfirm_option STRING comment '本息划拨确认审批意见',
principaltransferconfirm_status_name STRING comment '本息划拨确认审批状态',
verifyinsurance_time timestamp comment '核保时间',
verifyinsurance_user_id STRING comment '核保用户id',
verifyinsurance_user_name STRING comment '核保用户名',
verifyinsurance_option STRING comment '核保审批意见',
verifyinsurance_status_name STRING comment '核保审批状态',
agreeloanresult_time timestamp comment '确认银行放款时间',
agreeloanresult_user_id STRING comment '确认银行放款用户id',
agreeloanresult_user_name STRING comment '确认银行放款用户名',
agreeloanresult_option STRING comment '确认银行放款审批意见',
agreeloanresult_status_name STRING comment '确认银行放款审批状态',
management_division_time timestamp comment '总部风险审批时间',
management_division_user_id STRING comment '总部风险审批用户id',
management_division_user_name STRING comment '总部风险审批用户名',
management_division_option STRING comment '总部风险审批意见',
management_division_status_name STRING comment '总部风险审批状态',
technology_time timestamp comment '科技时间',
technology_user_id STRING comment '科技用户id',
technology_user_name STRING comment '科技用户名',
technology_option STRING comment '科技意见',
technology_status_name STRING comment '科技状态',
manager_operation_time timestamp comment '总部运营审批时间',
manager_operation_user_id STRING comment '总部运营审批用户id',
manager_operation_user_name STRING comment '总部运营审批用户名',
manager_operation_option STRING comment '总部运营审批意见',
manager_operation_status_name STRING comment '总部运营审批状态',
operation_supervisor_time timestamp comment '运营主管审批时间',
operation_supervisor_user_id STRING comment '运营主管审批用户id',
operation_supervisor_user_name STRING comment '运营主管审批用户名',
operation_supervisor_option STRING comment '运营主管审批意见',
operation_supervisor_status_name STRING comment '运营主管审批状态',
riskmanager_time timestamp comment '风险部审批时间',
riskmanager_user_id STRING comment '风险部审批用户id',
riskmanager_user_name STRING comment '风险部审批用户名',
riskmanager_option STRING comment '风险部审批意见',
riskmanager_status_name STRING comment '风险部审批状态',
centralized_operation_time timestamp comment '集中作业中心审批时间',
centralized_operation_user_id STRING comment '集中作业中心审批用户id',
centralized_operation_user_name STRING comment '集中作业中心审批用户名',
centralized_operation_option STRING comment '集中作业中心审批意见',
centralized_operation_status_name STRING comment '集中作业中心审批状态',
centralized_operation_manager_time timestamp comment '集中作业中心主管审批时间',
centralized_operation_manager_user_id STRING comment '集中作业中心主管审批用户id',
centralized_operation_manager_user_name STRING comment '集中作业中心主管审批用户名',
centralized_operation_manager_option STRING comment '集中作业中心主管审批意见',
centralized_operation_manager_status_name STRING comment '集中作业中心主管审批状态',
marketing_supervisor_time timestamp comment '市场主管审批时间',
marketing_supervisor_user_id STRING comment '市场主管审批用户id',
marketing_supervisor_user_name STRING comment '市场主管审批用户名',
marketing_supervisor_option STRING comment '市场主管审批意见',
marketing_supervisor_status_name STRING comment '市场主管审批状态',
capitalduty_time timestamp comment '资金岗审批时间',
capitalduty_user_id STRING comment '资金岗审批用户id',
capitalduty_user_name STRING comment '资金岗审批用户名',
capitalduty_option STRING comment '资金岗审批意见',
capitalduty_status_name STRING comment '资金岗审批状态',
sales_operation_time timestamp comment '销管审批时间',
sales_operation_user_id STRING comment '销管审批用户id',
sales_operation_user_name STRING comment '销管审批用户名',
sales_operation_option STRING comment '销管审批意见',
sales_operation_status_name STRING comment '销管审批状态'
) STORED AS parquet;
with tmp_check_opinion_common_ex as (
  select *, ROW_NUMBER() OVER(PARTITION BY proc_inst_id_,task_key_new_ ORDER BY complete_time_ desc) rn1
  from ods_bpms_bpm_check_opinion_common
)
insert overwrite table odstmp_bpms_bpms_bpm_check_opinion_flow_wx
select t666.*
from (
select proc_inst_id_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferapply' THEN t666.complete_time_ ELSE NULL END)) transferapply_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transferapply' THEN t666.auditor_ ELSE NULL END)) transferapply_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transferapply' THEN t666.auditor_name_ ELSE NULL END)) transferapply_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transferapply' THEN t666.opinion_ ELSE NULL END))  transferapply_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferapply' THEN t666.status_name_ ELSE NULL END))   transferapply_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferconfirm' THEN t666.complete_time_ ELSE NULL END)) transferconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transferconfirm' THEN t666.auditor_ ELSE NULL END)) transferconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transferconfirm' THEN t666.auditor_name_ ELSE NULL END)) transferconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transferconfirm' THEN t666.opinion_ ELSE NULL END))  transferconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferconfirm' THEN t666.status_name_ ELSE NULL END))   transferconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='returnapply' THEN t666.complete_time_ ELSE NULL END)) returnapply_time,
MAX((CASE WHEN lower(t666.task_key_new_)='returnapply' THEN t666.auditor_ ELSE NULL END)) returnapply_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='returnapply' THEN t666.auditor_name_ ELSE NULL END)) returnapply_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='returnapply' THEN t666.opinion_ ELSE NULL END))  returnapply_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='returnapply' THEN t666.status_name_ ELSE NULL END))   returnapply_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='accounttest' THEN t666.complete_time_ ELSE NULL END)) accounttest_time,
MAX((CASE WHEN lower(t666.task_key_new_)='accounttest' THEN t666.auditor_ ELSE NULL END)) accounttest_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='accounttest' THEN t666.auditor_name_ ELSE NULL END)) accounttest_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='accounttest' THEN t666.opinion_ ELSE NULL END))  accounttest_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='accounttest' THEN t666.status_name_ ELSE NULL END))   accounttest_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark' THEN t666.complete_time_ ELSE NULL END)) agreeloanmark_time,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark' THEN t666.auditor_ ELSE NULL END)) agreeloanmark_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark' THEN t666.auditor_name_ ELSE NULL END)) agreeloanmark_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark' THEN t666.opinion_ ELSE NULL END))  agreeloanmark_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark' THEN t666.status_name_ ELSE NULL END))   agreeloanmark_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark_atone' THEN t666.complete_time_ ELSE NULL END)) agreeloanmark_atone_time,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark_atone' THEN t666.auditor_ ELSE NULL END)) agreeloanmark_atone_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark_atone' THEN t666.auditor_name_ ELSE NULL END)) agreeloanmark_atone_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark_atone' THEN t666.opinion_ ELSE NULL END))  agreeloanmark_atone_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanmark_atone' THEN t666.status_name_ ELSE NULL END))   agreeloanmark_atone_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='applycheck' THEN t666.complete_time_ ELSE NULL END)) applycheck_time,
MAX((CASE WHEN lower(t666.task_key_new_)='applycheck' THEN t666.auditor_ ELSE NULL END)) applycheck_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='applycheck' THEN t666.auditor_name_ ELSE NULL END)) applycheck_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='applycheck' THEN t666.opinion_ ELSE NULL END))  applycheck_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='applycheck' THEN t666.status_name_ ELSE NULL END))   applycheck_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan' THEN t666.complete_time_ ELSE NULL END)) applyloan_time,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan' THEN t666.auditor_ ELSE NULL END)) applyloan_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan' THEN t666.auditor_name_ ELSE NULL END)) applyloan_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan' THEN t666.opinion_ ELSE NULL END))  applyloan_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan' THEN t666.status_name_ ELSE NULL END))   applyloan_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan_atone' THEN t666.complete_time_ ELSE NULL END)) applyloan_atone_time,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan_atone' THEN t666.auditor_ ELSE NULL END)) applyloan_atone_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan_atone' THEN t666.auditor_name_ ELSE NULL END)) applyloan_atone_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan_atone' THEN t666.opinion_ ELSE NULL END))  applyloan_atone_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='applyloan_atone' THEN t666.status_name_ ELSE NULL END))   applyloan_atone_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.complete_time_ ELSE NULL END)) applyorder_time,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.auditor_ ELSE NULL END)) applyorder_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.auditor_name_ ELSE NULL END)) applyorder_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.opinion_ ELSE NULL END))  applyorder_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='applyorder' THEN t666.status_name_ ELSE NULL END))   applyorder_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='appointinterview' THEN t666.complete_time_ ELSE NULL END)) appointinterview_time,
MAX((CASE WHEN lower(t666.task_key_new_)='appointinterview' THEN t666.auditor_ ELSE NULL END)) appointinterview_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='appointinterview' THEN t666.auditor_name_ ELSE NULL END)) appointinterview_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='appointinterview' THEN t666.opinion_ ELSE NULL END))  appointinterview_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='appointinterview' THEN t666.status_name_ ELSE NULL END))   appointinterview_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.complete_time_ ELSE NULL END)) approvalresult_time,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.auditor_ ELSE NULL END)) approvalresult_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.auditor_name_ ELSE NULL END)) approvalresult_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.opinion_ ELSE NULL END))  approvalresult_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='approvalresult' THEN t666.status_name_ ELSE NULL END))   approvalresult_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='billcheck' THEN t666.complete_time_ ELSE NULL END)) billcheck_time,
MAX((CASE WHEN lower(t666.task_key_new_)='billcheck' THEN t666.auditor_ ELSE NULL END)) billcheck_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='billcheck' THEN t666.auditor_name_ ELSE NULL END)) billcheck_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='billcheck' THEN t666.opinion_ ELSE NULL END))  billcheck_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='billcheck' THEN t666.status_name_ ELSE NULL END))   billcheck_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage' THEN t666.complete_time_ ELSE NULL END)) canclemortgage_time,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage' THEN t666.auditor_ ELSE NULL END)) canclemortgage_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage' THEN t666.auditor_name_ ELSE NULL END)) canclemortgage_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage' THEN t666.opinion_ ELSE NULL END))  canclemortgage_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage' THEN t666.status_name_ ELSE NULL END))   canclemortgage_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage_zz' THEN t666.complete_time_ ELSE NULL END)) canclemortgage_zz_time,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage_zz' THEN t666.auditor_ ELSE NULL END)) canclemortgage_zz_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage_zz' THEN t666.auditor_name_ ELSE NULL END)) canclemortgage_zz_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage_zz' THEN t666.opinion_ ELSE NULL END))  canclemortgage_zz_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='canclemortgage_zz' THEN t666.status_name_ ELSE NULL END))   canclemortgage_zz_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarpush' THEN t666.complete_time_ ELSE NULL END)) checkmarpush_time,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarpush' THEN t666.auditor_ ELSE NULL END)) checkmarpush_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarpush' THEN t666.auditor_name_ ELSE NULL END)) checkmarpush_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarpush' THEN t666.opinion_ ELSE NULL END))  checkmarpush_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarpush' THEN t666.status_name_ ELSE NULL END))   checkmarpush_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.complete_time_ ELSE NULL END)) checkmarsend_time,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.auditor_ ELSE NULL END)) checkmarsend_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.auditor_name_ ELSE NULL END)) checkmarsend_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.opinion_ ELSE NULL END))  checkmarsend_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='checkmarsend' THEN t666.status_name_ ELSE NULL END))   checkmarsend_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='checkresensure' THEN t666.complete_time_ ELSE NULL END)) checkresensure_time,
MAX((CASE WHEN lower(t666.task_key_new_)='checkresensure' THEN t666.auditor_ ELSE NULL END)) checkresensure_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='checkresensure' THEN t666.auditor_name_ ELSE NULL END)) checkresensure_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='checkresensure' THEN t666.opinion_ ELSE NULL END))  checkresensure_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='checkresensure' THEN t666.status_name_ ELSE NULL END))   checkresensure_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmarrival' THEN t666.complete_time_ ELSE NULL END)) confirmarrival_time,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmarrival' THEN t666.auditor_ ELSE NULL END)) confirmarrival_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmarrival' THEN t666.auditor_name_ ELSE NULL END)) confirmarrival_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmarrival' THEN t666.opinion_ ELSE NULL END))  confirmarrival_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmarrival' THEN t666.status_name_ ELSE NULL END))   confirmarrival_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtailarrial' THEN t666.complete_time_ ELSE NULL END)) confirmtailarrial_time,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtailarrial' THEN t666.auditor_ ELSE NULL END)) confirmtailarrial_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtailarrial' THEN t666.auditor_name_ ELSE NULL END)) confirmtailarrial_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtailarrial' THEN t666.opinion_ ELSE NULL END))  confirmtailarrial_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtailarrial' THEN t666.status_name_ ELSE NULL END))   confirmtailarrial_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtransfertail' THEN t666.complete_time_ ELSE NULL END)) confirmtransfertail_time,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtransfertail' THEN t666.auditor_ ELSE NULL END)) confirmtransfertail_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtransfertail' THEN t666.auditor_name_ ELSE NULL END)) confirmtransfertail_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtransfertail' THEN t666.opinion_ ELSE NULL END))  confirmtransfertail_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='confirmtransfertail' THEN t666.status_name_ ELSE NULL END))   confirmtransfertail_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='costconfirm' THEN t666.complete_time_ ELSE NULL END)) costconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='costconfirm' THEN t666.auditor_ ELSE NULL END)) costconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='costconfirm' THEN t666.auditor_name_ ELSE NULL END)) costconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='costconfirm' THEN t666.opinion_ ELSE NULL END))  costconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='costconfirm' THEN t666.status_name_ ELSE NULL END))   costconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.complete_time_ ELSE NULL END)) costitemmark_time,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.auditor_ ELSE NULL END)) costitemmark_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.auditor_name_ ELSE NULL END)) costitemmark_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.opinion_ ELSE NULL END))  costitemmark_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='costitemmark' THEN t666.status_name_ ELSE NULL END))   costitemmark_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.complete_time_ ELSE NULL END)) costmark_time,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.auditor_ ELSE NULL END)) costmark_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.auditor_name_ ELSE NULL END)) costmark_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.opinion_ ELSE NULL END))  costmark_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='costmark' THEN t666.status_name_ ELSE NULL END))   costmark_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.complete_time_ ELSE NULL END)) creditconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.auditor_ ELSE NULL END)) creditconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.auditor_name_ ELSE NULL END)) creditconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.opinion_ ELSE NULL END))  creditconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='creditconfirm' THEN t666.status_name_ ELSE NULL END))   creditconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='datainspection' THEN t666.complete_time_ ELSE NULL END)) datainspection_time,
MAX((CASE WHEN lower(t666.task_key_new_)='datainspection' THEN t666.auditor_ ELSE NULL END)) datainspection_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='datainspection' THEN t666.auditor_name_ ELSE NULL END)) datainspection_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='datainspection' THEN t666.opinion_ ELSE NULL END))  datainspection_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='datainspection' THEN t666.status_name_ ELSE NULL END))   datainspection_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='endnode' THEN t666.complete_time_ ELSE NULL END)) endnode_time,
MAX((CASE WHEN lower(t666.task_key_new_)='endnode' THEN t666.auditor_ ELSE NULL END)) endnode_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='endnode' THEN t666.auditor_name_ ELSE NULL END)) endnode_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='endnode' THEN t666.opinion_ ELSE NULL END))  endnode_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='endnode' THEN t666.status_name_ ELSE NULL END))   endnode_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='finalloan' THEN t666.complete_time_ ELSE NULL END)) finalloan_time,
MAX((CASE WHEN lower(t666.task_key_new_)='finalloan' THEN t666.auditor_ ELSE NULL END)) finalloan_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='finalloan' THEN t666.auditor_name_ ELSE NULL END)) finalloan_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='finalloan' THEN t666.opinion_ ELSE NULL END))  finalloan_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='finalloan' THEN t666.status_name_ ELSE NULL END))   finalloan_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='financialarchiveevent' THEN t666.complete_time_ ELSE NULL END)) financialarchiveevent_time,
MAX((CASE WHEN lower(t666.task_key_new_)='financialarchiveevent' THEN t666.auditor_ ELSE NULL END)) financialarchiveevent_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='financialarchiveevent' THEN t666.auditor_name_ ELSE NULL END)) financialarchiveevent_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='financialarchiveevent' THEN t666.opinion_ ELSE NULL END))  financialarchiveevent_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='financialarchiveevent' THEN t666.status_name_ ELSE NULL END))   financialarchiveevent_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='flooradvance' THEN t666.complete_time_ ELSE NULL END)) flooradvance_time,
MAX((CASE WHEN lower(t666.task_key_new_)='flooradvance' THEN t666.auditor_ ELSE NULL END)) flooradvance_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='flooradvance' THEN t666.auditor_name_ ELSE NULL END)) flooradvance_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='flooradvance' THEN t666.opinion_ ELSE NULL END))  flooradvance_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='flooradvance' THEN t666.status_name_ ELSE NULL END))   flooradvance_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='getcancelmaterial' THEN t666.complete_time_ ELSE NULL END)) getcancelmaterial_time,
MAX((CASE WHEN lower(t666.task_key_new_)='getcancelmaterial' THEN t666.auditor_ ELSE NULL END)) getcancelmaterial_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='getcancelmaterial' THEN t666.auditor_name_ ELSE NULL END)) getcancelmaterial_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='getcancelmaterial' THEN t666.opinion_ ELSE NULL END))  getcancelmaterial_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='getcancelmaterial' THEN t666.status_name_ ELSE NULL END))   getcancelmaterial_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='houseappraisal' THEN t666.complete_time_ ELSE NULL END)) houseappraisal_time,
MAX((CASE WHEN lower(t666.task_key_new_)='houseappraisal' THEN t666.auditor_ ELSE NULL END)) houseappraisal_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='houseappraisal' THEN t666.auditor_name_ ELSE NULL END)) houseappraisal_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='houseappraisal' THEN t666.opinion_ ELSE NULL END))  houseappraisal_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='houseappraisal' THEN t666.status_name_ ELSE NULL END))   houseappraisal_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.complete_time_ ELSE NULL END)) householdapprove_time,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.auditor_ ELSE NULL END)) householdapprove_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.auditor_name_ ELSE NULL END)) householdapprove_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.opinion_ ELSE NULL END))  householdapprove_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='householdapprove' THEN t666.status_name_ ELSE NULL END))   householdapprove_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.complete_time_ ELSE NULL END)) householdsurvey_time,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.auditor_ ELSE NULL END)) householdsurvey_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.auditor_name_ ELSE NULL END)) householdsurvey_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.opinion_ ELSE NULL END))  householdsurvey_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='householdsurvey' THEN t666.status_name_ ELSE NULL END))   householdsurvey_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='houseinspection' THEN t666.complete_time_ ELSE NULL END)) houseinspection_time,
MAX((CASE WHEN lower(t666.task_key_new_)='houseinspection' THEN t666.auditor_ ELSE NULL END)) houseinspection_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='houseinspection' THEN t666.auditor_name_ ELSE NULL END)) houseinspection_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='houseinspection' THEN t666.opinion_ ELSE NULL END))  houseinspection_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='houseinspection' THEN t666.status_name_ ELSE NULL END))   houseinspection_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.complete_time_ ELSE NULL END)) inputinfo_time,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.auditor_ ELSE NULL END)) inputinfo_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.auditor_name_ ELSE NULL END)) inputinfo_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.opinion_ ELSE NULL END))  inputinfo_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfo' THEN t666.status_name_ ELSE NULL END))   inputinfo_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfocomplete' THEN t666.complete_time_ ELSE NULL END)) inputinfocomplete_time,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfocomplete' THEN t666.auditor_ ELSE NULL END)) inputinfocomplete_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfocomplete' THEN t666.auditor_name_ ELSE NULL END)) inputinfocomplete_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfocomplete' THEN t666.opinion_ ELSE NULL END))  inputinfocomplete_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='inputinfocomplete' THEN t666.status_name_ ELSE NULL END))   inputinfocomplete_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.complete_time_ ELSE NULL END)) insuranceinfoconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.auditor_ ELSE NULL END)) insuranceinfoconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.auditor_name_ ELSE NULL END)) insuranceinfoconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.opinion_ ELSE NULL END))  insuranceinfoconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='insuranceinfoconfirm' THEN t666.status_name_ ELSE NULL END))   insuranceinfoconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.complete_time_ ELSE NULL END)) interview_time,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.auditor_ ELSE NULL END)) interview_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.auditor_name_ ELSE NULL END)) interview_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.opinion_ ELSE NULL END))  interview_option,
MAX((CASE WHEN lower(t666.task_key_new_)='interview' THEN t666.status_name_ ELSE NULL END))   interview_status_name,
MAX((CASE WHEN lower(t666.task_key_new_)='investigate' THEN t666.complete_time_ ELSE NULL END)) investigate_time,
MAX((CASE WHEN lower(t666.task_key_new_)='investigate' THEN t666.auditor_ ELSE NULL END)) investigate_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='investigate' THEN t666.auditor_name_ ELSE NULL END)) investigate_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='investigate' THEN t666.opinion_ ELSE NULL END))  investigate_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='investigate' THEN t666.status_name_ ELSE NULL END))   investigate_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck' THEN t666.complete_time_ ELSE NULL END)) mancheck_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck' THEN t666.auditor_ ELSE NULL END)) mancheck_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck' THEN t666.auditor_name_ ELSE NULL END)) mancheck_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck' THEN t666.opinion_ ELSE NULL END))  mancheck_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck' THEN t666.status_name_ ELSE NULL END))   mancheck_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.complete_time_ ELSE NULL END)) mortgageout_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.auditor_ ELSE NULL END)) mortgageout_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.auditor_name_ ELSE NULL END)) mortgageout_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.opinion_ ELSE NULL END))  mortgageout_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout' THEN t666.status_name_ ELSE NULL END))   mortgageout_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout_zz' THEN t666.complete_time_ ELSE NULL END)) mortgageout_zz_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout_zz' THEN t666.auditor_ ELSE NULL END)) mortgageout_zz_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout_zz' THEN t666.auditor_name_ ELSE NULL END)) mortgageout_zz_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout_zz' THEN t666.opinion_ ELSE NULL END))  mortgageout_zz_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageout_zz' THEN t666.status_name_ ELSE NULL END))   mortgageout_zz_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.complete_time_ ELSE NULL END)) mortgagepass_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.auditor_ ELSE NULL END)) mortgagepass_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.auditor_name_ ELSE NULL END)) mortgagepass_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.opinion_ ELSE NULL END))  mortgagepass_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass' THEN t666.status_name_ ELSE NULL END))   mortgagepass_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass_zz' THEN t666.complete_time_ ELSE NULL END)) mortgagepass_zz_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass_zz' THEN t666.auditor_ ELSE NULL END)) mortgagepass_zz_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass_zz' THEN t666.auditor_name_ ELSE NULL END)) mortgagepass_zz_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass_zz' THEN t666.opinion_ ELSE NULL END))  mortgagepass_zz_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgagepass_zz' THEN t666.status_name_ ELSE NULL END))   mortgagepass_zz_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.complete_time_ ELSE NULL END)) notarization_time,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.auditor_ ELSE NULL END)) notarization_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.auditor_name_ ELSE NULL END)) notarization_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.opinion_ ELSE NULL END))  notarization_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='notarization' THEN t666.status_name_ ELSE NULL END))   notarization_status_name_,
MAX((CASE WHEN (lower(t666.task_key_new_)='overinsurance' or lower(t666.task_key_new_)='jb_pc') THEN t666.complete_time_ ELSE NULL END)) overinsurance_time,
MAX((CASE WHEN (lower(t666.task_key_new_)='overinsurance' or lower(t666.task_key_new_)='jb_pc') THEN t666.auditor_ ELSE NULL END)) overinsurance_user_id,
MAX((CASE WHEN (lower(t666.task_key_new_)='overinsurance' or lower(t666.task_key_new_)='jb_pc') THEN t666.auditor_name_ ELSE NULL END)) overinsurance_user_name,
MAX((CASE WHEN (lower(t666.task_key_new_)='overinsurance' or lower(t666.task_key_new_)='jb_pc') THEN t666.opinion_ ELSE NULL END))  overinsurance_option_,
MAX((CASE WHEN (lower(t666.task_key_new_)='overinsurance' or lower(t666.task_key_new_)='jb_pc') THEN t666.status_name_ ELSE NULL END))   overinsurance_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.complete_time_ ELSE NULL END)) patch_ds_time,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.auditor_ ELSE NULL END)) patch_ds_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.auditor_name_ ELSE NULL END)) patch_ds_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.opinion_ ELSE NULL END))  patch_ds_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='patch_ds' THEN t666.status_name_ ELSE NULL END))   patch_ds_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='paymentarrival' THEN t666.complete_time_ ELSE NULL END)) paymentarrival_time,
MAX((CASE WHEN lower(t666.task_key_new_)='paymentarrival' THEN t666.auditor_ ELSE NULL END)) paymentarrival_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='paymentarrival' THEN t666.auditor_name_ ELSE NULL END)) paymentarrival_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='paymentarrival' THEN t666.opinion_ ELSE NULL END))  paymentarrival_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='paymentarrival' THEN t666.status_name_ ELSE NULL END))   paymentarrival_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='platformarrival' THEN t666.complete_time_ ELSE NULL END)) platformarrival_time,
MAX((CASE WHEN lower(t666.task_key_new_)='platformarrival' THEN t666.auditor_ ELSE NULL END)) platformarrival_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='platformarrival' THEN t666.auditor_name_ ELSE NULL END)) platformarrival_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='platformarrival' THEN t666.opinion_ ELSE NULL END))  platformarrival_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='platformarrival' THEN t666.status_name_ ELSE NULL END))   platformarrival_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='policyapply' THEN t666.complete_time_ ELSE NULL END)) policyapply_time,
MAX((CASE WHEN lower(t666.task_key_new_)='policyapply' THEN t666.auditor_ ELSE NULL END)) policyapply_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='policyapply' THEN t666.auditor_name_ ELSE NULL END)) policyapply_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='policyapply' THEN t666.opinion_ ELSE NULL END))  policyapply_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='policyapply' THEN t666.status_name_ ELSE NULL END))   policyapply_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.complete_time_ ELSE NULL END)) prefile_time,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.auditor_ ELSE NULL END)) prefile_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.auditor_name_ ELSE NULL END)) prefile_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.opinion_ ELSE NULL END))  prefile_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='prefile' THEN t666.status_name_ ELSE NULL END))   prefile_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='prerandom' THEN t666.complete_time_ ELSE NULL END)) prerandom_time,
MAX((CASE WHEN lower(t666.task_key_new_)='prerandom' THEN t666.auditor_ ELSE NULL END)) prerandom_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='prerandom' THEN t666.auditor_name_ ELSE NULL END)) prerandom_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='prerandom' THEN t666.opinion_ ELSE NULL END))  prerandom_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='prerandom' THEN t666.status_name_ ELSE NULL END))   prerandom_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.complete_time_ ELSE NULL END)) pushloancommand_time,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.auditor_ ELSE NULL END)) pushloancommand_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.auditor_name_ ELSE NULL END)) pushloancommand_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.opinion_ ELSE NULL END))  pushloancommand_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='pushloancommand' THEN t666.status_name_ ELSE NULL END))   pushloancommand_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.complete_time_ ELSE NULL END)) pushoutcommand_time,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.auditor_ ELSE NULL END)) pushoutcommand_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.auditor_name_ ELSE NULL END)) pushoutcommand_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.opinion_ ELSE NULL END))  pushoutcommand_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='pushoutcommand' THEN t666.status_name_ ELSE NULL END))   pushoutcommand_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.complete_time_ ELSE NULL END)) queryarchive_time,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.auditor_ ELSE NULL END)) queryarchive_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.auditor_name_ ELSE NULL END)) queryarchive_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.opinion_ ELSE NULL END))  queryarchive_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='queryarchive' THEN t666.status_name_ ELSE NULL END))   queryarchive_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='randomcashback' THEN t666.complete_time_ ELSE NULL END)) randomcashback_time,
MAX((CASE WHEN lower(t666.task_key_new_)='randomcashback' THEN t666.auditor_ ELSE NULL END)) randomcashback_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='randomcashback' THEN t666.auditor_name_ ELSE NULL END)) randomcashback_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='randomcashback' THEN t666.opinion_ ELSE NULL END))  randomcashback_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='randomcashback' THEN t666.status_name_ ELSE NULL END))   randomcashback_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='randommark' THEN t666.complete_time_ ELSE NULL END)) randommark_time,
MAX((CASE WHEN lower(t666.task_key_new_)='randommark' THEN t666.auditor_ ELSE NULL END)) randommark_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='randommark' THEN t666.auditor_name_ ELSE NULL END)) randommark_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='randommark' THEN t666.opinion_ ELSE NULL END))  randommark_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='randommark' THEN t666.status_name_ ELSE NULL END))   randommark_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='repaymentconfirm' THEN t666.complete_time_ ELSE NULL END)) repaymentconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='repaymentconfirm' THEN t666.auditor_ ELSE NULL END)) repaymentconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='repaymentconfirm' THEN t666.auditor_name_ ELSE NULL END)) repaymentconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='repaymentconfirm' THEN t666.opinion_ ELSE NULL END))  repaymentconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='repaymentconfirm' THEN t666.status_name_ ELSE NULL END))   repaymentconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.complete_time_ ELSE NULL END)) sendloancommand_time,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.auditor_ ELSE NULL END)) sendloancommand_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.auditor_name_ ELSE NULL END)) sendloancommand_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.opinion_ ELSE NULL END))  sendloancommand_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloancommand' THEN t666.status_name_ ELSE NULL END))   sendloancommand_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloanrelesecommand' THEN t666.complete_time_ ELSE NULL END)) sendloanrelesecommand_time,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloanrelesecommand' THEN t666.auditor_ ELSE NULL END)) sendloanrelesecommand_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloanrelesecommand' THEN t666.auditor_name_ ELSE NULL END)) sendloanrelesecommand_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloanrelesecommand' THEN t666.opinion_ ELSE NULL END))  sendloanrelesecommand_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendloanrelesecommand' THEN t666.status_name_ ELSE NULL END))   sendloanrelesecommand_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.complete_time_ ELSE NULL END)) sendverifymaterial_time,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.auditor_ ELSE NULL END)) sendverifymaterial_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.auditor_name_ ELSE NULL END)) sendverifymaterial_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.opinion_ ELSE NULL END))  sendverifymaterial_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='sendverifymaterial' THEN t666.status_name_ ELSE NULL END))   sendverifymaterial_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='startnode' THEN t666.complete_time_ ELSE NULL END)) startnode_time,
MAX((CASE WHEN lower(t666.task_key_new_)='startnode' THEN t666.auditor_ ELSE NULL END)) startnode_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='startnode' THEN t666.auditor_name_ ELSE NULL END)) startnode_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='startnode' THEN t666.opinion_ ELSE NULL END))  startnode_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='startnode' THEN t666.status_name_ ELSE NULL END))   startnode_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.complete_time_ ELSE NULL END)) submitverifyapply_time,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.auditor_ ELSE NULL END)) submitverifyapply_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.auditor_name_ ELSE NULL END)) submitverifyapply_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.opinion_ ELSE NULL END))  submitverifyapply_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='submitverifyapply' THEN t666.status_name_ ELSE NULL END))   submitverifyapply_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin' THEN t666.complete_time_ ELSE NULL END)) transferin_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin' THEN t666.auditor_ ELSE NULL END)) transferin_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin' THEN t666.auditor_name_ ELSE NULL END)) transferin_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin' THEN t666.opinion_ ELSE NULL END))  transferin_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin' THEN t666.status_name_ ELSE NULL END))   transferin_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin_zz' THEN t666.complete_time_ ELSE NULL END)) transferin_zz_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin_zz' THEN t666.auditor_ ELSE NULL END)) transferin_zz_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin_zz' THEN t666.auditor_name_ ELSE NULL END)) transferin_zz_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin_zz' THEN t666.opinion_ ELSE NULL END))  transferin_zz_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferin_zz' THEN t666.status_name_ ELSE NULL END))   transferin_zz_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.complete_time_ ELSE NULL END)) transfermark_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.auditor_ ELSE NULL END)) transfermark_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.auditor_name_ ELSE NULL END)) transfermark_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.opinion_ ELSE NULL END))  transfermark_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transfermark' THEN t666.status_name_ ELSE NULL END))   transfermark_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout' THEN t666.complete_time_ ELSE NULL END)) transferout_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout' THEN t666.auditor_ ELSE NULL END)) transferout_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout' THEN t666.auditor_name_ ELSE NULL END)) transferout_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout' THEN t666.opinion_ ELSE NULL END))  transferout_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout' THEN t666.status_name_ ELSE NULL END))   transferout_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout_zz' THEN t666.complete_time_ ELSE NULL END)) transferout_zz_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout_zz' THEN t666.auditor_ ELSE NULL END)) transferout_zz_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout_zz' THEN t666.auditor_name_ ELSE NULL END)) transferout_zz_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout_zz' THEN t666.opinion_ ELSE NULL END))  transferout_zz_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transferout_zz' THEN t666.status_name_ ELSE NULL END))   transferout_zz_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertail' THEN t666.complete_time_ ELSE NULL END)) transfertail_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertail' THEN t666.auditor_ ELSE NULL END)) transfertail_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertail' THEN t666.auditor_name_ ELSE NULL END)) transfertail_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertail' THEN t666.opinion_ ELSE NULL END))  transfertail_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertail' THEN t666.status_name_ ELSE NULL END))   transfertail_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.complete_time_ ELSE NULL END)) trustaccount_time,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.auditor_ ELSE NULL END)) trustaccount_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.auditor_name_ ELSE NULL END)) trustaccount_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.opinion_ ELSE NULL END))  trustaccount_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='trustaccount' THEN t666.status_name_ ELSE NULL END))   trustaccount_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.complete_time_ ELSE NULL END)) uploadimg_time,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.auditor_ ELSE NULL END)) uploadimg_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.auditor_name_ ELSE NULL END)) uploadimg_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.opinion_ ELSE NULL END))  uploadimg_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='uploadimg' THEN t666.status_name_ ELSE NULL END))   uploadimg_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertailrelese' THEN t666.complete_time_ ELSE NULL END)) transfertailrelese_time,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertailrelese' THEN t666.auditor_ ELSE NULL END)) transfertailrelese_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertailrelese' THEN t666.auditor_name_ ELSE NULL END)) transfertailrelese_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertailrelese' THEN t666.opinion_ ELSE NULL END))  transfertailrelese_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='transfertailrelese' THEN t666.status_name_ ELSE NULL END))   transfertailrelese_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='precheck' THEN t666.complete_time_ ELSE NULL END)) precheck_time,
MAX((CASE WHEN lower(t666.task_key_new_)='precheck' THEN t666.auditor_ ELSE NULL END)) precheck_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='precheck' THEN t666.auditor_name_ ELSE NULL END)) precheck_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='precheck' THEN t666.opinion_ ELSE NULL END))  precheck_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='precheck' THEN t666.status_name_ ELSE NULL END))   precheck_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='returnconfirm' THEN t666.complete_time_ ELSE NULL END)) returnconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='returnconfirm' THEN t666.auditor_ ELSE NULL END)) returnconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='returnconfirm' THEN t666.auditor_name_ ELSE NULL END)) returnconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='returnconfirm' THEN t666.opinion_ ELSE NULL END))  returnconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='returnconfirm' THEN t666.status_name_ ELSE NULL END))   returnconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck2' THEN t666.complete_time_ ELSE NULL END)) mancheck2_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck2' THEN t666.auditor_ ELSE NULL END)) mancheck2_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck2' THEN t666.auditor_name_ ELSE NULL END)) mancheck2_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck2' THEN t666.opinion_ ELSE NULL END))  mancheck2_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mancheck2' THEN t666.status_name_ ELSE NULL END))   mancheck2_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='lureturnapply' THEN t666.complete_time_ ELSE NULL END)) lureturnapply_time,
MAX((CASE WHEN lower(t666.task_key_new_)='lureturnapply' THEN t666.auditor_ ELSE NULL END)) lureturnapply_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='lureturnapply' THEN t666.auditor_name_ ELSE NULL END)) lureturnapply_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='lureturnapply' THEN t666.opinion_ ELSE NULL END))  lureturnapply_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='lureturnapply' THEN t666.status_name_ ELSE NULL END))   lureturnapply_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='internalturnFunds' THEN t666.complete_time_ ELSE NULL END)) internalturnFunds_time,
MAX((CASE WHEN lower(t666.task_key_new_)='internalturnFunds' THEN t666.auditor_ ELSE NULL END)) internalturnFunds_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='internalturnFunds' THEN t666.auditor_name_ ELSE NULL END)) internalturnFunds_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='internalturnFunds' THEN t666.opinion_ ELSE NULL END))  internalturnFunds_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='internalturnFunds' THEN t666.status_name_ ELSE NULL END))   internalturnFunds_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageprint' THEN t666.complete_time_ ELSE NULL END)) mortgageprint_time,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageprint' THEN t666.auditor_ ELSE NULL END)) mortgageprint_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageprint' THEN t666.auditor_name_ ELSE NULL END)) mortgageprint_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageprint' THEN t666.opinion_ ELSE NULL END))  mortgageprint_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='mortgageprint' THEN t666.status_name_ ELSE NULL END))   mortgageprint_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_1' THEN t666.complete_time_ ELSE NULL END)) bank_1_time,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_1' THEN t666.auditor_ ELSE NULL END)) bank_1_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_1' THEN t666.auditor_name_ ELSE NULL END)) bank_1_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_1' THEN t666.opinion_ ELSE NULL END))  bank_1_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_1' THEN t666.status_name_ ELSE NULL END))   bank_1_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_2' THEN t666.complete_time_ ELSE NULL END)) bank_2_time,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_2' THEN t666.auditor_ ELSE NULL END)) bank_2_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_2' THEN t666.auditor_name_ ELSE NULL END)) bank_2_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_2' THEN t666.opinion_ ELSE NULL END))  bank_2_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='bank_2' THEN t666.status_name_ ELSE NULL END))   bank_2_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='custreceivableconfirm' THEN t666.complete_time_ ELSE NULL END)) custreceivableconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='custreceivableconfirm' THEN t666.auditor_ ELSE NULL END)) custreceivableconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='custreceivableconfirm' THEN t666.auditor_name_ ELSE NULL END)) custreceivableconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='custreceivableconfirm' THEN t666.opinion_ ELSE NULL END))  custreceivableconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='custreceivableconfirm' THEN t666.status_name_ ELSE NULL END))   custreceivableconfirm_status_name_,
-- MAX((CASE WHEN lower(t666.task_key_new_)='other' THEN t666.complete_time_ ELSE NULL END)) other_time,
-- MAX((CASE WHEN lower(t666.task_key_new_)='other' THEN t666.auditor_ ELSE NULL END)) other_user_id,
-- MAX((CASE WHEN lower(t666.task_key_new_)='other' THEN t666.auditor_name_ ELSE NULL END)) other_user_name,
-- MAX((CASE WHEN lower(t666.task_key_new_)='other' THEN t666.opinion_ ELSE NULL END))  other_option_,
-- MAX((CASE WHEN lower(t666.task_key_new_)='other' THEN t666.status_name_ ELSE NULL END))   other_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransfer' THEN t666.complete_time_ ELSE NULL END)) principaltransfer_time,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransfer' THEN t666.auditor_ ELSE NULL END)) principaltransfer_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransfer' THEN t666.auditor_name_ ELSE NULL END)) principaltransfer_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransfer' THEN t666.opinion_ ELSE NULL END))  principaltransfer_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransfer' THEN t666.status_name_ ELSE NULL END))   principaltransfer_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransferconfirm' THEN t666.complete_time_ ELSE NULL END)) principaltransferconfirm_time,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransferconfirm' THEN t666.auditor_ ELSE NULL END)) principaltransferconfirm_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransferconfirm' THEN t666.auditor_name_ ELSE NULL END)) principaltransferconfirm_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransferconfirm' THEN t666.opinion_ ELSE NULL END))  principaltransferconfirm_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='principaltransferconfirm' THEN t666.status_name_ ELSE NULL END))   principaltransferconfirm_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='verifyinsurance' THEN t666.complete_time_ ELSE NULL END)) verifyinsurance_time,
MAX((CASE WHEN lower(t666.task_key_new_)='verifyinsurance' THEN t666.auditor_ ELSE NULL END)) verifyinsurance_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='verifyinsurance' THEN t666.auditor_name_ ELSE NULL END)) verifyinsurance_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='verifyinsurance' THEN t666.opinion_ ELSE NULL END))  verifyinsurance_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='verifyinsurance' THEN t666.status_name_ ELSE NULL END))  verifyinsurance_option_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanresult' THEN t666.complete_time_ ELSE NULL END)) agreeloanresult_time,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanresult' THEN t666.auditor_ ELSE NULL END)) agreeloanresult_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanresult' THEN t666.auditor_name_ ELSE NULL END)) agreeloanresult_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanresult' THEN t666.opinion_ ELSE NULL END))  agreeloanresult_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='agreeloanresult' THEN t666.status_name_ ELSE NULL END))   agreeloanresult_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='management_division' THEN t666.complete_time_ ELSE NULL END)) management_division_time,
MAX((CASE WHEN lower(t666.task_key_new_)='management_division' THEN t666.auditor_ ELSE NULL END)) management_division_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='management_division' THEN t666.auditor_name_ ELSE NULL END)) management_division_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='management_division' THEN t666.opinion_ ELSE NULL END))  management_division_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='management_division' THEN t666.status_name_ ELSE NULL END))   management_division_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='technology' THEN t666.complete_time_ ELSE NULL END)) technology_time,
MAX((CASE WHEN lower(t666.task_key_new_)='technology' THEN t666.auditor_ ELSE NULL END)) technology_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='technology' THEN t666.auditor_name_ ELSE NULL END)) technology_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='technology' THEN t666.opinion_ ELSE NULL END))  technology_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='technology' THEN t666.status_name_ ELSE NULL END))   technology_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='manager_operation' THEN t666.complete_time_ ELSE NULL END)) manager_operation_time,
MAX((CASE WHEN lower(t666.task_key_new_)='manager_operation' THEN t666.auditor_ ELSE NULL END)) manager_operation_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='manager_operation' THEN t666.auditor_name_ ELSE NULL END)) manager_operation_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='manager_operation' THEN t666.opinion_ ELSE NULL END))  manager_operation_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='manager_operation' THEN t666.status_name_ ELSE NULL END))   manager_operation_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='operation_supervisor' THEN t666.complete_time_ ELSE NULL END)) operation_supervisor_time,
MAX((CASE WHEN lower(t666.task_key_new_)='operation_supervisor' THEN t666.auditor_ ELSE NULL END)) operation_supervisor_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='operation_supervisor' THEN t666.auditor_name_ ELSE NULL END)) operation_supervisor_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='operation_supervisor' THEN t666.opinion_ ELSE NULL END))  operation_supervisor_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='operation_supervisor' THEN t666.status_name_ ELSE NULL END))   operation_supervisor_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='riskmanager' THEN t666.complete_time_ ELSE NULL END)) riskmanager_time,
MAX((CASE WHEN lower(t666.task_key_new_)='riskmanager' THEN t666.auditor_ ELSE NULL END)) riskmanager_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='riskmanager' THEN t666.auditor_name_ ELSE NULL END)) riskmanager_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='riskmanager' THEN t666.opinion_ ELSE NULL END))  riskmanager_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='riskmanager' THEN t666.status_name_ ELSE NULL END))   riskmanager_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation' THEN t666.complete_time_ ELSE NULL END)) centralized_operation_time,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation' THEN t666.auditor_ ELSE NULL END)) centralized_operation_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation' THEN t666.auditor_name_ ELSE NULL END)) centralized_operation_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation' THEN t666.opinion_ ELSE NULL END))  centralized_operation_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation' THEN t666.status_name_ ELSE NULL END))   centralized_operation_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation_manager' THEN t666.complete_time_ ELSE NULL END)) centralized_operation_manager_time,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation_manager' THEN t666.auditor_ ELSE NULL END)) centralized_operation_manager_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation_manager' THEN t666.auditor_name_ ELSE NULL END)) centralized_operation_manager_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation_manager' THEN t666.opinion_ ELSE NULL END))  centralized_operation_manager_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='centralized_operation_manager' THEN t666.status_name_ ELSE NULL END))   centralized_operation_manager_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='marketing_supervisor' THEN t666.complete_time_ ELSE NULL END)) marketing_supervisor_time,
MAX((CASE WHEN lower(t666.task_key_new_)='marketing_supervisor' THEN t666.auditor_ ELSE NULL END)) marketing_supervisor_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='marketing_supervisor' THEN t666.auditor_name_ ELSE NULL END)) marketing_supervisor_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='marketing_supervisor' THEN t666.opinion_ ELSE NULL END))  marketing_supervisor_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='marketing_supervisor' THEN t666.status_name_ ELSE NULL END))   marketing_supervisor_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='capitalduty' THEN t666.complete_time_ ELSE NULL END)) capitalduty_time,
MAX((CASE WHEN lower(t666.task_key_new_)='capitalduty' THEN t666.auditor_ ELSE NULL END)) capitalduty_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='capitalduty' THEN t666.auditor_name_ ELSE NULL END)) capitalduty_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='capitalduty' THEN t666.opinion_ ELSE NULL END))  capitalduty_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='capitalduty' THEN t666.status_name_ ELSE NULL END))   capitalduty_status_name_,
MAX((CASE WHEN lower(t666.task_key_new_)='sales_operation' THEN t666.complete_time_ ELSE NULL END)) sales_operation_time,
MAX((CASE WHEN lower(t666.task_key_new_)='sales_operation' THEN t666.auditor_ ELSE NULL END)) sales_operation_user_id,
MAX((CASE WHEN lower(t666.task_key_new_)='sales_operation' THEN t666.auditor_name_ ELSE NULL END)) sales_operation_user_name,
MAX((CASE WHEN lower(t666.task_key_new_)='sales_operation' THEN t666.opinion_ ELSE NULL END))  sales_operation_option_,
MAX((CASE WHEN lower(t666.task_key_new_)='sales_operation' THEN t666.status_name_ ELSE NULL END))   sales_operation_status_name_
from (select * from tmp_check_opinion_common_ex where rn1=1) t666 group by t666.PROC_INST_ID_) t666;
drop table if exists ods_bpms_bpms_bpm_check_opinion_flow_wx;
ALTER TABLE odstmp_bpms_bpms_bpm_check_opinion_flow_wx RENAME TO ods_bpms_bpms_bpm_check_opinion_flow_wx;