use ods;
drop table if  exists ods.odstmp_bpms_biz_order_matter_record_wx_common;
CREATE TABLE odstmp_bpms_biz_order_matter_record_wx_common (
product_name STRING,
product_type STRING comment '',
product_version STRING,
apply_no STRING,
transferApply_time timestamp comment '资金划拨申请时间' ,
transferApply_user_id STRING comment '资金划拨申请用户id' ,
transferApply_user_name STRING comment '资金划拨申请用户id' ,
ApplyOrder_time timestamp comment '业务申请时间' ,
ApplyOrder_user_id STRING comment '业务申请用户id' ,
ApplyOrder_user_name STRING comment '业务申请用户id' ,
FinalLoan_time timestamp comment '贷款上报终审时间' ,
FinalLoan_user_id STRING comment '贷款上报终审用户id' ,
FinalLoan_user_name STRING comment '贷款上报终审用户id' ,
DataInspection_time timestamp comment '资料齐全时间' ,
DataInspection_user_id STRING comment '资料齐全用户id' ,
DataInspection_user_name STRING comment '资料齐全用户id' ,
QueryArchive_time timestamp comment '查档时间' ,
QueryArchive_user_id STRING comment '查档用户id' ,
QueryArchive_user_name STRING comment '查档用户id' ,
HouseAppraisal_time timestamp comment '房产评估时间' ,
HouseAppraisal_user_id STRING comment '房产评估用户id' ,
HouseAppraisal_user_name STRING comment '房产评估用户id' ,
HouseInspection_time timestamp comment '查房时间' ,
HouseInspection_user_id STRING comment '查房用户id' ,
HouseInspection_user_name STRING comment '查房用户id' ,
CostMark_time timestamp comment '费用登记时间' ,
CostMark_user_id STRING comment '费用登记用户id' ,
CostMark_user_name STRING comment '费用登记用户id' ,
Interview_time timestamp comment '面签时间' ,
Interview_user_id STRING comment '面签用户id' ,
Interview_user_name STRING comment '面签用户id' ,
CostConfirm_time timestamp comment '缴费确认时间' ,
CostConfirm_user_id STRING comment '缴费确认用户id' ,
CostConfirm_user_name STRING comment '缴费确认用户id' ,
InputInfo_time timestamp comment '录入时间' ,
InputInfo_user_id STRING comment '录入用户id' ,
InputInfo_user_name STRING comment '录入用户id' ,
ApplyLoan_time timestamp comment '申请贷款时间' ,
ApplyLoan_user_id STRING comment '申请贷款用户id' ,
ApplyLoan_user_name STRING comment '申请贷款用户id' ,
TransferOut_time timestamp comment '过户出件时间' ,
TransferOut_user_id STRING comment '过户出件用户id' ,
TransferOut_user_name STRING comment '过户出件用户id' ,
TransferIn_time timestamp comment '过户递件时间' ,
TransferIn_user_id STRING comment '过户递件用户id' ,
TransferIn_user_name STRING comment '过户递件用户id' ,
AgreeLoanMark_time timestamp comment '同贷登记时间' ,
AgreeLoanMark_user_id STRING comment '同贷登记用户id' ,
AgreeLoanMark_user_name STRING comment '同贷登记用户id' ,
MortgageOut_time timestamp comment '抵押出件时间' ,
MortgageOut_user_id STRING comment '抵押出件用户id' ,
MortgageOut_user_name STRING comment '抵押出件用户id' ,
TransferMark_time timestamp comment '放款登记时间' ,
TransferMark_user_id STRING comment '放款登记用户id' ,
TransferMark_user_name STRING comment '放款登记用户id' ,
PreFile_time timestamp comment '归档时间' ,
PreFile_user_id STRING comment '归档用户id' ,
PreFile_user_name STRING comment '归档用户id' ,
TrustAccount_time timestamp comment '要件托管时间' ,
TrustAccount_user_id STRING comment '要件托管用户id' ,
TrustAccount_user_name STRING comment '要件托管用户id' ,
AccountTest_time timestamp comment '账户测试时间' ,
AccountTest_user_id STRING comment '账户测试用户id' ,
AccountTest_user_name STRING comment '账户测试用户id' ,
PreRandom_time timestamp comment '预约赎楼时间' ,
PreRandom_user_id STRING comment '预约赎楼用户id' ,
PreRandom_user_name STRING comment '预约赎楼用户id' ,
Notarization_time timestamp comment '办理公证时间' ,
Notarization_user_id STRING comment '办理公证用户id' ,
Notarization_user_name STRING comment '办理公证用户id' ,
CostItemMark_time timestamp comment '费项登记时间' ,
CostItemMark_user_id STRING comment '费项登记用户id' ,
CostItemMark_user_name STRING comment '费项登记用户id' ,
MortgagePass_time timestamp comment '抵押递件时间' ,
MortgagePass_user_id STRING comment '抵押递件用户id' ,
MortgagePass_user_name STRING comment '抵押递件用户id' ,
ApplyCheck_time timestamp comment '报审时间' ,
ApplyCheck_user_id STRING comment '报审用户id' ,
ApplyCheck_user_name STRING comment '报审用户id' ,
CheckMarPush_time timestamp comment '审批资料推送时间' ,
CheckMarPush_user_id STRING comment '审批资料推送用户id' ,
CheckMarPush_user_name STRING comment '审批资料推送用户id' ,
ManCheck_time timestamp comment '人工审批时间' ,
ManCheck_user_id STRING comment '人工审批用户id' ,
ManCheck_user_name STRING comment '人工审批用户id' ,
CheckMarSend_time timestamp comment '审批资料外传时间' ,
CheckMarSend_user_id STRING comment '审批资料外传用户id' ,
CheckMarSend_user_name STRING comment '审批资料外传用户id' ,
fundsArrival_time timestamp comment '确认资金到账时间' ,
fundsArrival_user_id STRING comment '确认资金到账用户id' ,
fundsArrival_user_name STRING comment '确认资金到账用户id' ,
CheckResEnsure_time timestamp comment '审批结果确定时间' ,
CheckResEnsure_user_id STRING comment '审批结果确定用户id' ,
CheckResEnsure_user_name STRING comment '审批结果确定用户id' ,
PushLoanCommand_time timestamp comment '放款指令推送时间' ,
PushLoanCommand_user_id STRING comment '放款指令推送用户id' ,
PushLoanCommand_user_name STRING comment '放款指令推送用户id' ,
platformArrival_time timestamp comment '确认平台款到账时间' ,
platformArrival_user_id STRING comment '确认平台款到账用户id' ,
platformArrival_user_name STRING comment '确认平台款到账用户id' ,
transferConfirm_time timestamp comment '资金划拨确认时间' ,
transferConfirm_user_id STRING comment '资金划拨确认用户id' ,
transferConfirm_user_name STRING comment '资金划拨确认用户id' ,
RandomMark_time timestamp comment '赎楼登记时间' ,
RandomMark_user_id STRING comment '赎楼登记用户id' ,
RandomMark_user_name STRING comment '赎楼登记用户id' ,
RandomCashBack_time timestamp comment '赎楼资金划回时间' ,
RandomCashBack_user_id STRING comment '赎楼资金划回用户id' ,
RandomCashBack_user_name STRING comment '赎楼资金划回用户id' ,
paymentArrival_time timestamp comment '确认回款资金到账时间' ,
paymentArrival_user_id STRING comment '确认回款资金到账用户id' ,
paymentArrival_user_name STRING comment '确认回款资金到账用户id' ,
SendLoanCommand_time timestamp comment '发送放款指令时间' ,
SendLoanCommand_user_id STRING comment '发送放款指令用户id' ,
SendLoanCommand_user_name STRING comment '发送放款指令用户id' ,
SendLoanCommand_option STRING comment '发送放款指令意见',
SendLoanCommand_status_name STRING comment '发送放款指令状态',
SubmitVerifyApply_time timestamp comment '提交核保申请时间' ,
SubmitVerifyApply_user_id STRING comment '提交核保申请用户id' ,
SubmitVerifyApply_user_name STRING comment '提交核保申请用户id' ,
floorAdvance_time timestamp comment '赎楼前垫资回款时间' ,
floorAdvance_user_id STRING comment '赎楼前垫资回款用户id' ,
floorAdvance_user_name STRING comment '赎楼前垫资回款用户id' ,
SendVerifyMaterial_time timestamp comment '核保资料外传时间' ,
SendVerifyMaterial_user_id STRING comment '核保资料外传用户id' ,
SendVerifyMaterial_user_name STRING comment '核保资料外传用户id' ,
returnApply_time timestamp comment '资金归还申请时间' ,
returnApply_user_id STRING comment '资金归还申请用户id' ,
returnApply_user_name STRING comment '资金归还申请用户id' ,
returnConfirm_time timestamp comment '资金归还确认时间' ,
returnConfirm_user_id STRING comment '资金归还确认用户id' ,
returnConfirm_user_name STRING comment '资金归还确认用户id' ,
returnConfirm_option STRING comment '资金归还确认意见',
returnconfirm_status_name STRING comment '资金归还确认状态',
GetCancelMaterial_time timestamp comment '领取注销资料时间' ,
GetCancelMaterial_user_id STRING comment '领取注销资料用户id' ,
GetCancelMaterial_user_name STRING comment '领取注销资料用户id' ,
CancleMortgage_time timestamp comment '注销抵押时间' ,
CancleMortgage_user_id STRING comment '注销抵押用户id' ,
CancleMortgage_user_name STRING comment '注销抵押用户id' ,
InsuranceInfoConfirm_time timestamp comment '保单信息确认时间' ,
InsuranceInfoConfirm_user_id STRING comment '保单信息确认用户id' ,
InsuranceInfoConfirm_user_name STRING comment '保单信息确认用户id' ,
SendLoanReleseCommand_time timestamp comment '发送款项释放指令时间' ,
SendLoanReleseCommand_user_id STRING comment '发送款项释放指令用户id' ,
SendLoanReleseCommand_user_name STRING comment '发送款项释放指令用户id' ,
OverInsurance_time timestamp comment '解保时间' ,
OverInsurance_user_id STRING comment '解保用户id' ,
OverInsurance_user_name STRING comment '解保用户id' ,
custPayment_time timestamp comment '确认客户回款时间' ,
custPayment_user_id STRING comment '确认客户回款用户id' ,
custPayment_user_name STRING comment '确认客户回款用户id' ,
MortgagePass_zz_time timestamp comment '抵押递件_郑州时间' ,
MortgagePass_zz_user_id STRING comment '抵押递件_郑州用户id' ,
MortgagePass_zz_user_name STRING comment '抵押递件_郑州用户id' ,
MortgageOut_zz_time timestamp comment '抵押出件_郑州时间' ,
MortgageOut_zz_user_id STRING comment '抵押出件_郑州用户id' ,
MortgageOut_zz_user_name STRING comment '抵押出件_郑州用户id' ,
CancleMortgage_zz_time timestamp comment '注销抵押_郑州时间' ,
CancleMortgage_zz_user_id STRING comment '注销抵押_郑州用户id' ,
CancleMortgage_zz_user_name STRING comment '注销抵押_郑州用户id' ,
TransferOut_zz_time timestamp comment '过户出件_郑州时间' ,
TransferOut_zz_user_id STRING comment '过户出件_郑州用户id' ,
TransferOut_zz_user_name STRING comment '过户出件_郑州用户id' ,
TransferIn_zz_time timestamp comment '过户递件_郑州时间' ,
TransferIn_zz_user_id STRING comment '过户递件_郑州用户id' ,
TransferIn_zz_user_name STRING comment '过户递件_郑州用户id' ,
Investigate_time timestamp comment '审查时间' ,
Investigate_user_id STRING comment '审查用户id' ,
Investigate_user_name STRING comment '审查用户id' ,
PolicyApply_time timestamp comment '出保单申请时间' ,
PolicyApply_user_id STRING comment '出保单申请用户id' ,
PolicyApply_user_name STRING comment '出保单申请用户id' ,
CreditConfirm_time timestamp comment '征信确认时间' ,
CreditConfirm_user_id STRING comment '征信确认用户id' ,
CreditConfirm_user_name STRING comment '征信确认用户id' ,
ApprovalResult_time timestamp comment '审批结果确认时间' ,
ApprovalResult_user_id STRING comment '审批结果确认用户id' ,
ApprovalResult_user_name STRING comment '审批结果确认用户id' ,
InputInfoComplete_time timestamp comment '录入完成时间' ,
InputInfoComplete_user_id STRING comment '录入完成用户id' ,
InputInfoComplete_user_name STRING comment '录入完成用户id' ,
PushOutCommand_time timestamp comment '外传指令推送时间' ,
PushOutCommand_user_id STRING comment '外传指令推送用户id' ,
PushOutCommand_user_name STRING comment '外传指令推送用户id' ,
UploadImg_time timestamp comment '资料反馈时间' ,
UploadImg_user_id STRING comment '资料反馈用户id' ,
UploadImg_user_name STRING comment '资料反馈用户id' ,
ConfirmArrival_time timestamp comment '确认资金到账时间' ,
ConfirmArrival_user_id STRING comment '确认资金到账用户id' ,
ConfirmArrival_user_name STRING comment '确认资金到账用户id' ,
HouseholdApprove_time timestamp comment '下户审批时间' ,
HouseholdApprove_user_id STRING comment '下户审批用户id' ,
HouseholdApprove_user_name STRING comment '下户审批用户id' ,
financialArchiveEvent_time timestamp comment '财务归档时间' ,
financialArchiveEvent_user_id STRING comment '财务归档用户id' ,
financialArchiveEvent_user_name STRING comment '财务归档用户id' ,
billCheck_time timestamp comment '出账前审查时间' ,
billCheck_user_id STRING comment '出账前审查用户id' ,
billCheck_user_name STRING comment '出账前审查用户id' ,
HouseholdSurvey_time timestamp comment '下户调查时间' ,
HouseholdSurvey_user_id STRING comment '下户调查用户id' ,
HouseholdSurvey_user_name STRING comment '下户调查用户id' ,
TransferTail_time timestamp comment '尾款划拨申请时间' ,
TransferTail_user_id STRING comment '尾款划拨申请用户id' ,
TransferTail_user_name STRING comment '尾款划拨申请用户id' ,
ConfirmTailArrial_time timestamp comment '确认资金到账（尾款）时间' ,
ConfirmTailArrial_user_id STRING comment '确认资金到账（尾款）用户id' ,
ConfirmTailArrial_user_name STRING comment '确认资金到账（尾款）用户id' ,
ApplyLoan_atone_time timestamp comment '申请贷款(赎楼贷款)时间' ,
ApplyLoan_atone_user_id STRING comment '申请贷款(赎楼贷款)用户id' ,
ApplyLoan_atone_user_name STRING comment '申请贷款(赎楼贷款)用户id' ,
AgreeLoanMark_atone_time timestamp comment '同贷信息登记(赎楼贷款)时间' ,
AgreeLoanMark_atone_user_id STRING comment '同贷信息登记(赎楼贷款)用户id' ,
AgreeLoanMark_atone_user_name STRING comment '同贷信息登记(赎楼贷款)用户id' ,
internalTurnFunds_time timestamp comment '内部转款-归还时间' ,
internalTurnFunds_user_id STRING comment '内部转款-归还用户id' ,
internalTurnFunds_user_name STRING comment '内部转款-归还用户id' ,
RandomReback_time timestamp comment '赎楼资金划回时间' ,
RandomReback_user_id STRING comment '赎楼资金划回用户id' ,
RandomReback_user_name STRING comment '赎楼资金划回用户id' ,
ConfirmTransferTail_time timestamp comment '尾款划拨确认时间' ,
ConfirmTransferTail_user_id STRING comment '尾款划拨确认用户id' ,
ConfirmTransferTail_user_name STRING comment '尾款划拨确认用户id' ,
repaymentConfirm_time timestamp comment '还款确认时间' ,
repaymentConfirm_user_id STRING comment '还款确认用户id' ,
repaymentConfirm_user_name STRING comment '还款确认用户id' ,
PATCH_DS_time timestamp comment '大数补件时间' ,
PATCH_DS_user_id STRING comment '大数补件用户id' ,
PATCH_DS_user_name STRING comment '大数补件用户id' ,
AppointInterview_time timestamp comment '预约面签时间' ,
AppointInterview_user_id STRING comment '预约面签用户id' ,
AppointInterview_user_name STRING comment '预约面签用户id' ,
VerifyInsurance_time timestamp comment '核保时间' ,
VerifyInsurance_user_id STRING comment '核保用户id' ,
VerifyInsurance_user_name STRING comment '核保用户id' ,
Other_time timestamp comment '其他时间' ,
Other_user_id STRING comment '其他用户id' ,
Other_user_name STRING comment '其他用户id' ,
principalTransfer_time timestamp comment '本息划拨申请时间' ,
principalTransfer_user_id STRING comment '本息划拨申请用户id' ,
principalTransfer_user_name STRING comment '本息划拨申请用户id' ,
principalTransferConfirm_time timestamp comment '本息划拨确认时间' ,
principalTransferConfirm_user_id STRING comment '本息划拨确认用户id' ,
principalTransferConfirm_user_name STRING comment '本息划拨确认用户id' ,
custReceivableConfirm_time timestamp comment '客户回款确认时间' ,
custReceivableConfirm_user_id STRING comment '客户回款确认用户id' ,
custReceivableConfirm_user_name STRING comment '客户回款确认用户id'
)stored as parquet;
with tmp_matter_record_common as (
  select *, ROW_NUMBER() OVER(PARTITION BY apply_no,matter_name_new ORDER BY handle_time desc) rn1
 from (select * from ods.ods_bpms_biz_order_matter_record_common where apply_no is not null
 and (`status_` is NULL or `status_`<>'manual_end') and handle_time is not null )t
)
insert overwrite table odstmp_bpms_biz_order_matter_record_wx_common
select
a.product_name,
a.product_type,
a.product_version,
b.* from ods_bpms_biz_apply_order_common a left join (
select apply_no,
MAX((CASE WHEN lower(t2.matter_key)='transferapply'  THEN t2.handle_time ELSE NULL END))  transferapply_time,
MAX((CASE WHEN lower(t2.matter_key)='transferapply'  THEN t2.handle_user_id ELSE NULL END))  transferapply_user_id,
MAX((CASE WHEN lower(t2.matter_key)='transferapply'  THEN t2.handle_user_name ELSE NULL END))  transferapply_user_name,
MAX((CASE WHEN lower(t2.matter_key)='applyorder'  THEN t2.handle_time ELSE NULL END))  applyorder_time,
MAX((CASE WHEN lower(t2.matter_key)='applyorder'  THEN t2.handle_user_id ELSE NULL END))  applyorder_user_id,
MAX((CASE WHEN lower(t2.matter_key)='applyorder'  THEN t2.handle_user_name ELSE NULL END))  applyorder_user_name,
MAX((CASE WHEN lower(t2.matter_key)='finalloan'  THEN t2.handle_time ELSE NULL END))  finalloan_time,
MAX((CASE WHEN lower(t2.matter_key)='finalloan'  THEN t2.handle_user_id ELSE NULL END))  finalloan_user_id,
MAX((CASE WHEN lower(t2.matter_key)='finalloan'  THEN t2.handle_user_name ELSE NULL END))  finalloan_user_name,
MAX((CASE WHEN lower(t2.matter_key)='datainspection'  THEN t2.handle_time ELSE NULL END))  datainspection_time,
MAX((CASE WHEN lower(t2.matter_key)='datainspection'  THEN t2.handle_user_id ELSE NULL END))  datainspection_user_id,
MAX((CASE WHEN lower(t2.matter_key)='datainspection'  THEN t2.handle_user_name ELSE NULL END))  datainspection_user_name,
MAX((CASE WHEN lower(t2.matter_key)='queryarchive'  THEN t2.handle_time ELSE NULL END))  queryarchive_time,
MAX((CASE WHEN lower(t2.matter_key)='queryarchive'  THEN t2.handle_user_id ELSE NULL END))  queryarchive_user_id,
MAX((CASE WHEN lower(t2.matter_key)='queryarchive'  THEN t2.handle_user_name ELSE NULL END))  queryarchive_user_name,
MAX((CASE WHEN lower(t2.matter_key)='houseappraisal'  THEN t2.handle_time ELSE NULL END))  houseappraisal_time,
MAX((CASE WHEN lower(t2.matter_key)='houseappraisal'  THEN t2.handle_user_id ELSE NULL END))  houseappraisal_user_id,
MAX((CASE WHEN lower(t2.matter_key)='houseappraisal'  THEN t2.handle_user_name ELSE NULL END))  houseappraisal_user_name,
MAX((CASE WHEN lower(t2.matter_key)='houseinspection'  THEN t2.handle_time ELSE NULL END))  houseinspection_time,
MAX((CASE WHEN lower(t2.matter_key)='houseinspection'  THEN t2.handle_user_id ELSE NULL END))  houseinspection_user_id,
MAX((CASE WHEN lower(t2.matter_key)='houseinspection'  THEN t2.handle_user_name ELSE NULL END))  houseinspection_user_name,
MAX((CASE WHEN lower(t2.matter_key)='costmark'  THEN t2.handle_time ELSE NULL END))  costmark_time,
MAX((CASE WHEN lower(t2.matter_key)='costmark'  THEN t2.handle_user_id ELSE NULL END))  costmark_user_id,
MAX((CASE WHEN lower(t2.matter_key)='costmark'  THEN t2.handle_user_name ELSE NULL END))  costmark_user_name,
MAX((CASE WHEN lower(t2.matter_key)='interview'  THEN t2.handle_time ELSE NULL END))  interview_time,
MAX((CASE WHEN lower(t2.matter_key)='interview'  THEN t2.handle_user_id ELSE NULL END))  interview_user_id,
MAX((CASE WHEN lower(t2.matter_key)='interview'  THEN t2.handle_user_name ELSE NULL END))  interview_user_name,
MAX((CASE WHEN lower(t2.matter_key)='costconfirm'  THEN t2.handle_time ELSE NULL END))  costconfirm_time,
MAX((CASE WHEN lower(t2.matter_key)='costconfirm'  THEN t2.handle_user_id ELSE NULL END))  costconfirm_user_id,
MAX((CASE WHEN lower(t2.matter_key)='costconfirm'  THEN t2.handle_user_name ELSE NULL END))  costconfirm_user_name,
MAX((CASE WHEN lower(t2.matter_key)='inputinfo'  THEN t2.handle_time ELSE NULL END))  inputinfo_time,
MAX((CASE WHEN lower(t2.matter_key)='inputinfo'  THEN t2.handle_user_id ELSE NULL END))  inputinfo_user_id,
MAX((CASE WHEN lower(t2.matter_key)='inputinfo'  THEN t2.handle_user_name ELSE NULL END))  inputinfo_user_name,
MAX((CASE WHEN lower(t2.matter_key)='applyloan'  THEN t2.handle_time ELSE NULL END))  applyloan_time,
MAX((CASE WHEN lower(t2.matter_key)='applyloan'  THEN t2.handle_user_id ELSE NULL END))  applyloan_user_id,
MAX((CASE WHEN lower(t2.matter_key)='applyloan'  THEN t2.handle_user_name ELSE NULL END))  applyloan_user_name,
MAX((CASE WHEN lower(t2.matter_key)='transferout'  THEN t2.handle_time ELSE NULL END))  transferout_time,
MAX((CASE WHEN lower(t2.matter_key)='transferout'  THEN t2.handle_user_id ELSE NULL END))  transferout_user_id,
MAX((CASE WHEN lower(t2.matter_key)='transferout'  THEN t2.handle_user_name ELSE NULL END))  transferout_user_name,
MAX((CASE WHEN lower(t2.matter_key)='transferin'  THEN t2.handle_time ELSE NULL END))  transferin_time,
MAX((CASE WHEN lower(t2.matter_key)='transferin'  THEN t2.handle_user_id ELSE NULL END))  transferin_user_id,
MAX((CASE WHEN lower(t2.matter_key)='transferin'  THEN t2.handle_user_name ELSE NULL END))  transferin_user_name,
MAX((CASE WHEN lower(t2.matter_key)='agreeloanmark'  THEN t2.handle_time ELSE NULL END))  agreeloanmark_time,
MAX((CASE WHEN lower(t2.matter_key)='agreeloanmark'  THEN t2.handle_user_id ELSE NULL END))  agreeloanmark_user_id,
MAX((CASE WHEN lower(t2.matter_key)='agreeloanmark'  THEN t2.handle_user_name ELSE NULL END))  agreeloanmark_user_name,
MAX((CASE WHEN lower(t2.matter_key)='mortgageout'  THEN t2.handle_time ELSE NULL END))  mortgageout_time,
MAX((CASE WHEN lower(t2.matter_key)='mortgageout'  THEN t2.handle_user_id ELSE NULL END))  mortgageout_user_id,
MAX((CASE WHEN lower(t2.matter_key)='mortgageout'  THEN t2.handle_user_name ELSE NULL END))  mortgageout_user_name,
MAX((CASE WHEN lower(t2.matter_key)='transfermark'  THEN t2.handle_time ELSE NULL END))  transfermark_time,
MAX((CASE WHEN lower(t2.matter_key)='transfermark'  THEN t2.handle_user_id ELSE NULL END))  transfermark_user_id,
MAX((CASE WHEN lower(t2.matter_key)='transfermark'  THEN t2.handle_user_name ELSE NULL END))  transfermark_user_name,
MAX((CASE WHEN lower(t2.matter_key)='prefile'  THEN t2.handle_time ELSE NULL END))  prefile_time,
MAX((CASE WHEN lower(t2.matter_key)='prefile'  THEN t2.handle_user_id ELSE NULL END))  prefile_user_id,
MAX((CASE WHEN lower(t2.matter_key)='prefile'  THEN t2.handle_user_name ELSE NULL END))  prefile_user_name,
MAX((CASE WHEN lower(t2.matter_key)='trustaccount'  THEN t2.handle_time ELSE NULL END))  trustaccount_time,
MAX((CASE WHEN lower(t2.matter_key)='trustaccount'  THEN t2.handle_user_id ELSE NULL END))  trustaccount_user_id,
MAX((CASE WHEN lower(t2.matter_key)='trustaccount'  THEN t2.handle_user_name ELSE NULL END))  trustaccount_user_name,
MAX((CASE WHEN lower(t2.matter_key)='accounttest'  THEN t2.handle_time ELSE NULL END))  accounttest_time,
MAX((CASE WHEN lower(t2.matter_key)='accounttest'  THEN t2.handle_user_id ELSE NULL END))  accounttest_user_id,
MAX((CASE WHEN lower(t2.matter_key)='accounttest'  THEN t2.handle_user_name ELSE NULL END))  accounttest_user_name,
MAX((CASE WHEN lower(t2.matter_key)='prerandom'  THEN t2.handle_time ELSE NULL END))  prerandom_time,
MAX((CASE WHEN lower(t2.matter_key)='prerandom'  THEN t2.handle_user_id ELSE NULL END))  prerandom_user_id,
MAX((CASE WHEN lower(t2.matter_key)='prerandom'  THEN t2.handle_user_name ELSE NULL END))  prerandom_user_name,
MAX((CASE WHEN lower(t2.matter_key)='notarization'  THEN t2.handle_time ELSE NULL END))  notarization_time,
MAX((CASE WHEN lower(t2.matter_key)='notarization'  THEN t2.handle_user_id ELSE NULL END))  notarization_user_id,
MAX((CASE WHEN lower(t2.matter_key)='notarization'  THEN t2.handle_user_name ELSE NULL END))  notarization_user_name,
MAX((CASE WHEN lower(t2.matter_key)='costitemmark'  THEN t2.handle_time ELSE NULL END))  costitemmark_time,
MAX((CASE WHEN lower(t2.matter_key)='costitemmark'  THEN t2.handle_user_id ELSE NULL END))  costitemmark_user_id,
MAX((CASE WHEN lower(t2.matter_key)='costitemmark'  THEN t2.handle_user_name ELSE NULL END))  costitemmark_user_name,
MAX((CASE WHEN lower(t2.matter_key)='mortgagepass'  THEN t2.handle_time ELSE NULL END))  mortgagepass_time,
MAX((CASE WHEN lower(t2.matter_key)='mortgagepass'  THEN t2.handle_user_id ELSE NULL END))  mortgagepass_user_id,
MAX((CASE WHEN lower(t2.matter_key)='mortgagepass'  THEN t2.handle_user_name ELSE NULL END))  mortgagepass_user_name,
MAX((CASE WHEN lower(t2.matter_key)='applycheck'  THEN t2.handle_time ELSE NULL END))  applycheck_time,
MAX((CASE WHEN lower(t2.matter_key)='applycheck'  THEN t2.handle_user_id ELSE NULL END))  applycheck_user_id,
MAX((CASE WHEN lower(t2.matter_key)='applycheck'  THEN t2.handle_user_name ELSE NULL END))  applycheck_user_name,
MAX((CASE WHEN lower(t2.matter_key)='checkmarpush'  THEN t2.handle_time ELSE NULL END))  checkmarpush_time,
MAX((CASE WHEN lower(t2.matter_key)='checkmarpush'  THEN t2.handle_user_id ELSE NULL END))  checkmarpush_user_id,
MAX((CASE WHEN lower(t2.matter_key)='checkmarpush'  THEN t2.handle_user_name ELSE NULL END))  checkmarpush_user_name,
MAX((CASE WHEN lower(t2.matter_key)='mancheck'  THEN t2.handle_time ELSE NULL END))  mancheck_time,
MAX((CASE WHEN lower(t2.matter_key)='mancheck'  THEN t2.handle_user_id ELSE NULL END))  mancheck_user_id,
MAX((CASE WHEN lower(t2.matter_key)='mancheck'  THEN t2.handle_user_name ELSE NULL END))  mancheck_user_name,
MAX((CASE WHEN lower(t2.matter_key)='checkmarsend'  THEN t2.handle_time ELSE NULL END))  checkmarsend_time,
MAX((CASE WHEN lower(t2.matter_key)='checkmarsend'  THEN t2.handle_user_id ELSE NULL END))  checkmarsend_user_id,
MAX((CASE WHEN lower(t2.matter_key)='checkmarsend'  THEN t2.handle_user_name ELSE NULL END))  checkmarsend_user_name,
MAX((CASE WHEN lower(t2.matter_key)='fundsarrival'  THEN t2.handle_time ELSE NULL END))  fundsarrival_time,
MAX((CASE WHEN lower(t2.matter_key)='fundsarrival'  THEN t2.handle_user_id ELSE NULL END))  fundsarrival_user_id,
MAX((CASE WHEN lower(t2.matter_key)='fundsarrival'  THEN t2.handle_user_name ELSE NULL END))  fundsarrival_user_name,
MAX((CASE WHEN lower(t2.matter_key)='checkresensure'  THEN t2.handle_time ELSE NULL END))  checkresensure_time,
MAX((CASE WHEN lower(t2.matter_key)='checkresensure'  THEN t2.handle_user_id ELSE NULL END))  checkresensure_user_id,
MAX((CASE WHEN lower(t2.matter_key)='checkresensure'  THEN t2.handle_user_name ELSE NULL END))  checkresensure_user_name,
MAX((CASE WHEN lower(t2.matter_key)='pushloancommand'  THEN t2.handle_time ELSE NULL END))  pushloancommand_time,
MAX((CASE WHEN lower(t2.matter_key)='pushloancommand'  THEN t2.handle_user_id ELSE NULL END))  pushloancommand_user_id,
MAX((CASE WHEN lower(t2.matter_key)='pushloancommand'  THEN t2.handle_user_name ELSE NULL END))  pushloancommand_user_name,
MAX((CASE WHEN lower(t2.matter_key)='platformarrival'  THEN t2.handle_time ELSE NULL END))  platformarrival_time,
MAX((CASE WHEN lower(t2.matter_key)='platformarrival'  THEN t2.handle_user_id ELSE NULL END))  platformarrival_user_id,
MAX((CASE WHEN lower(t2.matter_key)='platformarrival'  THEN t2.handle_user_name ELSE NULL END))  platformarrival_user_name,
MAX((CASE WHEN lower(t2.matter_key)='transferconfirm'  THEN t2.handle_time ELSE NULL END))  transferconfirm_time,
MAX((CASE WHEN lower(t2.matter_key)='transferconfirm'  THEN t2.handle_user_id ELSE NULL END))  transferconfirm_user_id,
MAX((CASE WHEN lower(t2.matter_key)='transferconfirm'  THEN t2.handle_user_name ELSE NULL END))  transferconfirm_user_name,
MAX((CASE WHEN lower(t2.matter_key)='randommark'  THEN t2.handle_time ELSE NULL END))  randommark_time,
MAX((CASE WHEN lower(t2.matter_key)='randommark'  THEN t2.handle_user_id ELSE NULL END))  randommark_user_id,
MAX((CASE WHEN lower(t2.matter_key)='randommark'  THEN t2.handle_user_name ELSE NULL END))  randommark_user_name,
MAX((CASE WHEN lower(t2.matter_key)='randomcashback'  THEN t2.handle_time ELSE NULL END))  randomcashback_time,
MAX((CASE WHEN lower(t2.matter_key)='randomcashback'  THEN t2.handle_user_id ELSE NULL END))  randomcashback_user_id,
MAX((CASE WHEN lower(t2.matter_key)='randomcashback'  THEN t2.handle_user_name ELSE NULL END))  randomcashback_user_name,
MAX((CASE WHEN lower(t2.matter_key)='paymentarrival'  THEN t2.handle_time ELSE NULL END))  paymentarrival_time,
MAX((CASE WHEN lower(t2.matter_key)='paymentarrival'  THEN t2.handle_user_id ELSE NULL END))  paymentarrival_user_id,
MAX((CASE WHEN lower(t2.matter_key)='paymentarrival'  THEN t2.handle_user_name ELSE NULL END))  paymentarrival_user_name,
MAX((CASE WHEN lower(t2.matter_key)='sendloancommand'  THEN t2.handle_time ELSE NULL END))  sendloancommand_time,
MAX((CASE WHEN lower(t2.matter_key)='sendloancommand'  THEN t2.handle_user_id ELSE NULL END))  sendloancommand_user_id,
MAX((CASE WHEN lower(t2.matter_key)='sendloancommand'  THEN t2.handle_user_name ELSE NULL END))  sendloancommand_user_name,
MAX((CASE WHEN lower(t2.matter_key)='sendloancommand'  THEN t2.remark ELSE NULL END))  sendloancommand_option,
MAX((CASE WHEN lower(t2.matter_key)='sendloancommand'  THEN t2.status_name_option ELSE NULL END))  sendloancommand_status_name,
MAX((CASE WHEN lower(t2.matter_key)='submitverifyapply'  THEN t2.handle_time ELSE NULL END))  submitverifyapply_time,
MAX((CASE WHEN lower(t2.matter_key)='submitverifyapply'  THEN t2.handle_user_id ELSE NULL END))  submitverifyapply_user_id,
MAX((CASE WHEN lower(t2.matter_key)='submitverifyapply'  THEN t2.handle_user_name ELSE NULL END))  submitverifyapply_user_name,
MAX((CASE WHEN lower(t2.matter_key)='flooradvance'  THEN t2.handle_time ELSE NULL END))  flooradvance_time,
MAX((CASE WHEN lower(t2.matter_key)='flooradvance'  THEN t2.handle_user_id ELSE NULL END))  flooradvance_user_id,
MAX((CASE WHEN lower(t2.matter_key)='flooradvance'  THEN t2.handle_user_name ELSE NULL END))  flooradvance_user_name,
MAX((CASE WHEN lower(t2.matter_key)='sendverifymaterial'  THEN t2.handle_time ELSE NULL END))  sendverifymaterial_time,
MAX((CASE WHEN lower(t2.matter_key)='sendverifymaterial'  THEN t2.handle_user_id ELSE NULL END))  sendverifymaterial_user_id,
MAX((CASE WHEN lower(t2.matter_key)='sendverifymaterial'  THEN t2.handle_user_name ELSE NULL END))  sendverifymaterial_user_name,
MAX((CASE WHEN lower(t2.matter_key)='returnapply'  THEN t2.handle_time ELSE NULL END))  returnapply_time,
MAX((CASE WHEN lower(t2.matter_key)='returnapply'  THEN t2.handle_user_id ELSE NULL END))  returnapply_user_id,
MAX((CASE WHEN lower(t2.matter_key)='returnapply'  THEN t2.handle_user_name ELSE NULL END))  returnapply_user_name,
MAX((CASE WHEN lower(t2.matter_key)='returnconfirm'  THEN t2.handle_time ELSE NULL END))  returnconfirm_time,
MAX((CASE WHEN lower(t2.matter_key)='returnconfirm'  THEN t2.handle_user_id ELSE NULL END))  returnconfirm_user_id,
MAX((CASE WHEN lower(t2.matter_key)='returnconfirm'  THEN t2.handle_user_name ELSE NULL END))  returnconfirm_user_name,
MAX((CASE WHEN lower(t2.matter_key)='returnconfirm'  THEN t2.remark ELSE NULL END))  returnconfirm_option,
MAX((CASE WHEN lower(t2.matter_key)='returnconfirm'  THEN t2.status_name_option ELSE NULL END))  returnconfirm_status_name,
MAX((CASE WHEN lower(t2.matter_key)='getcancelmaterial'  THEN t2.handle_time ELSE NULL END))  getcancelmaterial_time,
MAX((CASE WHEN lower(t2.matter_key)='getcancelmaterial'  THEN t2.handle_user_id ELSE NULL END))  getcancelmaterial_user_id,
MAX((CASE WHEN lower(t2.matter_key)='getcancelmaterial'  THEN t2.handle_user_name ELSE NULL END))  getcancelmaterial_user_name,
MAX((CASE WHEN lower(t2.matter_key)='canclemortgage'  THEN t2.handle_time ELSE NULL END))  canclemortgage_time,
MAX((CASE WHEN lower(t2.matter_key)='canclemortgage'  THEN t2.handle_user_id ELSE NULL END))  canclemortgage_user_id,
MAX((CASE WHEN lower(t2.matter_key)='canclemortgage'  THEN t2.handle_user_name ELSE NULL END))  canclemortgage_user_name,
MAX((CASE WHEN lower(t2.matter_key)='insuranceinfoconfirm'  THEN t2.handle_time ELSE NULL END))  insuranceinfoconfirm_time,
MAX((CASE WHEN lower(t2.matter_key)='insuranceinfoconfirm'  THEN t2.handle_user_id ELSE NULL END))  insuranceinfoconfirm_user_id,
MAX((CASE WHEN lower(t2.matter_key)='insuranceinfoconfirm'  THEN t2.handle_user_name ELSE NULL END))  insuranceinfoconfirm_user_name,
MAX((CASE WHEN lower(t2.matter_key)='sendloanrelesecommand'  THEN t2.handle_time ELSE NULL END))  sendloanrelesecommand_time,
MAX((CASE WHEN lower(t2.matter_key)='sendloanrelesecommand'  THEN t2.handle_user_id ELSE NULL END))  sendloanrelesecommand_user_id,
MAX((CASE WHEN lower(t2.matter_key)='sendloanrelesecommand'  THEN t2.handle_user_name ELSE NULL END))  sendloanrelesecommand_user_name,
MAX((CASE WHEN lower(t2.matter_key)='overinsurance'  THEN t2.handle_time ELSE NULL END))  overinsurance_time,
MAX((CASE WHEN lower(t2.matter_key)='overinsurance'  THEN t2.handle_user_id ELSE NULL END))  overinsurance_user_id,
MAX((CASE WHEN lower(t2.matter_key)='overinsurance'  THEN t2.handle_user_name ELSE NULL END))  overinsurance_user_name,
MAX((CASE WHEN lower(t2.matter_key)='custpayment'  THEN t2.handle_time ELSE NULL END))  custpayment_time,
MAX((CASE WHEN lower(t2.matter_key)='custpayment'  THEN t2.handle_user_id ELSE NULL END))  custpayment_user_id,
MAX((CASE WHEN lower(t2.matter_key)='custpayment'  THEN t2.handle_user_name ELSE NULL END))  custpayment_user_name,
MAX((CASE WHEN lower(t2.matter_key)='mortgagepass_zz'  THEN t2.handle_time ELSE NULL END))  mortgagepass_zz_time,
MAX((CASE WHEN lower(t2.matter_key)='mortgagepass_zz'  THEN t2.handle_user_id ELSE NULL END))  mortgagepass_zz_user_id,
MAX((CASE WHEN lower(t2.matter_key)='mortgagepass_zz'  THEN t2.handle_user_name ELSE NULL END))  mortgagepass_zz_user_name,
MAX((CASE WHEN lower(t2.matter_key)='mortgageout_zz'  THEN t2.handle_time ELSE NULL END))  mortgageout_zz_time,
MAX((CASE WHEN lower(t2.matter_key)='mortgageout_zz'  THEN t2.handle_user_id ELSE NULL END))  mortgageout_zz_user_id,
MAX((CASE WHEN lower(t2.matter_key)='mortgageout_zz'  THEN t2.handle_user_name ELSE NULL END))  mortgageout_zz_user_name,
MAX((CASE WHEN lower(t2.matter_key)='canclemortgage_zz'  THEN t2.handle_time ELSE NULL END))  canclemortgage_zz_time,
MAX((CASE WHEN lower(t2.matter_key)='canclemortgage_zz'  THEN t2.handle_user_id ELSE NULL END))  canclemortgage_zz_user_id,
MAX((CASE WHEN lower(t2.matter_key)='canclemortgage_zz'  THEN t2.handle_user_name ELSE NULL END))  canclemortgage_zz_user_name,
MAX((CASE WHEN lower(t2.matter_key)='transferout_zz'  THEN t2.handle_time ELSE NULL END))  transferout_zz_time,
MAX((CASE WHEN lower(t2.matter_key)='transferout_zz'  THEN t2.handle_user_id ELSE NULL END))  transferout_zz_user_id,
MAX((CASE WHEN lower(t2.matter_key)='transferout_zz'  THEN t2.handle_user_name ELSE NULL END))  transferout_zz_user_name,
MAX((CASE WHEN lower(t2.matter_key)='transferin_zz'  THEN t2.handle_time ELSE NULL END))  transferin_zz_time,
MAX((CASE WHEN lower(t2.matter_key)='transferin_zz'  THEN t2.handle_user_id ELSE NULL END))  transferin_zz_user_id,
MAX((CASE WHEN lower(t2.matter_key)='transferin_zz'  THEN t2.handle_user_name ELSE NULL END))  transferin_zz_user_name,
MAX((CASE WHEN lower(t2.matter_key)='investigate'  THEN t2.handle_time ELSE NULL END))  investigate_time,
MAX((CASE WHEN lower(t2.matter_key)='investigate'  THEN t2.handle_user_id ELSE NULL END))  investigate_user_id,
MAX((CASE WHEN lower(t2.matter_key)='investigate'  THEN t2.handle_user_name ELSE NULL END))  investigate_user_name,
MAX((CASE WHEN lower(t2.matter_key)='policyapply'  THEN t2.handle_time ELSE NULL END))  policyapply_time,
MAX((CASE WHEN lower(t2.matter_key)='policyapply'  THEN t2.handle_user_id ELSE NULL END))  policyapply_user_id,
MAX((CASE WHEN lower(t2.matter_key)='policyapply'  THEN t2.handle_user_name ELSE NULL END))  policyapply_user_name,
MAX((CASE WHEN lower(t2.matter_key)='creditconfirm'  THEN t2.handle_time ELSE NULL END))  creditconfirm_time,
MAX((CASE WHEN lower(t2.matter_key)='creditconfirm'  THEN t2.handle_user_id ELSE NULL END))  creditconfirm_user_id,
MAX((CASE WHEN lower(t2.matter_key)='creditconfirm'  THEN t2.handle_user_name ELSE NULL END))  creditconfirm_user_name,
MAX((CASE WHEN lower(t2.matter_key)='approvalresult'  THEN t2.handle_time ELSE NULL END))  approvalresult_time,
MAX((CASE WHEN lower(t2.matter_key)='approvalresult'  THEN t2.handle_user_id ELSE NULL END))  approvalresult_user_id,
MAX((CASE WHEN lower(t2.matter_key)='approvalresult'  THEN t2.handle_user_name ELSE NULL END))  approvalresult_user_name,
MAX((CASE WHEN lower(t2.matter_key)='inputinfocomplete'  THEN t2.handle_time ELSE NULL END))  inputinfocomplete_time,
MAX((CASE WHEN lower(t2.matter_key)='inputinfocomplete'  THEN t2.handle_user_id ELSE NULL END))  inputinfocomplete_user_id,
MAX((CASE WHEN lower(t2.matter_key)='inputinfocomplete'  THEN t2.handle_user_name ELSE NULL END))  inputinfocomplete_user_name,
MAX((CASE WHEN lower(t2.matter_key)='pushoutcommand'  THEN t2.handle_time ELSE NULL END))  pushoutcommand_time,
MAX((CASE WHEN lower(t2.matter_key)='pushoutcommand'  THEN t2.handle_user_id ELSE NULL END))  pushoutcommand_user_id,
MAX((CASE WHEN lower(t2.matter_key)='pushoutcommand'  THEN t2.handle_user_name ELSE NULL END))  pushoutcommand_user_name,
MAX((CASE WHEN lower(t2.matter_key)='uploadimg'  THEN t2.handle_time ELSE NULL END))  uploadimg_time,
MAX((CASE WHEN lower(t2.matter_key)='uploadimg'  THEN t2.handle_user_id ELSE NULL END))  uploadimg_user_id,
MAX((CASE WHEN lower(t2.matter_key)='uploadimg'  THEN t2.handle_user_name ELSE NULL END))  uploadimg_user_name,
MAX((CASE WHEN lower(t2.matter_key)='confirmarrival'  THEN t2.handle_time ELSE NULL END))  confirmarrival_time,
MAX((CASE WHEN lower(t2.matter_key)='confirmarrival'  THEN t2.handle_user_id ELSE NULL END))  confirmarrival_user_id,
MAX((CASE WHEN lower(t2.matter_key)='confirmarrival'  THEN t2.handle_user_name ELSE NULL END))  confirmarrival_user_name,
MAX((CASE WHEN lower(t2.matter_key)='householdapprove'  THEN t2.handle_time ELSE NULL END))  householdapprove_time,
MAX((CASE WHEN lower(t2.matter_key)='householdapprove'  THEN t2.handle_user_id ELSE NULL END))  householdapprove_user_id,
MAX((CASE WHEN lower(t2.matter_key)='householdapprove'  THEN t2.handle_user_name ELSE NULL END))  householdapprove_user_name,
MAX((CASE WHEN lower(t2.matter_key)='financialarchiveevent'  THEN t2.handle_time ELSE NULL END))  financialarchiveevent_time,
MAX((CASE WHEN lower(t2.matter_key)='financialarchiveevent'  THEN t2.handle_user_id ELSE NULL END))  financialarchiveevent_user_id,
MAX((CASE WHEN lower(t2.matter_key)='financialarchiveevent'  THEN t2.handle_user_name ELSE NULL END))  financialarchiveevent_user_name,
MAX((CASE WHEN lower(t2.matter_key)='billcheck'  THEN t2.handle_time ELSE NULL END))  billcheck_time,
MAX((CASE WHEN lower(t2.matter_key)='billcheck'  THEN t2.handle_user_id ELSE NULL END))  billcheck_user_id,
MAX((CASE WHEN lower(t2.matter_key)='billcheck'  THEN t2.handle_user_name ELSE NULL END))  billcheck_user_name,
MAX((CASE WHEN lower(t2.matter_key)='householdsurvey'  THEN t2.handle_time ELSE NULL END))  householdsurvey_time,
MAX((CASE WHEN lower(t2.matter_key)='householdsurvey'  THEN t2.handle_user_id ELSE NULL END))  householdsurvey_user_id,
MAX((CASE WHEN lower(t2.matter_key)='householdsurvey'  THEN t2.handle_user_name ELSE NULL END))  householdsurvey_user_name,
MAX((CASE WHEN lower(t2.matter_key)='transfertail'  THEN t2.handle_time ELSE NULL END))  transfertail_time,
MAX((CASE WHEN lower(t2.matter_key)='transfertail'  THEN t2.handle_user_id ELSE NULL END))  transfertail_user_id,
MAX((CASE WHEN lower(t2.matter_key)='transfertail'  THEN t2.handle_user_name ELSE NULL END))  transfertail_user_name,
MAX((CASE WHEN lower(t2.matter_key)='confirmtailarrial'  THEN t2.handle_time ELSE NULL END))  confirmtailarrial_time,
MAX((CASE WHEN lower(t2.matter_key)='confirmtailarrial'  THEN t2.handle_user_id ELSE NULL END))  confirmtailarrial_user_id,
MAX((CASE WHEN lower(t2.matter_key)='confirmtailarrial'  THEN t2.handle_user_name ELSE NULL END))  confirmtailarrial_user_name,
MAX((CASE WHEN lower(t2.matter_key)='applyloan_atone'  THEN t2.handle_time ELSE NULL END))  applyloan_atone_time,
MAX((CASE WHEN lower(t2.matter_key)='applyloan_atone'  THEN t2.handle_user_id ELSE NULL END))  applyloan_atone_user_id,
MAX((CASE WHEN lower(t2.matter_key)='applyloan_atone'  THEN t2.handle_user_name ELSE NULL END))  applyloan_atone_user_name,
MAX((CASE WHEN lower(t2.matter_key)='agreeloanmark_atone'  THEN t2.handle_time ELSE NULL END))  agreeloanmark_atone_time,
MAX((CASE WHEN lower(t2.matter_key)='agreeloanmark_atone'  THEN t2.handle_user_id ELSE NULL END))  agreeloanmark_atone_user_id,
MAX((CASE WHEN lower(t2.matter_key)='agreeloanmark_atone'  THEN t2.handle_user_name ELSE NULL END))  agreeloanmark_atone_user_name,
MAX((CASE WHEN lower(t2.matter_key)='internalturnfunds'  THEN t2.handle_time ELSE NULL END))  internalturnfunds_time,
MAX((CASE WHEN lower(t2.matter_key)='internalturnfunds'  THEN t2.handle_user_id ELSE NULL END))  internalturnfunds_user_id,
MAX((CASE WHEN lower(t2.matter_key)='internalturnfunds'  THEN t2.handle_user_name ELSE NULL END))  internalturnfunds_user_name,
MAX((CASE WHEN lower(t2.matter_key)='randomreback'  THEN t2.handle_time ELSE NULL END))  randomreback_time,
MAX((CASE WHEN lower(t2.matter_key)='randomreback'  THEN t2.handle_user_id ELSE NULL END))  randomreback_user_id,
MAX((CASE WHEN lower(t2.matter_key)='randomreback'  THEN t2.handle_user_name ELSE NULL END))  randomreback_user_name,
MAX((CASE WHEN lower(t2.matter_key)='confirmtransfertail'  THEN t2.handle_time ELSE NULL END))  confirmtransfertail_time,
MAX((CASE WHEN lower(t2.matter_key)='confirmtransfertail'  THEN t2.handle_user_id ELSE NULL END))  confirmtransfertail_user_id,
MAX((CASE WHEN lower(t2.matter_key)='confirmtransfertail'  THEN t2.handle_user_name ELSE NULL END))  confirmtransfertail_user_name,
MAX((CASE WHEN lower(t2.matter_key)='repaymentconfirm'  THEN t2.handle_time ELSE NULL END))  repaymentconfirm_time,
MAX((CASE WHEN lower(t2.matter_key)='repaymentconfirm'  THEN t2.handle_user_id ELSE NULL END))  repaymentconfirm_user_id,
MAX((CASE WHEN lower(t2.matter_key)='repaymentconfirm'  THEN t2.handle_user_name ELSE NULL END))  repaymentconfirm_user_name,
MAX((CASE WHEN lower(t2.matter_key)='patch_ds'  THEN t2.handle_time ELSE NULL END))  patch_ds_time,
MAX((CASE WHEN lower(t2.matter_key)='patch_ds'  THEN t2.handle_user_id ELSE NULL END))  patch_ds_user_id,
MAX((CASE WHEN lower(t2.matter_key)='patch_ds'  THEN t2.handle_user_name ELSE NULL END))  patch_ds_user_name,
MAX((CASE WHEN lower(t2.matter_key)='appointinterview'  THEN t2.handle_time ELSE NULL END))  appointinterview_time,
MAX((CASE WHEN lower(t2.matter_key)='appointinterview'  THEN t2.handle_user_id ELSE NULL END))  appointinterview_user_id,
MAX((CASE WHEN lower(t2.matter_key)='appointinterview'  THEN t2.handle_user_name ELSE NULL END))  appointinterview_user_name,
MAX((CASE WHEN lower(t2.matter_key)='verifyinsurance'  THEN t2.handle_time ELSE NULL END))  verifyinsurance_time,
MAX((CASE WHEN lower(t2.matter_key)='verifyinsurance'  THEN t2.handle_user_id ELSE NULL END))  verifyinsurance_user_id,
MAX((CASE WHEN lower(t2.matter_key)='verifyinsurance'  THEN t2.handle_user_name ELSE NULL END))  verifyinsurance_user_name,
MAX((CASE WHEN lower(t2.matter_key)='other' THEN t2.handle_time ELSE NULL END))  other_time,
MAX((CASE WHEN lower(t2.matter_key)='other' THEN t2.handle_user_id ELSE NULL END))  other_user_id,
MAX((CASE WHEN lower(t2.matter_key)='other' THEN t2.handle_user_name ELSE NULL END))  other_user_name,
MAX((CASE WHEN lower(t2.matter_key)='principaltransfer'  THEN t2.handle_time ELSE NULL END))  principaltransfer_time,
MAX((CASE WHEN lower(t2.matter_key)='principaltransfer'  THEN t2.handle_user_id ELSE NULL END))  principaltransfer_user_id,
MAX((CASE WHEN lower(t2.matter_key)='principaltransfer'  THEN t2.handle_user_name ELSE NULL END))  principaltransfer_user_name,
MAX((CASE WHEN lower(t2.matter_key)='principaltransferconfirm'  THEN t2.handle_time ELSE NULL END))  principaltransferconfirm_time,
MAX((CASE WHEN lower(t2.matter_key)='principaltransferconfirm'  THEN t2.handle_user_id ELSE NULL END))  principaltransferconfirm_user_id,
MAX((CASE WHEN lower(t2.matter_key)='principaltransferconfirm'  THEN t2.handle_user_name ELSE NULL END))  principaltransferconfirm_user_name,
MAX((CASE WHEN lower(t2.matter_key)='custreceivableconfirm'  THEN t2.handle_time ELSE NULL END))  custreceivableconfirm_time,
MAX((CASE WHEN lower(t2.matter_key)='custreceivableconfirm'  THEN t2.handle_user_id ELSE NULL END))  custreceivableconfirm_user_id,
MAX((CASE WHEN lower(t2.matter_key)='custreceivableconfirm'  THEN t2.handle_user_name ELSE NULL END))  custreceivableconfirm_user_name
from (select * from tmp_matter_record_common where rn1=1) t2 GROUP BY t2.`apply_no`) b on a.apply_no=b.apply_no;
drop table if exists ods_bpms_biz_order_matter_record_wx_common;
ALTER TABLE odstmp_bpms_biz_order_matter_record_wx_common RENAME TO ods_bpms_biz_order_matter_record_wx_common;