use ods;
drop table if  exists ods.odstmp_bpms_biz_house_transfer_common;
CREATE TABLE if not exists ods.odstmp_bpms_biz_house_transfer_common (
  id STRING COMMENT '主键id',
apply_no STRING COMMENT '订单编号',
house_no STRING COMMENT '房产信息编号关联房产信息',
cancel_mortgage_time TIMESTAMP COMMENT '注销抵押出件时间',
transfer_receipt_no STRING COMMENT '过户回执号',
transfer_expect_time TIMESTAMP COMMENT '预计过户出件时间',
new_house_no STRING COMMENT '新房产证号',
obtain_cert_expect_time TIMESTAMP COMMENT '预计取证时间',
new_house_no_time TIMESTAMP COMMENT '取新证时间',
mortgage_receipt_no STRING COMMENT '抵押回执号',
mortgage_out_time TIMESTAMP COMMENT '抵押出件时间',
mortgage_expect_time TIMESTAMP COMMENT '预计抵押出件时间',
cancel_mortgage_time_more TIMESTAMP COMMENT '注销抵押出件时间（more）',
transfer_receipt_no_more STRING COMMENT '过户回执号(more)',
transfer_post_time TIMESTAMP COMMENT '过户递件时间',
transfer_out_time TIMESTAMP COMMENT '过户出件时间',
transfer_expect_time_more TIMESTAMP COMMENT '预计过户出件时间(more)',
mortgage_receipt_no_more STRING COMMENT '抵押回执号(more)',
mortgage_expect_time_more TIMESTAMP COMMENT '预计抵押出件时间(more)',
remark STRING COMMENT '备注',
create_user_id STRING COMMENT '创建人id',
update_user_id STRING COMMENT '更新人id',
create_time TIMESTAMP COMMENT '记录创建时间',
update_time TIMESTAMP COMMENT '记录更新时间',
rev bigint comment '版本号',
delete_flag STRING COMMENT '记录删除标识(1：删除；0：有效记录)',
has_get_new_houseno STRING COMMENT '是否需要取新证',
has_transfer STRING COMMENT '是否需过户',
has_mortgage STRING COMMENT '是否需要抵押',
cancel_mortgage_remark STRING COMMENT '注销出件备注',
cancel_mortgage_more_remark STRING COMMENT '注销出件more备注',
new_house_no_remark STRING COMMENT '新房产编号备注',
has_cancel_mortgage STRING COMMENT '是否需要注销过户抵押',
mortgage_post_time TIMESTAMP COMMENT '抵押递件时间',
mortgage_expect_post_time TIMESTAMP COMMENT '预计抵押递件时间',
cancel_guanraty_time TIMESTAMP COMMENT '注销抵押时间',
rn bigint
) STORED AS parquet;
insert overwrite table odstmp_bpms_biz_house_transfer_common
select T.*,
ROW_NUMBER() OVER(PARTITION BY apply_no ORDER BY create_time asc) rn
from
( SELECT
a.id,
a.apply_no,
a.house_no,
a.cancel_mortgage_time,
a.transfer_receipt_no,
a.transfer_expect_time,
a.new_house_no,
a.obtain_cert_expect_time,
a.new_house_no_time,
a.mortgage_receipt_no,
a.mortgage_out_time,
a.mortgage_expect_time,
a.cancel_mortgage_time_more,
a.transfer_receipt_no_more,
a.transfer_post_time,
a.transfer_out_time,
a.transfer_expect_time_more,
a.mortgage_receipt_no_more,
a.mortgage_expect_time_more,
a.remark,
a.create_user_id,
a.update_user_id,
a.create_time,
a.update_time,
a.rev,
a.delete_flag,
a.has_get_new_houseno,
a.has_transfer,
a.has_mortgage,
a.cancel_mortgage_remark,
a.cancel_mortgage_more_remark,
a.new_house_no_remark,
a.has_cancel_mortgage,
a.mortgage_post_time,
a.mortgage_expect_post_time,
a.cancel_guanraty_time
FROM
( select * from ods_bpms_biz_house_transfer where apply_no<>'' and apply_no is not null ) a
union all
SELECT
a1.id,
c1.apply_no,
a1.house_no,
a1.cancel_mortgage_time,
a1.transfer_receipt_no,
a1.transfer_expect_time,
a1.new_house_no,
a1.obtain_cert_expect_time,
a1.new_house_no_time,
a1.mortgage_receipt_no,
a1.mortgage_out_time,
a1.mortgage_expect_time,
a1.cancel_mortgage_time_more,
a1.transfer_receipt_no_more,
a1.transfer_post_time,
a1.transfer_out_time,
a1.transfer_expect_time_more,
a1.mortgage_receipt_no_more,
a1.mortgage_expect_time_more,
a1.remark,
a1.create_user_id,
a1.update_user_id,
a1.create_time,
a1.update_time,
a1.rev,
a1.delete_flag,
a1.has_get_new_houseno,
a1.has_transfer,
a1.has_mortgage,
a1.cancel_mortgage_remark,
a1.cancel_mortgage_more_remark,
a1.new_house_no_remark,
a1.has_cancel_mortgage,
a1.mortgage_post_time,
a1.mortgage_expect_post_time,
a1.cancel_guanraty_time
FROM
( select * from ods_bpms_biz_house_transfer where (apply_no<>'' and apply_no is not null) and(house_no<>'' and house_no is not null ) ) a1
LEFT JOIN ( select apply_no, house_no from ods_bpms_biz_apply_order where house_no <> '' AND house_no IS NOT NULL ) c1 ON c1.house_no = a1.house_no
union all
select
b.id,
c.apply_no apply_no,
b.house_no,
b.cancel_mortgage_time,
b.transfer_receipt_no,
b.transfer_expect_time,
b.new_house_no,
b.obtain_cert_expect_time,
b.new_house_no_time,
b.mortgage_receipt_no,
b.mortgage_out_time,
b.mortgage_expect_time,
b.cancel_mortgage_time_more,
b.transfer_receipt_no_more,
b.transfer_post_time,
b.transfer_out_time,
b.transfer_expect_time_more,
b.mortgage_receipt_no_more,
b.mortgage_expect_time_more,
b.remark,
b.create_user_id,
b.update_user_id,
b.create_time,
b.update_time,
b.rev,
b.delete_flag,
b.has_get_new_houseno,
b.has_transfer,
b.has_mortgage,
b.cancel_mortgage_remark,
b.cancel_mortgage_more_remark,
b.new_house_no_remark,
b.has_cancel_mortgage,
b.mortgage_post_time,
b.mortgage_expect_post_time,
b.cancel_guanraty_time
from ( SELECT
*
FROM
ods_bpms_biz_house_transfer
WHERE
(house_no <> '' AND house_no IS NOT NULL ) and (apply_no ='' or apply_no is null )
) b
LEFT JOIN ( select apply_no, house_no from ods_bpms_biz_apply_order where house_no <> '' AND house_no IS NOT NULL ) c ON c.house_no = b.house_no
)T;
drop table if exists ods_bpms_biz_house_transfer_common;
ALTER TABLE odstmp_bpms_biz_house_transfer_common RENAME TO ods_bpms_biz_house_transfer_common;