use ods;
drop table if  exists ods.odstmp_bims_biz_repayment_plan_common;
CREATE TABLE ods.odstmp_bims_biz_repayment_plan_common (
    id STRING COMMENT '主键',
   apply_no STRING COMMENT '订单编号',
   channel STRING COMMENT '渠道（AJXT:爱建  DASHU:大数）',
   period STRING COMMENT '当前期数',
   enddate TIMESTAMP COMMENT '当前到期日',
   totalamt DOUBLE COMMENT '当前应还总金额',
   status STRING COMMENT '当期状态N 未结清 Y已结清',
   currentstatus STRING COMMENT '当期还款状态（1正常2逾期3已代偿未还款4已代偿已还款5已回购未还款6已回购已还款7结清，8回款中，9回款成功，10回款失败）',
   repaymentstauts STRING COMMENT '还款状态',
   payamount DOUBLE COMMENT '应收管理费',
   actualpayamount DOUBLE COMMENT '实收管理费',
   paymoney DOUBLE COMMENT '应收资金占用费',
   actualpaymoney DOUBLE COMMENT '实收资金占用费',
   paypenaltyamt DOUBLE COMMENT '应收罚息',
   actualpaypenaltyamt DOUBLE COMMENT '实收罚息',
   payinterestamt DOUBLE COMMENT '应收利息',
   actualpaypayinterestamt DOUBLE COMMENT '实收利息',
   payprincipalamt DOUBLE COMMENT '应收本金',
   actualpaypayprincipalamt DOUBLE COMMENT '实收本金',
   wvpaypenaltyamt DOUBLE COMMENT '应收减免罚息',
   wvactualpaypenaltyamt DOUBLE COMMENT '实收减免罚息',
   wvpayinterestamt DOUBLE COMMENT '应收减免利息',
   wvactualpaypayinterestamt DOUBLE COMMENT '实收减免利息',
   wvpayprincipalamt DOUBLE COMMENT '应收减免本金',
   wvactualpaypayprincipalamt DOUBLE COMMENT '实收减免本金',
   actualstilldate TIMESTAMP COMMENT '实还日期',
   custactualstilldate TIMESTAMP COMMENT '客户实还日期',
   shouldcompound DOUBLE COMMENT '应还复利',
   actualcompound DOUBLE COMMENT '实还复利',
   payguaranteefee DOUBLE COMMENT '应收担保费（月担保费）',
   consulefee DOUBLE COMMENT '应收评审费（前置担保费）',
   actualconsulefee DOUBLE COMMENT '实收评审费（前置担保费）',
   monthpremium DOUBLE COMMENT '月保费',
   actualmonthpremium DOUBLE COMMENT '实收月保费',
   prepremiums DOUBLE COMMENT '前置保费',
   actualprepremiums DOUBLE COMMENT '实收前置保费',
   premiumoverduefine DOUBLE COMMENT '保费逾期罚息',
   actualpremiumoverduefine DOUBLE COMMENT '实收保费逾期罚息',
   compensatoryprincipal DOUBLE COMMENT '代偿本金',
   actualcompensatoryprincipal DOUBLE COMMENT '实收代偿本金',
   compensatoryinteresttotal DOUBLE COMMENT '代偿利息合计',
   actualcompensatoryinteresttotal DOUBLE COMMENT '实收代偿利息合计',
   compensatoryotherfeetotal DOUBLE COMMENT '代偿其他费用合计',
   actualcompensatoryotherfeetotal DOUBLE COMMENT '实收代偿其他费用合计',
   compensatorylatefeetotal DOUBLE COMMENT '代偿滞纳金合计',
   actualcompensatorylatefeetotal DOUBLE COMMENT '实收代偿滞纳金合计',
   earlypaypenalty DOUBLE COMMENT '提前还款违约金',
   actualearlypaypenalty DOUBLE COMMENT '实收提前还款违约金',
   buybackprincipal DOUBLE COMMENT '回购/理赔本金',
   actualbuybackprincipal DOUBLE COMMENT '实收回购/理赔本金',
   buybackinterest DOUBLE COMMENT '回购/理赔利息',
   actualbuybackinterest DOUBLE COMMENT '实收回购/理赔利息',
   buybackotherfee DOUBLE COMMENT '回购/理赔其他费用',
   actualbuybackotherfee DOUBLE COMMENT '实收回购/理赔其他费用',
   buybackoverduefee DOUBLE COMMENT '回购/理赔逾期费用',
   actualbuybackoverduefee DOUBLE COMMENT '实收回购/理赔逾期费用',
   latefee DOUBLE COMMENT '滞纳金',
   actuallatefee DOUBLE COMMENT '实收滞纳金',
   derateamount DOUBLE COMMENT '减免金额',
   actualpayguaranteefee DOUBLE COMMENT '实收担保费（月担保费）',
   remark STRING COMMENT '备注',
   create_user_id STRING COMMENT '创建人id',
   update_user_id STRING COMMENT '更新人id',
   create_time TIMESTAMP COMMENT '创建时间',
   update_time TIMESTAMP COMMENT '更新时间',
   rev bigint comment '版本号',
   delete_flag STRING COMMENT '记录删除标识(1：删除；0：有效记录)' ,
   currentstatus_name STRING COMMENT '当期还款状态名',
   rn bigint
   )  STORED AS parquet;
insert overwrite table odstmp_bims_biz_repayment_plan_common
select T.*,ROW_NUMBER() OVER(PARTITION BY apply_no ORDER BY endDate desc) rn from (
select
a.`id`,
a.`apply_no`,
a.`channel`,
a.`period`,
a.`enddate`,
a.`totalamt`,
a.`status`,
a.`currentstatus`,
a.`repaymentstauts`,
a.`payamount`,
a.`actualpayamount`,
a.`paymoney`,
a.`actualpaymoney`,
a.`paypenaltyamt`,
a.`actualpaypenaltyamt`,
a.`payinterestamt`,
a.`actualpaypayinterestamt`,
a.`payprincipalamt`,
a.`actualpaypayprincipalamt`,
a.`wvpaypenaltyamt`,
a.`wvactualpaypenaltyamt`,
a.`wvpayinterestamt`,
a.`wvactualpaypayinterestamt`,
a.`wvpayprincipalamt`,
a.`wvactualpaypayprincipalamt`,
a.`actualstilldate`,
a.`custactualstilldate`,
a.`shouldcompound`,
a.`actualcompound`,
a.`payguaranteefee`,
a.`consulefee`,
a.`actualconsulefee`,
a.`monthpremium`,
a.`actualmonthpremium`,
a.`prepremiums`,
a.`actualprepremiums`,
a.`premiumoverduefine`,
a.`actualpremiumoverduefine`,
a.`compensatoryprincipal`,
a.`actualcompensatoryprincipal`,
a.`compensatoryinteresttotal`,
a.`actualcompensatoryinteresttotal`,
a.`compensatoryotherfeetotal`,
a.`actualcompensatoryotherfeetotal`,
a.`compensatorylatefeetotal`,
a.`actualcompensatorylatefeetotal`,
a.`earlypaypenalty`,
a.`actualearlypaypenalty`,
a.`buybackprincipal`,
a.`actualbuybackprincipal`,
a.`buybackinterest`,
a.`actualbuybackinterest`,
a.`buybackotherfee`,
a.`actualbuybackotherfee`,
a.`buybackoverduefee`,
a.`actualbuybackoverduefee`,
a.`latefee`,
a.`actuallatefee`,
a.`derateamount`,
a.`actualpayguaranteefee`,
a.`remark`,
a.`create_user_id`,
a.`update_user_id`,
a.`create_time`,
a.`update_time`,
a.`rev`,
a.`delete_flag`,
case a.`currentstatus`
when '1' then '正常'
when '2' then '逾期'
when '3' then '已代偿未还款'
when '4' then '已代偿已还款'
when '5' then '已回购未还款'
when '6' then '已回购已还款'
when '7' then '结清'
when '8' then '回款中'
when '9' then '回款成功'
when '10' then '回款失败'
end currentstatus_name
from ods_bims_biz_repayment_plan a
)T;
drop table if exists ods_bims_biz_repayment_plan_common;
ALTER TABLE odstmp_bims_biz_repayment_plan_common RENAME TO ods_bims_biz_repayment_plan_common;