use ods;
CREATE TABLE if not exists ods.odstmp_bims_biz_p2p_ret_wx (
  apply_no STRING COMMENT '订单编号',
  loan_status_name string COMMENT '放款返回状态',
  loan_create_time timestamp comment '放款时间',
 `loan_result` string COMMENT '放款返回结果',
  loan_description STRING COMMENT '放款返回结果备注',
loan_receipt_status_name string COMMENT '放款回执返回状态',
  loan_receipt_create_time timestamp comment '放款回执时间',
 `loan_receipt_result` string COMMENT '放款回执返回结果',
  loan_receipt_description STRING COMMENT '放款回执返回结果备注',
push_plan_to_dashu_status_name string COMMENT '推送还款计划返回状态',
  push_plan_to_dashu_create_time timestamp comment '推送还款计划时间',
 `push_plan_to_dashu_result` string COMMENT '推送还款计划返回结果',
  push_plan_to_dashu_description STRING COMMENT '推送还款计划返回结果备注',
push_repayplan_status_name string COMMENT '推送还款计划到资方返回状态',
  push_repayplan_create_time timestamp comment '推送还款计划到资方时间',
 `push_repayplan_result` string COMMENT '推送还款计划到资方返回结果',
  push_repayplan_description STRING COMMENT '推送还款计划到资方返回结果备注',
query_ajxt_plan_status_name string COMMENT '获取还款计划返回状态',
  query_ajxt_plan_create_time timestamp comment '获取还款计划时间',
 `query_ajxt_plan_result` string COMMENT '获取还款计划返回结果',
  query_ajxt_plan_description STRING COMMENT '获取还款计划返回结果备注',
query_dashu_plan_status_name string COMMENT '查询大数还款计划返回状态',
  query_dashu_plan_create_time timestamp comment '查询大数还款计划时间',
 `query_dashu_plan_result` string COMMENT '查询大数还款计划返回结果',
  query_dashu_plan_description STRING COMMENT '查询大数还款计划返回结果备注',
team_org_approve_status_name string COMMENT '合作机构审批返回状态',
  team_org_approve_create_time timestamp comment '合作机构审批时间',
 `team_org_approve_result` string COMMENT '合作机构审批返回结果',
  team_org_approve_description STRING COMMENT '合作机构审批返回结果备注'
) STORED AS parquet;
insert overwrite table  odstmp_bims_biz_p2p_ret_wx
select t.`apply_no`,
max((case when lower(t.`task_name`)='loan' then t.`status_name` else null end)) loan_status_name ,
max((case when lower(t.`task_name`)='loan' then t.`create_time` else null end)) loan_create_time ,
max((case when lower(t.`task_name`)='loan' then t.`result` else null end)) loan_result ,
max((case when lower(t.`task_name`)='loan' then t.`description` else null end)) loan_description ,
max((case when lower(t.`task_name`)='loan_receipt' then t.`status_name` else null end)) loan_receipt_status_name ,
max((case when lower(t.`task_name`)='loan_receipt' then t.`create_time` else null end)) loan_receipt_create_time ,
max((case when lower(t.`task_name`)='loan_receipt' then t.`result` else null end)) loan_receipt_result ,
max((case when lower(t.`task_name`)='loan_receipt' then t.`description` else null end)) loan_receipt_description ,
max((case when lower(t.`task_name`)='push_plan_to_dashu' then t.`status_name` else null end)) push_plan_to_dashu_status_name ,
max((case when lower(t.`task_name`)='push_plan_to_dashu' then t.`create_time` else null end)) push_plan_to_dashu_create_time ,
max((case when lower(t.`task_name`)='push_plan_to_dashu' then t.`result` else null end)) push_plan_to_dashu_result ,
max((case when lower(t.`task_name`)='push_plan_to_dashu' then t.`description` else null end)) push_plan_to_dashu_description ,
max((case when lower(t.`task_name`)='push_repayplan' then t.`status_name` else null end)) push_repayplan_status_name ,
max((case when lower(t.`task_name`)='push_repayplan' then t.`create_time` else null end)) push_repayplan_create_time ,
max((case when lower(t.`task_name`)='push_repayplan' then t.`result` else null end)) push_repayplan_result ,
max((case when lower(t.`task_name`)='push_repayplan' then t.`description` else null end)) push_repayplan_description ,
max((case when lower(t.`task_name`)='query_ajxt_plan' then t.`status_name` else null end)) query_ajxt_plan_status_name ,
max((case when lower(t.`task_name`)='query_ajxt_plan' then t.`create_time` else null end)) query_ajxt_plan_create_time ,
max((case when lower(t.`task_name`)='query_ajxt_plan' then t.`result` else null end)) query_ajxt_plan_result ,
max((case when lower(t.`task_name`)='query_ajxt_plan' then t.`description` else null end)) query_ajxt_plan_description ,
max((case when lower(t.`task_name`)='query_dashu_plan' then t.`status_name` else null end)) query_dashu_plan_status_name ,
max((case when lower(t.`task_name`)='query_dashu_plan' then t.`create_time` else null end)) query_dashu_plan_create_time ,
max((case when lower(t.`task_name`)='query_dashu_plan' then t.`result` else null end)) query_dashu_plan_result ,
max((case when lower(t.`task_name`)='query_dashu_plan' then t.`description` else null end)) query_dashu_plan_description ,
max((case when lower(t.`task_name`)='team_org_approve' then t.`status_name` else null end)) team_org_approve_status_name ,
max((case when lower(t.`task_name`)='team_org_approve' then t.`create_time` else null end)) team_org_approve_create_time ,
max((case when lower(t.`task_name`)='team_org_approve' then t.`result` else null end)) team_org_approve_result ,
max((case when lower(t.`task_name`)='team_org_approve' then t.`description` else null end)) team_org_approve_description
from ods_bims_biz_p2p_ret_common t group by t.`apply_no`;
drop table if exists ods_bims_biz_p2p_ret_common_wx;
ALTER TABLE odstmp_bims_biz_p2p_ret_wx RENAME TO ods_bims_biz_p2p_ret_common_wx;