use ods;
drop table if  exists ods.odstmp_bpms_ods_bpms_biz_house_common;
CREATE TABLE if not exists ods.odstmp_bpms_ods_bpms_biz_house_common (
  id STRING COMMENT 'ID',
  apply_no STRING COMMENT '订单编号',
  house_no STRING COMMENT '房产编号',
  cert_type STRING COMMENT '房产证类型',
  house_cert_no STRING COMMENT '产证编号',
  new_house_cert_no STRING COMMENT '新房产证编号',
  house_type STRING COMMENT '房产用途',
  house_area STRING COMMENT '所在区域',
  house_address STRING COMMENT '房产地址（坐落）',
  house_acreage STRING COMMENT '房屋面积',
  register_price DOUBLE COMMENT '登记价（元）',
  register_time timestamp COMMENT '登记日期',
  completion_time timestamp COMMENT '竣工日期',
  land_expiry STRING COMMENT '土地使用期限',
  land_right_no STRING COMMENT '丘权号',
  remark STRING COMMENT '备注',
  property_owner_info STRING COMMENT '产权人相关信息',
  create_user_id STRING COMMENT '创建人id',
  update_user_id STRING COMMENT '更新人id',
  create_time timestamp COMMENT '记录创建时间',
  update_time timestamp COMMENT '记录更新时间',
  rev bigint comment '版本号',
  delete_flag STRING COMMENT '记录删除标识(1：删除；0：有效记录)',
  house_age STRING COMMENT '房龄',
  housing_status STRING COMMENT '房屋现状(对应字典表fwxz)',
  house_property STRING COMMENT '房屋性质',
  house_type_other STRING COMMENT '房产用途其他',
  house_location STRING COMMENT '房产证地址（省份、直辖市、自治区, （广东省，深圳市，南山区）逗号分隔）',
  house_location_province STRING COMMENT '省',
  house_location_city STRING COMMENT '市',
  house_area_code STRING COMMENT '区域编码',
  interior_house_acreage STRING COMMENT '套内建筑面积',
  borrower_equity DOUBLE COMMENT '借款人产权份额',
  owner_type STRING COMMENT '共有情况',
  owner_number bigint comment '共有产权人数',
  mortgage_time timestamp COMMENT '抵押日期',
  mortgage_struct STRING COMMENT '抵押物房屋结构',
  mortgage_type STRING COMMENT '抵押物房屋类型',
  mortgage_status STRING COMMENT '抵押状态',
  rent_status STRING COMMENT '出租情况',
  right_property STRING COMMENT '权利性质',
  right_type STRING COMMENT '权利类型',
  total_floor bigint comment '总层数',
  prop_buy_time timestamp COMMENT '购房日期',
  project_name STRING COMMENT '楼盘名称',
  is_only_house STRING,
  fxt_area_code STRING COMMENT '房讯通区域编码',
  fxt_area_name STRING COMMENT '房讯通区域名称',
  house_village_name STRING,
  house_building_no STRING,
  house_floor_no STRING,
  house_room_no STRING,
  build_year STRING,
  land_type STRING COMMENT '土地类型',
  is_second_mortgage STRING COMMENT '是否在我司二押',
  house_mold STRING COMMENT '房产类型',
  loan_agency_type STRING COMMENT '贷款机构类型',
  loan_agency_name STRING COMMENT '贷款机构名称',
  mortgage_right_amount STRING COMMENT '抵押债权金额',
  other_estate_type STRING COMMENT '其他房产类型',
  comprehensive_average_price DOUBLE COMMENT '综合评估均价',
  comprehensive_evaluation_price DOUBLE COMMENT '综合评估总价',
  in_reserve_house STRING COMMENT '是否备用房',
  cert_type_name STRING,
  house_type_name STRING,
  rn bigint
) STORED AS parquet;

insert overwrite table odstmp_bpms_ods_bpms_biz_house_common
select AT.*,ROW_NUMBER() OVER(PARTITION BY apply_no ORDER BY create_time asc) rn from (
select T.*,
d.NAME_ `cert_type_name`,
e.NAME_ `house_type_name`
from (select
a.id,
b.apply_no apply_no,
a.house_no,
a.cert_type,
a.house_cert_no,
a.new_house_cert_no,
a.house_type,
a.house_area,
a.house_address,
a.house_acreage,
a.register_price,
a.register_date,
a.completion_date,
a.land_expiry,
a.land_right_no,
a.remark,
a.property_owner_info,
a.create_user_id,
a.update_user_id,
a.create_time,
a.update_time,
a.rev,
a.delete_flag,
a.house_age,
a.housing_status,
a.house_property,
a.house_type_other,
a.house_location,
a.house_location_province,
a.house_location_city,
a.house_area_code,
a.interior_house_acreage,
a.borrower_equity,
a.owner_type,
a.owner_number,
a.mortgage_date,
a.mortgage_struct,
a.mortgage_type,
a.mortgage_status,
a.rent_status,
a.right_property,
a.right_type,
a.total_floor,
a.prop_buy_time,
a.project_name,
a.is_only_house,
a.fxt_area_code,
a.fxt_area_name,
a.house_village_name,
a.house_building_no,
a.house_floor_no,
a.house_room_no,
a.build_year,
a.land_type,
a.is_second_mortgage,
a.house_mold,
a.loan_agency_type,
a.loan_agency_name,
a.mortgage_right_amount,
a.other_estate_type,
a.comprehensive_average_price,
a.comprehensive_evaluation_price,
a.in_reserve_house -- 37316
 from (SELECT
	*
FROM
	ods_bpms_biz_house
WHERE
	(
		(apply_no = '' or apply_no is null)
		AND house_no <> ''
		AND house_no IS NOT NULL
	)) a
LEFT JOIN (SELECT apply_no,house_no from  ods_bpms_biz_apply_order where house_no <> '' and house_no IS NOT NULL ) b ON b.house_no = a.house_no
union ALL
SELECT
		a.id,
a.apply_no apply_no,
a.house_no,
a.cert_type,
a.house_cert_no,
a.new_house_cert_no,
a.house_type,
a.house_area,
a.house_address,
a.house_acreage,
a.register_price,
a.register_date,
a.completion_date,
a.land_expiry,
a.land_right_no,
a.remark,
a.property_owner_info,
a.create_user_id,
a.update_user_id,
a.create_time,
a.update_time,
a.rev,
a.delete_flag,
a.house_age,
a.housing_status,
a.house_property,
a.house_type_other,
a.house_location,
a.house_location_province,
a.house_location_city,
a.house_area_code,
a.interior_house_acreage,
a.borrower_equity,
a.owner_type,
a.owner_number,
a.mortgage_date,
a.mortgage_struct,
a.mortgage_type,
a.mortgage_status,
a.rent_status,
a.right_property,
a.right_type,
a.total_floor,
a.prop_buy_time,
a.project_name,
a.is_only_house,
a.fxt_area_code,
a.fxt_area_name,
a.house_village_name,
a.house_building_no,
a.house_floor_no,
a.house_room_no,
a.build_year,
a.land_type,
a.is_second_mortgage,
a.house_mold,
a.loan_agency_type,
a.loan_agency_name,
a.mortgage_right_amount,
a.other_estate_type,
a.comprehensive_average_price,
a.comprehensive_evaluation_price,
a.in_reserve_house
FROM
	ods_bpms_biz_house a
WHERE apply_no <> '' and  apply_no is not null) T
left join (select DISTINCT KEY_,NAME_new_ NAME_ from ods_bpms_sys_dic_common where TYPE_ID_='10000010830911' or TYPE_ID_='10000057530172' or TYPE_ID_='10000034210010' or TYPE_ID_='10000025010002' or  TYPE_ID_='10000001220223' or TYPE_ID_='10000034210010' or TYPE_ID_='1000000122021' or TYPE_ID_='10000033770002' )d on d.KEY_=T.cert_type
left join (select DISTINCT KEY_,NAME_new_ NAME_ from ods_bpms_sys_dic_common where TYPE_ID_='10000001220242' or TYPE_ID_='10000010830911' or TYPE_ID_='10000057530172' or TYPE_ID_='10000034210010' or TYPE_ID_='10000025010002' or  TYPE_ID_='10000001220223' or TYPE_ID_='10000034210010' or TYPE_ID_='1000000122021' or TYPE_ID_='10000033770002' or TYPE_ID_='10000028440005' or TYPE_ID_='10000001220242' or TYPE_ID_='10000044981244')e on e.KEY_=T.house_type)AT;
drop table if exists ods_bpms_biz_house_common;
ALTER TABLE odstmp_bpms_ods_bpms_biz_house_common RENAME TO ods_bpms_biz_house_common;